

set RtlHierarchyInfo {[
	{"ID" : "0", "Level" : "0", "Path" : "`AUTOTB_DUT_INST", "Parent" : "", "Child" : ["1"],
		"CDFG" : "run_head_group",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "5", "EstimateLatencyMax" : "7",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "head_ctx_ref", "Type" : "Memory", "Direction" : "IO"},
			{"Name" : "res", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "layer_idx", "Type" : "None", "Direction" : "I"},
			{"Name" : "group_idx", "Type" : "None", "Direction" : "I"},
			{"Name" : "reset_resources", "Type" : "None", "Direction" : "I"},
			{"Name" : "wl_ready", "Type" : "None", "Direction" : "I"},
			{"Name" : "dma_done", "Type" : "None", "Direction" : "I"},
			{"Name" : "compute_ready", "Type" : "None", "Direction" : "I"},
			{"Name" : "compute_done", "Type" : "None", "Direction" : "I"},
			{"Name" : "requant_ready", "Type" : "None", "Direction" : "I"},
			{"Name" : "requant_done", "Type" : "None", "Direction" : "I"},
			{"Name" : "wl_start", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "wl_addr_sel", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "wl_layer", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "wl_head", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "wl_tile", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "compute_start", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "compute_op", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "requant_start", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "requant_op", "Type" : "Vld", "Direction" : "O"}]},
	{"ID" : "1", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.sparsemux_7_2_1_1_1_U1", "Parent" : "0"}]}
