-- ==============================================================
-- Generated by Vitis HLS v2025.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity run_single_head is
port (
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    ctx_i : IN STD_LOGIC_VECTOR (76 downto 0);
    ctx_o : OUT STD_LOGIC_VECTOR (76 downto 0);
    ctx_o_ap_vld : OUT STD_LOGIC;
    head_idx : IN STD_LOGIC_VECTOR (31 downto 0);
    layer_idx : IN STD_LOGIC_VECTOR (31 downto 0);
    ap_return : OUT STD_LOGIC_VECTOR (0 downto 0);
    ap_rst : IN STD_LOGIC );
end;


architecture behav of run_single_head is 
    attribute CORE_GENERATION_INFO : STRING;
    attribute CORE_GENERATION_INFO of behav : architecture is
    "run_single_head_run_single_head,hls_ip_2025_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xck26-sfvc784-2LV-c,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=3.819500,HLS_SYN_LAT=0,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=0,HLS_SYN_LUT=232,HLS_VERSION=2025_1}";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv8_0 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    constant ap_const_lv8_1 : STD_LOGIC_VECTOR (7 downto 0) := "00000001";
    constant ap_const_lv8_4 : STD_LOGIC_VECTOR (7 downto 0) := "00000100";
    constant ap_const_lv8_D : STD_LOGIC_VECTOR (7 downto 0) := "00001101";
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_const_lv32_2A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000101010";
    constant ap_const_lv32_29 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000101001";
    constant ap_const_lv32_2B : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000101011";
    constant ap_const_lv32_28 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000101000";
    constant ap_const_lv2_2 : STD_LOGIC_VECTOR (1 downto 0) := "10";
    constant ap_const_lv32_20 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000100000";
    constant ap_const_lv32_27 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000100111";
    constant ap_const_lv3_5 : STD_LOGIC_VECTOR (2 downto 0) := "101";
    constant ap_const_boolean_1 : BOOLEAN := true;

    signal or_ln_fu_346_p4 : STD_LOGIC_VECTOR (43 downto 0);
    signal ap_phi_mux_ctx_new_0_phi_fu_94_p6 : STD_LOGIC_VECTOR (43 downto 0);
    signal tmp_1_fu_316_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_3_fu_324_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln27_fu_306_p3 : STD_LOGIC_VECTOR (43 downto 0);
    signal ap_phi_mux_empty_phi_fu_105_p6 : STD_LOGIC_VECTOR (0 downto 0);
    signal zext_ln38_fu_357_p1 : STD_LOGIC_VECTOR (46 downto 0);
    signal ap_phi_mux_ctx_new_1_phi_fu_119_p26 : STD_LOGIC_VECTOR (46 downto 0);
    signal trunc_ln3_fu_368_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal zext_ln73_fu_431_p1 : STD_LOGIC_VECTOR (46 downto 0);
    signal grp_fu_262_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal sext_ln69_fu_408_p1 : STD_LOGIC_VECTOR (46 downto 0);
    signal grp_fu_244_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal zext_ln61_fu_471_p1 : STD_LOGIC_VECTOR (46 downto 0);
    signal or_ln4_fu_440_p5 : STD_LOGIC_VECTOR (46 downto 0);
    signal zext_ln49_fu_519_p1 : STD_LOGIC_VECTOR (46 downto 0);
    signal zext_ln45_fu_496_p1 : STD_LOGIC_VECTOR (46 downto 0);
    signal ap_phi_mux_empty_6_phi_fu_150_p26 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_phi_mux_empty_7_phi_fu_194_p26 : STD_LOGIC_VECTOR (7 downto 0);
    signal xor_ln80_fu_535_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_phi_mux_finished_phi_fu_237_p4 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln80_fu_529_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln27_fu_292_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal icmp_ln27_fu_296_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal zext_ln27_fu_302_p1 : STD_LOGIC_VECTOR (43 downto 0);
    signal trunc_ln23_fu_288_p1 : STD_LOGIC_VECTOR (43 downto 0);
    signal tmp_fu_332_p4 : STD_LOGIC_VECTOR (1 downto 0);
    signal trunc_ln33_fu_342_p1 : STD_LOGIC_VECTOR (39 downto 0);
    signal grp_fu_252_p4 : STD_LOGIC_VECTOR (2 downto 0);
    signal trunc_ln68_fu_392_p1 : STD_LOGIC_VECTOR (39 downto 0);
    signal or_ln6_fu_396_p5 : STD_LOGIC_VECTOR (44 downto 0);
    signal grp_fu_270_p4 : STD_LOGIC_VECTOR (1 downto 0);
    signal grp_fu_280_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln71_fu_413_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal or_ln5_fu_417_p6 : STD_LOGIC_VECTOR (43 downto 0);
    signal trunc_ln56_fu_436_p1 : STD_LOGIC_VECTOR (39 downto 0);
    signal trunc_ln59_fu_453_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal or_ln3_fu_457_p6 : STD_LOGIC_VECTOR (43 downto 0);
    signal trunc_ln44_fu_476_p1 : STD_LOGIC_VECTOR (39 downto 0);
    signal or_ln2_fu_480_p5 : STD_LOGIC_VECTOR (44 downto 0);
    signal sext_ln45_fu_492_p1 : STD_LOGIC_VECTOR (45 downto 0);
    signal trunc_ln47_fu_501_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal or_ln1_fu_505_p6 : STD_LOGIC_VECTOR (43 downto 0);
    signal ap_ce_reg : STD_LOGIC;


begin



    ap_done <= ap_start;
    ap_idle <= ap_const_logic_1;

    ap_phi_mux_ctx_new_0_phi_fu_94_p6_assign_proc : process(or_ln_fu_346_p4, tmp_1_fu_316_p3, tmp_3_fu_324_p3, select_ln27_fu_306_p3)
    begin
        if (((tmp_1_fu_316_p3 = ap_const_lv1_0) or ((tmp_3_fu_324_p3 = ap_const_lv1_0) and (tmp_1_fu_316_p3 = ap_const_lv1_1)))) then 
            ap_phi_mux_ctx_new_0_phi_fu_94_p6 <= select_ln27_fu_306_p3;
        elsif (((tmp_3_fu_324_p3 = ap_const_lv1_1) and (tmp_1_fu_316_p3 = ap_const_lv1_1))) then 
            ap_phi_mux_ctx_new_0_phi_fu_94_p6 <= or_ln_fu_346_p4;
        else 
            ap_phi_mux_ctx_new_0_phi_fu_94_p6 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    ap_phi_mux_ctx_new_1_phi_fu_119_p26_assign_proc : process(ap_phi_mux_empty_phi_fu_105_p6, zext_ln38_fu_357_p1, trunc_ln3_fu_368_p4, zext_ln73_fu_431_p1, grp_fu_262_p3, sext_ln69_fu_408_p1, grp_fu_244_p3, zext_ln61_fu_471_p1, or_ln4_fu_440_p5, zext_ln49_fu_519_p1, zext_ln45_fu_496_p1)
    begin
        if (((grp_fu_244_p3 = ap_const_lv1_1) and (trunc_ln3_fu_368_p4 = ap_const_lv8_0) and (ap_phi_mux_empty_phi_fu_105_p6 = ap_const_lv1_0))) then 
            ap_phi_mux_ctx_new_1_phi_fu_119_p26 <= zext_ln45_fu_496_p1;
        elsif (((grp_fu_262_p3 = ap_const_lv1_1) and (trunc_ln3_fu_368_p4 = ap_const_lv8_0) and (ap_phi_mux_empty_phi_fu_105_p6 = ap_const_lv1_1))) then 
            ap_phi_mux_ctx_new_1_phi_fu_119_p26 <= zext_ln49_fu_519_p1;
        elsif (((grp_fu_244_p3 = ap_const_lv1_1) and (trunc_ln3_fu_368_p4 = ap_const_lv8_1) and (ap_phi_mux_empty_phi_fu_105_p6 = ap_const_lv1_0))) then 
            ap_phi_mux_ctx_new_1_phi_fu_119_p26 <= or_ln4_fu_440_p5;
        elsif (((grp_fu_262_p3 = ap_const_lv1_1) and (trunc_ln3_fu_368_p4 = ap_const_lv8_1) and (ap_phi_mux_empty_phi_fu_105_p6 = ap_const_lv1_1))) then 
            ap_phi_mux_ctx_new_1_phi_fu_119_p26 <= zext_ln61_fu_471_p1;
        elsif (((grp_fu_244_p3 = ap_const_lv1_1) and (trunc_ln3_fu_368_p4 = ap_const_lv8_4) and (ap_phi_mux_empty_phi_fu_105_p6 = ap_const_lv1_0))) then 
            ap_phi_mux_ctx_new_1_phi_fu_119_p26 <= sext_ln69_fu_408_p1;
        elsif (((grp_fu_262_p3 = ap_const_lv1_1) and (trunc_ln3_fu_368_p4 = ap_const_lv8_4) and (ap_phi_mux_empty_phi_fu_105_p6 = ap_const_lv1_1))) then 
            ap_phi_mux_ctx_new_1_phi_fu_119_p26 <= zext_ln73_fu_431_p1;
        elsif ((((grp_fu_244_p3 = ap_const_lv1_0) and (trunc_ln3_fu_368_p4 = ap_const_lv8_4) and (ap_phi_mux_empty_phi_fu_105_p6 = ap_const_lv1_0)) or ((grp_fu_244_p3 = ap_const_lv1_0) and (trunc_ln3_fu_368_p4 = ap_const_lv8_1) and (ap_phi_mux_empty_phi_fu_105_p6 = ap_const_lv1_0)) or ((grp_fu_244_p3 = ap_const_lv1_0) and (trunc_ln3_fu_368_p4 = ap_const_lv8_0) and (ap_phi_mux_empty_phi_fu_105_p6 = ap_const_lv1_0)) or ((grp_fu_262_p3 = ap_const_lv1_0) and (trunc_ln3_fu_368_p4 = ap_const_lv8_4) and (ap_phi_mux_empty_phi_fu_105_p6 = ap_const_lv1_1)) or ((grp_fu_262_p3 = ap_const_lv1_0) and (trunc_ln3_fu_368_p4 = ap_const_lv8_1) and (ap_phi_mux_empty_phi_fu_105_p6 = ap_const_lv1_1)) or ((grp_fu_262_p3 = ap_const_lv1_0) and (trunc_ln3_fu_368_p4 = ap_const_lv8_0) and (ap_phi_mux_empty_phi_fu_105_p6 = ap_const_lv1_1)) or (not((trunc_ln3_fu_368_p4 = ap_const_lv8_4)) and not((trunc_ln3_fu_368_p4 = ap_const_lv8_1)) and not((trunc_ln3_fu_368_p4 = ap_const_lv8_0))))) then 
            ap_phi_mux_ctx_new_1_phi_fu_119_p26 <= zext_ln38_fu_357_p1;
        else 
            ap_phi_mux_ctx_new_1_phi_fu_119_p26 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    ap_phi_mux_empty_6_phi_fu_150_p26_assign_proc : process(ap_phi_mux_empty_phi_fu_105_p6, trunc_ln3_fu_368_p4, grp_fu_262_p3, grp_fu_244_p3)
    begin
        if ((((grp_fu_244_p3 = ap_const_lv1_0) and (trunc_ln3_fu_368_p4 = ap_const_lv8_4) and (ap_phi_mux_empty_phi_fu_105_p6 = ap_const_lv1_0)) or ((grp_fu_244_p3 = ap_const_lv1_0) and (trunc_ln3_fu_368_p4 = ap_const_lv8_1) and (ap_phi_mux_empty_phi_fu_105_p6 = ap_const_lv1_0)) or ((grp_fu_244_p3 = ap_const_lv1_0) and (trunc_ln3_fu_368_p4 = ap_const_lv8_0) and (ap_phi_mux_empty_phi_fu_105_p6 = ap_const_lv1_0)))) then 
            ap_phi_mux_empty_6_phi_fu_150_p26 <= ap_const_lv1_0;
        elsif ((((grp_fu_244_p3 = ap_const_lv1_1) and (trunc_ln3_fu_368_p4 = ap_const_lv8_4) and (ap_phi_mux_empty_phi_fu_105_p6 = ap_const_lv1_0)) or ((grp_fu_244_p3 = ap_const_lv1_1) and (trunc_ln3_fu_368_p4 = ap_const_lv8_1) and (ap_phi_mux_empty_phi_fu_105_p6 = ap_const_lv1_0)) or ((grp_fu_244_p3 = ap_const_lv1_1) and (trunc_ln3_fu_368_p4 = ap_const_lv8_0) and (ap_phi_mux_empty_phi_fu_105_p6 = ap_const_lv1_0)) or ((grp_fu_262_p3 = ap_const_lv1_0) and (trunc_ln3_fu_368_p4 = ap_const_lv8_4) and (ap_phi_mux_empty_phi_fu_105_p6 = ap_const_lv1_1)) or ((grp_fu_262_p3 = ap_const_lv1_0) and (trunc_ln3_fu_368_p4 = ap_const_lv8_1) and (ap_phi_mux_empty_phi_fu_105_p6 = ap_const_lv1_1)) or ((grp_fu_262_p3 = ap_const_lv1_0) and (trunc_ln3_fu_368_p4 = ap_const_lv8_0) and (ap_phi_mux_empty_phi_fu_105_p6 = ap_const_lv1_1)) or ((grp_fu_262_p3 = ap_const_lv1_1) and (trunc_ln3_fu_368_p4 = ap_const_lv8_4) and (ap_phi_mux_empty_phi_fu_105_p6 = ap_const_lv1_1)) or ((grp_fu_262_p3 = ap_const_lv1_1) and (trunc_ln3_fu_368_p4 = ap_const_lv8_1) and 
    (ap_phi_mux_empty_phi_fu_105_p6 = ap_const_lv1_1)) or ((grp_fu_262_p3 = ap_const_lv1_1) and (trunc_ln3_fu_368_p4 = ap_const_lv8_0) and (ap_phi_mux_empty_phi_fu_105_p6 = ap_const_lv1_1)))) then 
            ap_phi_mux_empty_6_phi_fu_150_p26 <= ap_const_lv1_1;
        elsif ((not((trunc_ln3_fu_368_p4 = ap_const_lv8_4)) and not((trunc_ln3_fu_368_p4 = ap_const_lv8_1)) and not((trunc_ln3_fu_368_p4 = ap_const_lv8_0)))) then 
            ap_phi_mux_empty_6_phi_fu_150_p26 <= ap_phi_mux_empty_phi_fu_105_p6;
        else 
            ap_phi_mux_empty_6_phi_fu_150_p26 <= "X";
        end if; 
    end process;


    ap_phi_mux_empty_7_phi_fu_194_p26_assign_proc : process(ap_phi_mux_ctx_new_0_phi_fu_94_p6, ap_phi_mux_empty_phi_fu_105_p6, trunc_ln3_fu_368_p4, grp_fu_262_p3, grp_fu_244_p3)
    begin
        if ((((grp_fu_244_p3 = ap_const_lv1_0) and (trunc_ln3_fu_368_p4 = ap_const_lv8_0) and (ap_phi_mux_empty_phi_fu_105_p6 = ap_const_lv1_0)) or ((grp_fu_244_p3 = ap_const_lv1_1) and (trunc_ln3_fu_368_p4 = ap_const_lv8_0) and (ap_phi_mux_empty_phi_fu_105_p6 = ap_const_lv1_0)) or ((grp_fu_262_p3 = ap_const_lv1_0) and (trunc_ln3_fu_368_p4 = ap_const_lv8_0) and (ap_phi_mux_empty_phi_fu_105_p6 = ap_const_lv1_1)))) then 
            ap_phi_mux_empty_7_phi_fu_194_p26 <= ap_const_lv8_0;
        elsif ((((grp_fu_244_p3 = ap_const_lv1_0) and (trunc_ln3_fu_368_p4 = ap_const_lv8_1) and (ap_phi_mux_empty_phi_fu_105_p6 = ap_const_lv1_0)) or ((grp_fu_244_p3 = ap_const_lv1_1) and (trunc_ln3_fu_368_p4 = ap_const_lv8_1) and (ap_phi_mux_empty_phi_fu_105_p6 = ap_const_lv1_0)) or ((grp_fu_262_p3 = ap_const_lv1_0) and (trunc_ln3_fu_368_p4 = ap_const_lv8_1) and (ap_phi_mux_empty_phi_fu_105_p6 = ap_const_lv1_1)) or ((grp_fu_262_p3 = ap_const_lv1_1) and (trunc_ln3_fu_368_p4 = ap_const_lv8_0) and (ap_phi_mux_empty_phi_fu_105_p6 = ap_const_lv1_1)))) then 
            ap_phi_mux_empty_7_phi_fu_194_p26 <= ap_const_lv8_1;
        elsif ((((grp_fu_244_p3 = ap_const_lv1_0) and (trunc_ln3_fu_368_p4 = ap_const_lv8_4) and (ap_phi_mux_empty_phi_fu_105_p6 = ap_const_lv1_0)) or ((grp_fu_244_p3 = ap_const_lv1_1) and (trunc_ln3_fu_368_p4 = ap_const_lv8_4) and (ap_phi_mux_empty_phi_fu_105_p6 = ap_const_lv1_0)) or ((grp_fu_262_p3 = ap_const_lv1_0) and (trunc_ln3_fu_368_p4 = ap_const_lv8_4) and (ap_phi_mux_empty_phi_fu_105_p6 = ap_const_lv1_1)) or ((grp_fu_262_p3 = ap_const_lv1_1) and (trunc_ln3_fu_368_p4 = ap_const_lv8_1) and (ap_phi_mux_empty_phi_fu_105_p6 = ap_const_lv1_1)))) then 
            ap_phi_mux_empty_7_phi_fu_194_p26 <= ap_const_lv8_4;
        elsif (((grp_fu_262_p3 = ap_const_lv1_1) and (trunc_ln3_fu_368_p4 = ap_const_lv8_4) and (ap_phi_mux_empty_phi_fu_105_p6 = ap_const_lv1_1))) then 
            ap_phi_mux_empty_7_phi_fu_194_p26 <= ap_const_lv8_D;
        elsif ((not((trunc_ln3_fu_368_p4 = ap_const_lv8_4)) and not((trunc_ln3_fu_368_p4 = ap_const_lv8_1)) and not((trunc_ln3_fu_368_p4 = ap_const_lv8_0)))) then 
            ap_phi_mux_empty_7_phi_fu_194_p26 <= ap_phi_mux_ctx_new_0_phi_fu_94_p6(39 downto 32);
        else 
            ap_phi_mux_empty_7_phi_fu_194_p26 <= "XXXXXXXX";
        end if; 
    end process;


    ap_phi_mux_empty_phi_fu_105_p6_assign_proc : process(tmp_1_fu_316_p3, tmp_3_fu_324_p3)
    begin
        if (((tmp_3_fu_324_p3 = ap_const_lv1_0) and (tmp_1_fu_316_p3 = ap_const_lv1_1))) then 
            ap_phi_mux_empty_phi_fu_105_p6 <= ap_const_lv1_1;
        elsif (((tmp_1_fu_316_p3 = ap_const_lv1_0) or ((tmp_3_fu_324_p3 = ap_const_lv1_1) and (tmp_1_fu_316_p3 = ap_const_lv1_1)))) then 
            ap_phi_mux_empty_phi_fu_105_p6 <= ap_const_lv1_0;
        else 
            ap_phi_mux_empty_phi_fu_105_p6 <= "X";
        end if; 
    end process;


    ap_phi_mux_finished_phi_fu_237_p4_assign_proc : process(xor_ln80_fu_535_p2, icmp_ln80_fu_529_p2)
    begin
        if ((icmp_ln80_fu_529_p2 = ap_const_lv1_0)) then 
            ap_phi_mux_finished_phi_fu_237_p4 <= ap_const_lv1_0;
        elsif ((icmp_ln80_fu_529_p2 = ap_const_lv1_1)) then 
            ap_phi_mux_finished_phi_fu_237_p4 <= xor_ln80_fu_535_p2;
        else 
            ap_phi_mux_finished_phi_fu_237_p4 <= "X";
        end if; 
    end process;

    ap_ready <= ap_start;
    ap_return <= ap_phi_mux_finished_phi_fu_237_p4;
    ctx_o <= std_logic_vector(IEEE.numeric_std.resize(unsigned(ap_phi_mux_ctx_new_1_phi_fu_119_p26),77));

    ctx_o_ap_vld_assign_proc : process(ap_start)
    begin
        if ((ap_start = ap_const_logic_1)) then 
            ctx_o_ap_vld <= ap_const_logic_1;
        else 
            ctx_o_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    grp_fu_244_p3 <= ap_phi_mux_ctx_new_0_phi_fu_94_p6(42 downto 42);
    grp_fu_252_p4 <= ap_phi_mux_ctx_new_0_phi_fu_94_p6(43 downto 41);
    grp_fu_262_p3 <= ap_phi_mux_ctx_new_0_phi_fu_94_p6(41 downto 41);
    grp_fu_270_p4 <= ap_phi_mux_ctx_new_0_phi_fu_94_p6(43 downto 42);
    grp_fu_280_p3 <= ap_phi_mux_ctx_new_0_phi_fu_94_p6(40 downto 40);
    icmp_ln27_fu_296_p2 <= "0" when (trunc_ln27_fu_292_p1 = layer_idx) else "1";
    icmp_ln80_fu_529_p2 <= "1" when (ap_phi_mux_empty_7_phi_fu_194_p26 = ap_const_lv8_D) else "0";
    or_ln1_fu_505_p6 <= ((((grp_fu_270_p4 & ap_const_lv1_0) & grp_fu_280_p3) & ap_const_lv8_1) & trunc_ln47_fu_501_p1);
    or_ln2_fu_480_p5 <= (((ap_const_lv1_1 & grp_fu_252_p4) & ap_const_lv1_1) & trunc_ln44_fu_476_p1);
    or_ln3_fu_457_p6 <= ((((grp_fu_270_p4 & ap_const_lv1_0) & grp_fu_280_p3) & ap_const_lv8_4) & trunc_ln59_fu_453_p1);
    or_ln4_fu_440_p5 <= (((ap_const_lv3_5 & grp_fu_252_p4) & ap_const_lv1_1) & trunc_ln56_fu_436_p1);
    or_ln5_fu_417_p6 <= ((((grp_fu_270_p4 & ap_const_lv1_0) & grp_fu_280_p3) & ap_const_lv8_D) & trunc_ln71_fu_413_p1);
    or_ln6_fu_396_p5 <= (((ap_const_lv1_1 & grp_fu_252_p4) & ap_const_lv1_1) & trunc_ln68_fu_392_p1);
    or_ln_fu_346_p4 <= ((tmp_fu_332_p4 & ap_const_lv2_2) & trunc_ln33_fu_342_p1);
    select_ln27_fu_306_p3 <= 
        zext_ln27_fu_302_p1 when (icmp_ln27_fu_296_p2(0) = '1') else 
        trunc_ln23_fu_288_p1;
        sext_ln45_fu_492_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(or_ln2_fu_480_p5),46));

        sext_ln69_fu_408_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(or_ln6_fu_396_p5),47));

    tmp_1_fu_316_p3 <= select_ln27_fu_306_p3(40 downto 40);
    tmp_3_fu_324_p3 <= select_ln27_fu_306_p3(43 downto 43);
    tmp_fu_332_p4 <= select_ln27_fu_306_p3(43 downto 42);
    trunc_ln23_fu_288_p1 <= ctx_i(44 - 1 downto 0);
    trunc_ln27_fu_292_p1 <= ctx_i(32 - 1 downto 0);
    trunc_ln33_fu_342_p1 <= select_ln27_fu_306_p3(40 - 1 downto 0);
    trunc_ln3_fu_368_p4 <= ap_phi_mux_ctx_new_0_phi_fu_94_p6(39 downto 32);
    trunc_ln44_fu_476_p1 <= ap_phi_mux_ctx_new_0_phi_fu_94_p6(40 - 1 downto 0);
    trunc_ln47_fu_501_p1 <= ap_phi_mux_ctx_new_0_phi_fu_94_p6(32 - 1 downto 0);
    trunc_ln56_fu_436_p1 <= ap_phi_mux_ctx_new_0_phi_fu_94_p6(40 - 1 downto 0);
    trunc_ln59_fu_453_p1 <= ap_phi_mux_ctx_new_0_phi_fu_94_p6(32 - 1 downto 0);
    trunc_ln68_fu_392_p1 <= ap_phi_mux_ctx_new_0_phi_fu_94_p6(40 - 1 downto 0);
    trunc_ln71_fu_413_p1 <= ap_phi_mux_ctx_new_0_phi_fu_94_p6(32 - 1 downto 0);
    xor_ln80_fu_535_p2 <= (ap_phi_mux_empty_6_phi_fu_150_p26 xor ap_const_lv1_1);
    zext_ln27_fu_302_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(layer_idx),44));
    zext_ln38_fu_357_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(ap_phi_mux_ctx_new_0_phi_fu_94_p6),47));
    zext_ln45_fu_496_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(sext_ln45_fu_492_p1),47));
    zext_ln49_fu_519_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(or_ln1_fu_505_p6),47));
    zext_ln61_fu_471_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(or_ln3_fu_457_p6),47));
    zext_ln73_fu_431_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(or_ln5_fu_417_p6),47));
end behav;
