-- ==============================================================
-- Generated by Vitis HLS v2025.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity drive_group_head_phase is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    head_ctx_ref_0_i : IN STD_LOGIC_VECTOR (65 downto 0);
    head_ctx_ref_0_o : OUT STD_LOGIC_VECTOR (65 downto 0);
    head_ctx_ref_0_o_ap_vld : OUT STD_LOGIC;
    head_ctx_ref_1_i : IN STD_LOGIC_VECTOR (65 downto 0);
    head_ctx_ref_1_o : OUT STD_LOGIC_VECTOR (65 downto 0);
    head_ctx_ref_1_o_ap_vld : OUT STD_LOGIC;
    base_head_idx : IN STD_LOGIC_VECTOR (31 downto 0);
    layer_idx : IN STD_LOGIC_VECTOR (31 downto 0);
    start_r : IN STD_LOGIC_VECTOR (0 downto 0);
    ap_return : OUT STD_LOGIC_VECTOR (0 downto 0) );
end;


architecture behav of drive_group_head_phase is 
    attribute CORE_GENERATION_INFO : STRING;
    attribute CORE_GENERATION_INFO of behav : architecture is
    "drive_group_head_phase_drive_group_head_phase,hls_ip_2025_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xck26-sfvc784-2LV-c,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=7.041650,HLS_SYN_LAT=4,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=176,HLS_SYN_LUT=982,HLS_VERSION=2025_1}";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (4 downto 0) := "00001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (4 downto 0) := "00010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (4 downto 0) := "00100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (4 downto 0) := "01000";
    constant ap_ST_fsm_state5 : STD_LOGIC_VECTOR (4 downto 0) := "10000";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv32_20 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000100000";
    constant ap_const_lv32_27 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000100111";
    constant ap_const_lv8_E : STD_LOGIC_VECTOR (7 downto 0) := "00001110";
    constant ap_const_lv8_0 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    constant ap_const_lv32_34 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000110100";
    constant ap_const_lv32_41 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001000001";

    signal ap_CS_fsm : STD_LOGIC_VECTOR (4 downto 0) := "00001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal start_r_read_reg_244 : STD_LOGIC_VECTOR (0 downto 0);
    signal layer_idx_read_reg_249 : STD_LOGIC_VECTOR (31 downto 0);
    signal icmp_ln205_fu_141_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln205_reg_254 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln206_fu_153_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln206_reg_258 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_reg_264 : STD_LOGIC_VECTOR (13 downto 0);
    signal trunc_ln206_fu_169_p1 : STD_LOGIC_VECTOR (50 downto 0);
    signal trunc_ln206_reg_269 : STD_LOGIC_VECTOR (50 downto 0);
    signal head_done_2_reg_274 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal icmp_ln205_1_fu_195_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln205_1_reg_279 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal and_ln206_1_fu_207_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln206_1_reg_283 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_s_reg_289 : STD_LOGIC_VECTOR (13 downto 0);
    signal trunc_ln206_1_fu_222_p1 : STD_LOGIC_VECTOR (50 downto 0);
    signal trunc_ln206_1_reg_294 : STD_LOGIC_VECTOR (50 downto 0);
    signal grp_run_single_head_fu_118_ap_return_0 : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_run_single_head_fu_118_ap_return_1 : STD_LOGIC_VECTOR (65 downto 0);
    signal call_ret_reg_299_0 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_state4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";
    signal grp_run_single_head_fu_118_ap_ready : STD_LOGIC;
    signal grp_run_single_head_fu_118_p_read : STD_LOGIC_VECTOR (65 downto 0);
    signal grp_run_single_head_fu_118_start_r : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_phi_mux_group_finished_1_phi_fu_100_p4 : STD_LOGIC_VECTOR (0 downto 0);
    signal group_finished_1_reg_96 : STD_LOGIC_VECTOR (0 downto 0);
    signal group_finished_2_fu_237_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_phi_mux_group_finished_3_phi_fu_111_p4 : STD_LOGIC_VECTOR (0 downto 0);
    signal group_finished_3_reg_108 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_state5 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state5 : signal is "none";
    signal or_ln_fu_173_p4 : STD_LOGIC_VECTOR (65 downto 0);
    signal or_ln206_1_fu_226_p4 : STD_LOGIC_VECTOR (65 downto 0);
    signal trunc_ln_fu_131_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal icmp_ln206_fu_147_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln205_1_fu_185_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal icmp_ln206_1_fu_201_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (4 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_ST_fsm_state3_blk : STD_LOGIC;
    signal ap_ST_fsm_state4_blk : STD_LOGIC;
    signal ap_ST_fsm_state5_blk : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component drive_group_head_phase_run_single_head IS
    port (
        ap_ready : OUT STD_LOGIC;
        p_read : IN STD_LOGIC_VECTOR (65 downto 0);
        layer_idx : IN STD_LOGIC_VECTOR (31 downto 0);
        start_r : IN STD_LOGIC_VECTOR (0 downto 0);
        ap_return_0 : OUT STD_LOGIC_VECTOR (0 downto 0);
        ap_return_1 : OUT STD_LOGIC_VECTOR (65 downto 0);
        ap_rst : IN STD_LOGIC );
    end component;



begin
    grp_run_single_head_fu_118 : component drive_group_head_phase_run_single_head
    port map (
        ap_ready => grp_run_single_head_fu_118_ap_ready,
        p_read => grp_run_single_head_fu_118_p_read,
        layer_idx => layer_idx_read_reg_249,
        start_r => grp_run_single_head_fu_118_start_r,
        ap_return_0 => grp_run_single_head_fu_118_ap_return_0,
        ap_return_1 => grp_run_single_head_fu_118_ap_return_1,
        ap_rst => ap_rst);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    group_finished_1_reg_96_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln205_fu_141_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then 
                group_finished_1_reg_96 <= ap_const_lv1_1;
            elsif (((icmp_ln205_reg_254 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
                group_finished_1_reg_96 <= head_done_2_reg_274;
            end if; 
        end if;
    end process;

    group_finished_3_reg_108_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln205_1_fu_195_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
                group_finished_3_reg_108 <= ap_phi_mux_group_finished_1_phi_fu_100_p4;
            elsif (((icmp_ln205_1_reg_279 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state5))) then 
                group_finished_3_reg_108 <= group_finished_2_fu_237_p2;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state3)) then
                and_ln206_1_reg_283 <= and_ln206_1_fu_207_p2;
                icmp_ln205_1_reg_279 <= icmp_ln205_1_fu_195_p2;
                tmp_s_reg_289 <= head_ctx_ref_1_i(65 downto 52);
                trunc_ln206_1_reg_294 <= trunc_ln206_1_fu_222_p1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state1)) then
                and_ln206_reg_258 <= and_ln206_fu_153_p2;
                icmp_ln205_reg_254 <= icmp_ln205_fu_141_p2;
                layer_idx_read_reg_249 <= layer_idx;
                start_r_read_reg_244 <= start_r;
                tmp_reg_264 <= head_ctx_ref_0_i(65 downto 52);
                trunc_ln206_reg_269 <= trunc_ln206_fu_169_p1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state4)) then
                call_ret_reg_299_0 <= grp_run_single_head_fu_118_ap_return_0;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state2)) then
                head_done_2_reg_274 <= grp_run_single_head_fu_118_ap_return_0;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_start, ap_CS_fsm, ap_CS_fsm_state1, icmp_ln205_fu_141_p2, icmp_ln205_1_fu_195_p2, ap_CS_fsm_state3)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((icmp_ln205_fu_141_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state3;
                elsif (((icmp_ln205_fu_141_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                ap_NS_fsm <= ap_ST_fsm_state3;
            when ap_ST_fsm_state3 => 
                if (((icmp_ln205_1_fu_195_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then
                    ap_NS_fsm <= ap_ST_fsm_state5;
                else
                    ap_NS_fsm <= ap_ST_fsm_state4;
                end if;
            when ap_ST_fsm_state4 => 
                ap_NS_fsm <= ap_ST_fsm_state5;
            when ap_ST_fsm_state5 => 
                ap_NS_fsm <= ap_ST_fsm_state1;
            when others =>  
                ap_NS_fsm <= "XXXXX";
        end case;
    end process;
    and_ln206_1_fu_207_p2 <= (start_r_read_reg_244 and icmp_ln206_1_fu_201_p2);
    and_ln206_fu_153_p2 <= (start_r and icmp_ln206_fu_147_p2);
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);
    ap_CS_fsm_state4 <= ap_CS_fsm(3);
    ap_CS_fsm_state5 <= ap_CS_fsm(4);

    ap_ST_fsm_state1_blk_assign_proc : process(ap_start)
    begin
        if ((ap_start = ap_const_logic_0)) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state2_blk <= ap_const_logic_0;
    ap_ST_fsm_state3_blk <= ap_const_logic_0;
    ap_ST_fsm_state4_blk <= ap_const_logic_0;
    ap_ST_fsm_state5_blk <= ap_const_logic_0;

    ap_done_assign_proc : process(ap_CS_fsm_state5)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_phi_mux_group_finished_1_phi_fu_100_p4_assign_proc : process(icmp_ln205_reg_254, head_done_2_reg_274, ap_CS_fsm_state3, group_finished_1_reg_96)
    begin
        if (((icmp_ln205_reg_254 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
            ap_phi_mux_group_finished_1_phi_fu_100_p4 <= head_done_2_reg_274;
        else 
            ap_phi_mux_group_finished_1_phi_fu_100_p4 <= group_finished_1_reg_96;
        end if; 
    end process;


    ap_phi_mux_group_finished_3_phi_fu_111_p4_assign_proc : process(icmp_ln205_1_reg_279, group_finished_2_fu_237_p2, group_finished_3_reg_108, ap_CS_fsm_state5)
    begin
        if (((icmp_ln205_1_reg_279 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state5))) then 
            ap_phi_mux_group_finished_3_phi_fu_111_p4 <= group_finished_2_fu_237_p2;
        else 
            ap_phi_mux_group_finished_3_phi_fu_111_p4 <= group_finished_3_reg_108;
        end if; 
    end process;


    ap_ready_assign_proc : process(ap_CS_fsm_state5)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;

    ap_return <= ap_phi_mux_group_finished_3_phi_fu_111_p4;
    group_finished_2_fu_237_p2 <= (group_finished_1_reg_96 and call_ret_reg_299_0);

    grp_run_single_head_fu_118_p_read_assign_proc : process(ap_CS_fsm_state2, ap_CS_fsm_state4, or_ln_fu_173_p4, or_ln206_1_fu_226_p4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            grp_run_single_head_fu_118_p_read <= or_ln206_1_fu_226_p4;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            grp_run_single_head_fu_118_p_read <= or_ln_fu_173_p4;
        else 
            grp_run_single_head_fu_118_p_read <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    grp_run_single_head_fu_118_start_r_assign_proc : process(and_ln206_reg_258, ap_CS_fsm_state2, and_ln206_1_reg_283, ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            grp_run_single_head_fu_118_start_r <= and_ln206_1_reg_283;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            grp_run_single_head_fu_118_start_r <= and_ln206_reg_258;
        else 
            grp_run_single_head_fu_118_start_r <= "X";
        end if; 
    end process;


    head_ctx_ref_0_o_assign_proc : process(head_ctx_ref_0_i, ap_CS_fsm_state2, grp_run_single_head_fu_118_ap_return_1)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            head_ctx_ref_0_o <= grp_run_single_head_fu_118_ap_return_1;
        else 
            head_ctx_ref_0_o <= head_ctx_ref_0_i;
        end if; 
    end process;


    head_ctx_ref_0_o_ap_vld_assign_proc : process(ap_CS_fsm_state2)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            head_ctx_ref_0_o_ap_vld <= ap_const_logic_1;
        else 
            head_ctx_ref_0_o_ap_vld <= ap_const_logic_0;
        end if; 
    end process;


    head_ctx_ref_1_o_assign_proc : process(head_ctx_ref_1_i, grp_run_single_head_fu_118_ap_return_1, ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            head_ctx_ref_1_o <= grp_run_single_head_fu_118_ap_return_1;
        else 
            head_ctx_ref_1_o <= head_ctx_ref_1_i;
        end if; 
    end process;


    head_ctx_ref_1_o_ap_vld_assign_proc : process(ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            head_ctx_ref_1_o_ap_vld <= ap_const_logic_1;
        else 
            head_ctx_ref_1_o_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    icmp_ln205_1_fu_195_p2 <= "1" when (trunc_ln205_1_fu_185_p4 = ap_const_lv8_E) else "0";
    icmp_ln205_fu_141_p2 <= "1" when (trunc_ln_fu_131_p4 = ap_const_lv8_E) else "0";
    icmp_ln206_1_fu_201_p2 <= "1" when (trunc_ln205_1_fu_185_p4 = ap_const_lv8_0) else "0";
    icmp_ln206_fu_147_p2 <= "1" when (trunc_ln_fu_131_p4 = ap_const_lv8_0) else "0";
    or_ln206_1_fu_226_p4 <= ((tmp_s_reg_289 & and_ln206_1_reg_283) & trunc_ln206_1_reg_294);
    or_ln_fu_173_p4 <= ((tmp_reg_264 & and_ln206_reg_258) & trunc_ln206_reg_269);
    trunc_ln205_1_fu_185_p4 <= head_ctx_ref_1_i(39 downto 32);
    trunc_ln206_1_fu_222_p1 <= head_ctx_ref_1_i(51 - 1 downto 0);
    trunc_ln206_fu_169_p1 <= head_ctx_ref_0_i(51 - 1 downto 0);
    trunc_ln_fu_131_p4 <= head_ctx_ref_0_i(39 downto 32);
end behav;
