

set RtlHierarchyInfo {[
	{"ID" : "0", "Level" : "0", "Path" : "`AUTOTB_DUT_INST", "Parent" : "",
		"CDFG" : "scheduler_hls",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "1",
		"VariableLatency" : "0", "ExactLatency" : "0", "EstimateLatencyMin" : "0", "EstimateLatencyMax" : "0",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "cntrl_start", "Type" : "None", "Direction" : "I"},
			{"Name" : "cntrl_reset_n", "Type" : "None", "Direction" : "I"},
			{"Name" : "cntrl_layer_idx", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "cntrl_busy", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "cntrl_start_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "axis_in_valid", "Type" : "None", "Direction" : "I"},
			{"Name" : "axis_in_last", "Type" : "None", "Direction" : "I"},
			{"Name" : "axis_in_ready", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "wl_ready", "Type" : "None", "Direction" : "I"},
			{"Name" : "wl_start", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "wl_addr_sel", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "wl_layer", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "wl_head", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "wl_tile", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "dma_done", "Type" : "None", "Direction" : "I"},
			{"Name" : "compute_ready", "Type" : "None", "Direction" : "I"},
			{"Name" : "compute_done", "Type" : "None", "Direction" : "I"},
			{"Name" : "requant_ready", "Type" : "None", "Direction" : "I"},
			{"Name" : "requant_done", "Type" : "None", "Direction" : "I"},
			{"Name" : "compute_start", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "compute_op", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "requant_start", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "requant_op", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "stream_ready", "Type" : "None", "Direction" : "I"},
			{"Name" : "stream_start", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "stream_done", "Type" : "None", "Direction" : "I"},
			{"Name" : "done", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "STATE", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "ffn_started", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "st", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "layer_idx", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "attn_started", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "concat_started", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "outproj_started", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "wo_tile", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "wo_dma_busy", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "wo_comp_busy", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "resid0_started", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "ln0_started", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "ffn_stage", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "resid1_started", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "ln1_started", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "stream_started", "Type" : "OVld", "Direction" : "IO"}]}]}
