

set RtlHierarchyInfo {[
	{"ID" : "0", "Level" : "0", "Path" : "`AUTOTB_DUT_INST", "Parent" : "", "Child" : ["1"],
		"CDFG" : "scheduler_hls",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "1", "EstimateLatencyMax" : "1",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "cntrl_start", "Type" : "None", "Direction" : "I"},
			{"Name" : "cntrl_reset_n", "Type" : "None", "Direction" : "I"},
			{"Name" : "cntrl_layer_idx", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "cntrl_busy", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "cntrl_start_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "axis_in_valid", "Type" : "None", "Direction" : "I"},
			{"Name" : "axis_in_last", "Type" : "None", "Direction" : "I"},
			{"Name" : "axis_in_ready", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "wl_ready", "Type" : "None", "Direction" : "I"},
			{"Name" : "wl_start", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "wl_addr_sel", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "wl_layer", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "wl_head", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "wl_tile", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "dma_done", "Type" : "None", "Direction" : "I"},
			{"Name" : "compute_ready", "Type" : "None", "Direction" : "I"},
			{"Name" : "compute_done", "Type" : "None", "Direction" : "I"},
			{"Name" : "requant_ready", "Type" : "None", "Direction" : "I"},
			{"Name" : "requant_done", "Type" : "None", "Direction" : "I"},
			{"Name" : "head_ctx_ref_0", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "head_ctx_ref_1", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "head_ctx_ref_2", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "head_ctx_ref_3", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "compute_start", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "compute_op", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "requant_start", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "requant_op", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "stream_ready", "Type" : "None", "Direction" : "I"},
			{"Name" : "stream_start", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "stream_done", "Type" : "None", "Direction" : "I"},
			{"Name" : "done", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "debug_compute_done", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "STATE", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "attn_started", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "attn_compute_done", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "group_idx", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "start_head_group", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "concat_compute_done", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "concat_started", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "outproj_started", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "outproj_compute_done", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "resid0_started", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "resid0_compute_done", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "ln0_started", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "ln0_compute_done", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "ffn_w1_compute_done", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "ffn_act_compute_done", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "ffn_w2_compute_done", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "ffn_stage", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "ffn_started", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "resid1_started", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "resid1_compute_done", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "ln1_started", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "ln1_compute_done", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "st", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "layer_idx", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "stream_started", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "wo_tile", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "wo_dma_busy", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "wo_comp_busy", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "w1_tile", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "w1_dma_busy", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "w1_comp_busy", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "w2_tile", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "w2_dma_busy", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "w2_comp_busy", "Type" : "OVld", "Direction" : "IO"}]},
	{"ID" : "1", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.call_ret_drive_group_head_phase_fu_7665", "Parent" : "0", "Child" : ["2", "3", "4", "5"],
		"CDFG" : "drive_group_head_phase",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "0", "ap_start" : "0", "ap_ready" : "1", "ap_done" : "0", "ap_continue" : "0", "ap_idle" : "0", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "1",
		"VariableLatency" : "0", "ExactLatency" : "0", "EstimateLatencyMin" : "0", "EstimateLatencyMax" : "0",
		"Combinational" : "1",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "p_read", "Type" : "None", "Direction" : "I"},
			{"Name" : "p_read1", "Type" : "None", "Direction" : "I"},
			{"Name" : "p_read2", "Type" : "None", "Direction" : "I"},
			{"Name" : "p_read3", "Type" : "None", "Direction" : "I"},
			{"Name" : "head_ctx_ref_phase_read", "Type" : "None", "Direction" : "I"},
			{"Name" : "head_ctx_ref_phase_read_7", "Type" : "None", "Direction" : "I"},
			{"Name" : "head_ctx_ref_phase_read_8", "Type" : "None", "Direction" : "I"},
			{"Name" : "head_ctx_ref_phase_read_9", "Type" : "None", "Direction" : "I"},
			{"Name" : "p_read8", "Type" : "None", "Direction" : "I"},
			{"Name" : "p_read9", "Type" : "None", "Direction" : "I"},
			{"Name" : "p_read10", "Type" : "None", "Direction" : "I"},
			{"Name" : "p_read11", "Type" : "None", "Direction" : "I"},
			{"Name" : "p_read12", "Type" : "None", "Direction" : "I"},
			{"Name" : "p_read13", "Type" : "None", "Direction" : "I"},
			{"Name" : "p_read14", "Type" : "None", "Direction" : "I"},
			{"Name" : "p_read15", "Type" : "None", "Direction" : "I"},
			{"Name" : "p_read16", "Type" : "None", "Direction" : "I"},
			{"Name" : "p_read17", "Type" : "None", "Direction" : "I"},
			{"Name" : "p_read18", "Type" : "None", "Direction" : "I"},
			{"Name" : "p_read19", "Type" : "None", "Direction" : "I"},
			{"Name" : "head_ctx_ref_compute_op_read", "Type" : "None", "Direction" : "I"},
			{"Name" : "head_ctx_ref_compute_op_read_11", "Type" : "None", "Direction" : "I"},
			{"Name" : "head_ctx_ref_compute_op_read_12", "Type" : "None", "Direction" : "I"},
			{"Name" : "head_ctx_ref_compute_op_read_13", "Type" : "None", "Direction" : "I"},
			{"Name" : "p_read24", "Type" : "None", "Direction" : "I"},
			{"Name" : "p_read25", "Type" : "None", "Direction" : "I"},
			{"Name" : "p_read26", "Type" : "None", "Direction" : "I"},
			{"Name" : "p_read27", "Type" : "None", "Direction" : "I"},
			{"Name" : "p_read28", "Type" : "None", "Direction" : "I"},
			{"Name" : "p_read29", "Type" : "None", "Direction" : "I"},
			{"Name" : "p_read30", "Type" : "None", "Direction" : "I"},
			{"Name" : "p_read31", "Type" : "None", "Direction" : "I"},
			{"Name" : "p_read32", "Type" : "None", "Direction" : "I"},
			{"Name" : "p_read33", "Type" : "None", "Direction" : "I"},
			{"Name" : "p_read34", "Type" : "None", "Direction" : "I"},
			{"Name" : "p_read35", "Type" : "None", "Direction" : "I"},
			{"Name" : "p_read36", "Type" : "None", "Direction" : "I"},
			{"Name" : "p_read37", "Type" : "None", "Direction" : "I"},
			{"Name" : "p_read38", "Type" : "None", "Direction" : "I"},
			{"Name" : "p_read39", "Type" : "None", "Direction" : "I"},
			{"Name" : "p_read40", "Type" : "None", "Direction" : "I"},
			{"Name" : "p_read41", "Type" : "None", "Direction" : "I"},
			{"Name" : "p_read42", "Type" : "None", "Direction" : "I"},
			{"Name" : "p_read43", "Type" : "None", "Direction" : "I"},
			{"Name" : "p_read44", "Type" : "None", "Direction" : "I"},
			{"Name" : "p_read45", "Type" : "None", "Direction" : "I"},
			{"Name" : "p_read46", "Type" : "None", "Direction" : "I"},
			{"Name" : "p_read47", "Type" : "None", "Direction" : "I"},
			{"Name" : "p_read48", "Type" : "None", "Direction" : "I"},
			{"Name" : "p_read49", "Type" : "None", "Direction" : "I"},
			{"Name" : "p_read50", "Type" : "None", "Direction" : "I"},
			{"Name" : "p_read51", "Type" : "None", "Direction" : "I"},
			{"Name" : "p_read52", "Type" : "None", "Direction" : "I"},
			{"Name" : "p_read53", "Type" : "None", "Direction" : "I"},
			{"Name" : "p_read54", "Type" : "None", "Direction" : "I"},
			{"Name" : "p_read55", "Type" : "None", "Direction" : "I"},
			{"Name" : "p_read56", "Type" : "None", "Direction" : "I"},
			{"Name" : "p_read57", "Type" : "None", "Direction" : "I"},
			{"Name" : "p_read58", "Type" : "None", "Direction" : "I"},
			{"Name" : "p_read59", "Type" : "None", "Direction" : "I"},
			{"Name" : "p_read60", "Type" : "None", "Direction" : "I"},
			{"Name" : "p_read61", "Type" : "None", "Direction" : "I"},
			{"Name" : "p_read62", "Type" : "None", "Direction" : "I"},
			{"Name" : "p_read63", "Type" : "None", "Direction" : "I"},
			{"Name" : "p_read64", "Type" : "None", "Direction" : "I"},
			{"Name" : "p_read65", "Type" : "None", "Direction" : "I"},
			{"Name" : "p_read66", "Type" : "None", "Direction" : "I"},
			{"Name" : "p_read67", "Type" : "None", "Direction" : "I"},
			{"Name" : "p_read68", "Type" : "None", "Direction" : "I"},
			{"Name" : "p_read69", "Type" : "None", "Direction" : "I"},
			{"Name" : "p_read70", "Type" : "None", "Direction" : "I"},
			{"Name" : "p_read71", "Type" : "None", "Direction" : "I"},
			{"Name" : "p_read72", "Type" : "None", "Direction" : "I"},
			{"Name" : "p_read73", "Type" : "None", "Direction" : "I"},
			{"Name" : "p_read74", "Type" : "None", "Direction" : "I"},
			{"Name" : "p_read75", "Type" : "None", "Direction" : "I"},
			{"Name" : "p_read76", "Type" : "None", "Direction" : "I"},
			{"Name" : "p_read77", "Type" : "None", "Direction" : "I"},
			{"Name" : "p_read78", "Type" : "None", "Direction" : "I"},
			{"Name" : "p_read79", "Type" : "None", "Direction" : "I"},
			{"Name" : "p_read80", "Type" : "None", "Direction" : "I"},
			{"Name" : "p_read81", "Type" : "None", "Direction" : "I"},
			{"Name" : "p_read82", "Type" : "None", "Direction" : "I"},
			{"Name" : "p_read83", "Type" : "None", "Direction" : "I"},
			{"Name" : "layer_idx", "Type" : "None", "Direction" : "I"},
			{"Name" : "start_r", "Type" : "None", "Direction" : "I"}]},
	{"ID" : "2", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.call_ret_drive_group_head_phase_fu_7665.call_ret1_run_single_head_fu_1576", "Parent" : "1",
		"CDFG" : "run_single_head",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "0", "ap_start" : "0", "ap_ready" : "1", "ap_done" : "0", "ap_continue" : "0", "ap_idle" : "0", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "1",
		"VariableLatency" : "0", "ExactLatency" : "0", "EstimateLatencyMin" : "0", "EstimateLatencyMax" : "0",
		"Combinational" : "1",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "ctx_layer_stamp_read_5", "Type" : "None", "Direction" : "I"},
			{"Name" : "ctx_layer_stamp_read", "Type" : "None", "Direction" : "I"},
			{"Name" : "ctx_phase_read", "Type" : "None", "Direction" : "I"},
			{"Name" : "ctx_compute_ready_read", "Type" : "None", "Direction" : "I"},
			{"Name" : "ctx_compute_done_read", "Type" : "None", "Direction" : "I"},
			{"Name" : "ctx_compute_op_read", "Type" : "None", "Direction" : "I"},
			{"Name" : "ctx_start_head_read", "Type" : "None", "Direction" : "I"},
			{"Name" : "ctx_q_started_read", "Type" : "None", "Direction" : "I"},
			{"Name" : "ctx_k_started_read", "Type" : "None", "Direction" : "I"},
			{"Name" : "ctx_v_started_read", "Type" : "None", "Direction" : "I"},
			{"Name" : "ctx_att_scores_started_read", "Type" : "None", "Direction" : "I"},
			{"Name" : "ctx_val_scale_started_read", "Type" : "None", "Direction" : "I"},
			{"Name" : "ctx_softmax_started_read", "Type" : "None", "Direction" : "I"},
			{"Name" : "ctx_att_value_started_read", "Type" : "None", "Direction" : "I"},
			{"Name" : "ctx_q_compute_done_read", "Type" : "None", "Direction" : "I"},
			{"Name" : "ctx_k_compute_done_read", "Type" : "None", "Direction" : "I"},
			{"Name" : "ctx_v_compute_done_read", "Type" : "None", "Direction" : "I"},
			{"Name" : "ctx_att_scores_compute_done_read", "Type" : "None", "Direction" : "I"},
			{"Name" : "ctx_val_scale_compute_done_read", "Type" : "None", "Direction" : "I"},
			{"Name" : "ctx_softmax_compute_done_read", "Type" : "None", "Direction" : "I"},
			{"Name" : "ctx_att_value_compute_done_read", "Type" : "None", "Direction" : "I"},
			{"Name" : "layer_idx", "Type" : "None", "Direction" : "I"},
			{"Name" : "start_r", "Type" : "None", "Direction" : "I"}]},
	{"ID" : "3", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.call_ret_drive_group_head_phase_fu_7665.call_ret2_run_single_head_fu_1624", "Parent" : "1",
		"CDFG" : "run_single_head",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "0", "ap_start" : "0", "ap_ready" : "1", "ap_done" : "0", "ap_continue" : "0", "ap_idle" : "0", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "1",
		"VariableLatency" : "0", "ExactLatency" : "0", "EstimateLatencyMin" : "0", "EstimateLatencyMax" : "0",
		"Combinational" : "1",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "ctx_layer_stamp_read_5", "Type" : "None", "Direction" : "I"},
			{"Name" : "ctx_layer_stamp_read", "Type" : "None", "Direction" : "I"},
			{"Name" : "ctx_phase_read", "Type" : "None", "Direction" : "I"},
			{"Name" : "ctx_compute_ready_read", "Type" : "None", "Direction" : "I"},
			{"Name" : "ctx_compute_done_read", "Type" : "None", "Direction" : "I"},
			{"Name" : "ctx_compute_op_read", "Type" : "None", "Direction" : "I"},
			{"Name" : "ctx_start_head_read", "Type" : "None", "Direction" : "I"},
			{"Name" : "ctx_q_started_read", "Type" : "None", "Direction" : "I"},
			{"Name" : "ctx_k_started_read", "Type" : "None", "Direction" : "I"},
			{"Name" : "ctx_v_started_read", "Type" : "None", "Direction" : "I"},
			{"Name" : "ctx_att_scores_started_read", "Type" : "None", "Direction" : "I"},
			{"Name" : "ctx_val_scale_started_read", "Type" : "None", "Direction" : "I"},
			{"Name" : "ctx_softmax_started_read", "Type" : "None", "Direction" : "I"},
			{"Name" : "ctx_att_value_started_read", "Type" : "None", "Direction" : "I"},
			{"Name" : "ctx_q_compute_done_read", "Type" : "None", "Direction" : "I"},
			{"Name" : "ctx_k_compute_done_read", "Type" : "None", "Direction" : "I"},
			{"Name" : "ctx_v_compute_done_read", "Type" : "None", "Direction" : "I"},
			{"Name" : "ctx_att_scores_compute_done_read", "Type" : "None", "Direction" : "I"},
			{"Name" : "ctx_val_scale_compute_done_read", "Type" : "None", "Direction" : "I"},
			{"Name" : "ctx_softmax_compute_done_read", "Type" : "None", "Direction" : "I"},
			{"Name" : "ctx_att_value_compute_done_read", "Type" : "None", "Direction" : "I"},
			{"Name" : "layer_idx", "Type" : "None", "Direction" : "I"},
			{"Name" : "start_r", "Type" : "None", "Direction" : "I"}]},
	{"ID" : "4", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.call_ret_drive_group_head_phase_fu_7665.call_ret3_run_single_head_fu_1672", "Parent" : "1",
		"CDFG" : "run_single_head",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "0", "ap_start" : "0", "ap_ready" : "1", "ap_done" : "0", "ap_continue" : "0", "ap_idle" : "0", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "1",
		"VariableLatency" : "0", "ExactLatency" : "0", "EstimateLatencyMin" : "0", "EstimateLatencyMax" : "0",
		"Combinational" : "1",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "ctx_layer_stamp_read_5", "Type" : "None", "Direction" : "I"},
			{"Name" : "ctx_layer_stamp_read", "Type" : "None", "Direction" : "I"},
			{"Name" : "ctx_phase_read", "Type" : "None", "Direction" : "I"},
			{"Name" : "ctx_compute_ready_read", "Type" : "None", "Direction" : "I"},
			{"Name" : "ctx_compute_done_read", "Type" : "None", "Direction" : "I"},
			{"Name" : "ctx_compute_op_read", "Type" : "None", "Direction" : "I"},
			{"Name" : "ctx_start_head_read", "Type" : "None", "Direction" : "I"},
			{"Name" : "ctx_q_started_read", "Type" : "None", "Direction" : "I"},
			{"Name" : "ctx_k_started_read", "Type" : "None", "Direction" : "I"},
			{"Name" : "ctx_v_started_read", "Type" : "None", "Direction" : "I"},
			{"Name" : "ctx_att_scores_started_read", "Type" : "None", "Direction" : "I"},
			{"Name" : "ctx_val_scale_started_read", "Type" : "None", "Direction" : "I"},
			{"Name" : "ctx_softmax_started_read", "Type" : "None", "Direction" : "I"},
			{"Name" : "ctx_att_value_started_read", "Type" : "None", "Direction" : "I"},
			{"Name" : "ctx_q_compute_done_read", "Type" : "None", "Direction" : "I"},
			{"Name" : "ctx_k_compute_done_read", "Type" : "None", "Direction" : "I"},
			{"Name" : "ctx_v_compute_done_read", "Type" : "None", "Direction" : "I"},
			{"Name" : "ctx_att_scores_compute_done_read", "Type" : "None", "Direction" : "I"},
			{"Name" : "ctx_val_scale_compute_done_read", "Type" : "None", "Direction" : "I"},
			{"Name" : "ctx_softmax_compute_done_read", "Type" : "None", "Direction" : "I"},
			{"Name" : "ctx_att_value_compute_done_read", "Type" : "None", "Direction" : "I"},
			{"Name" : "layer_idx", "Type" : "None", "Direction" : "I"},
			{"Name" : "start_r", "Type" : "None", "Direction" : "I"}]},
	{"ID" : "5", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.call_ret_drive_group_head_phase_fu_7665.call_ret_run_single_head_fu_1720", "Parent" : "1",
		"CDFG" : "run_single_head",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "0", "ap_start" : "0", "ap_ready" : "1", "ap_done" : "0", "ap_continue" : "0", "ap_idle" : "0", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "1",
		"VariableLatency" : "0", "ExactLatency" : "0", "EstimateLatencyMin" : "0", "EstimateLatencyMax" : "0",
		"Combinational" : "1",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "ctx_layer_stamp_read_5", "Type" : "None", "Direction" : "I"},
			{"Name" : "ctx_layer_stamp_read", "Type" : "None", "Direction" : "I"},
			{"Name" : "ctx_phase_read", "Type" : "None", "Direction" : "I"},
			{"Name" : "ctx_compute_ready_read", "Type" : "None", "Direction" : "I"},
			{"Name" : "ctx_compute_done_read", "Type" : "None", "Direction" : "I"},
			{"Name" : "ctx_compute_op_read", "Type" : "None", "Direction" : "I"},
			{"Name" : "ctx_start_head_read", "Type" : "None", "Direction" : "I"},
			{"Name" : "ctx_q_started_read", "Type" : "None", "Direction" : "I"},
			{"Name" : "ctx_k_started_read", "Type" : "None", "Direction" : "I"},
			{"Name" : "ctx_v_started_read", "Type" : "None", "Direction" : "I"},
			{"Name" : "ctx_att_scores_started_read", "Type" : "None", "Direction" : "I"},
			{"Name" : "ctx_val_scale_started_read", "Type" : "None", "Direction" : "I"},
			{"Name" : "ctx_softmax_started_read", "Type" : "None", "Direction" : "I"},
			{"Name" : "ctx_att_value_started_read", "Type" : "None", "Direction" : "I"},
			{"Name" : "ctx_q_compute_done_read", "Type" : "None", "Direction" : "I"},
			{"Name" : "ctx_k_compute_done_read", "Type" : "None", "Direction" : "I"},
			{"Name" : "ctx_v_compute_done_read", "Type" : "None", "Direction" : "I"},
			{"Name" : "ctx_att_scores_compute_done_read", "Type" : "None", "Direction" : "I"},
			{"Name" : "ctx_val_scale_compute_done_read", "Type" : "None", "Direction" : "I"},
			{"Name" : "ctx_softmax_compute_done_read", "Type" : "None", "Direction" : "I"},
			{"Name" : "ctx_att_value_compute_done_read", "Type" : "None", "Direction" : "I"},
			{"Name" : "layer_idx", "Type" : "None", "Direction" : "I"},
			{"Name" : "start_r", "Type" : "None", "Direction" : "I"}]}]}
