

set RtlHierarchyInfo {[
	{"ID" : "0", "Level" : "0", "Path" : "`AUTOTB_DUT_INST", "Parent" : "", "Child" : ["1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22"],
		"CDFG" : "scheduler_hls",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "1",
		"VariableLatency" : "0", "ExactLatency" : "0", "EstimateLatencyMin" : "0", "EstimateLatencyMax" : "0",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "cntrl_start", "Type" : "None", "Direction" : "I"},
			{"Name" : "cntrl_reset_n", "Type" : "None", "Direction" : "I"},
			{"Name" : "cntrl_layer_idx", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "cntrl_busy", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "cntrl_start_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "axis_in_valid", "Type" : "None", "Direction" : "I"},
			{"Name" : "axis_in_last", "Type" : "None", "Direction" : "I"},
			{"Name" : "axis_in_ready", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "wl_ready", "Type" : "None", "Direction" : "I"},
			{"Name" : "wl_start", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "wl_addr_sel", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "wl_layer", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "wl_head", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "wl_tile", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "dma_done", "Type" : "None", "Direction" : "I"},
			{"Name" : "compute_ready", "Type" : "None", "Direction" : "I"},
			{"Name" : "compute_done", "Type" : "None", "Direction" : "I"},
			{"Name" : "requant_ready", "Type" : "None", "Direction" : "I"},
			{"Name" : "requant_done", "Type" : "None", "Direction" : "I"},
			{"Name" : "head_ctx_ref_0", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "head_ctx_ref_1", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "head_ctx_ref_2", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "head_ctx_ref_3", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "compute_start", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "compute_op", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "requant_start", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "requant_op", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "stream_ready", "Type" : "None", "Direction" : "I"},
			{"Name" : "stream_start", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "stream_done", "Type" : "None", "Direction" : "I"},
			{"Name" : "done", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "STATE", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "attn_started", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "group_idx", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "start_head_group", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "concat_compute_done", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "concat_started", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "outproj_started", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "outproj_compute_done", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "resid0_started", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "resid0_compute_done", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "ln0_started", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "ln0_compute_done", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "ffn_w1_compute_done", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "ffn_act_compute_done", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "ffn_w2_compute_done", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "ffn_stage", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "ffn_started", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "resid1_started", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "resid1_compute_done", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "ln1_started", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "ln1_compute_done", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "st", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "layer_idx", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "stream_started", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "wo_tile", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "wo_dma_busy", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "wo_comp_busy", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "w1_tile", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "w1_dma_busy", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "w1_comp_busy", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "w2_tile", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "w2_dma_busy", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "w2_comp_busy", "Type" : "OVld", "Direction" : "IO"}]},
	{"ID" : "1", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.call_ret_run_single_head_fu_7748", "Parent" : "0",
		"CDFG" : "run_single_head",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "0", "ap_start" : "0", "ap_ready" : "1", "ap_done" : "0", "ap_continue" : "0", "ap_idle" : "0", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "1",
		"VariableLatency" : "0", "ExactLatency" : "0", "EstimateLatencyMin" : "0", "EstimateLatencyMax" : "0",
		"Combinational" : "1",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "ctx_layer_stamp_read", "Type" : "None", "Direction" : "I"},
			{"Name" : "ctx_phase_read", "Type" : "None", "Direction" : "I"},
			{"Name" : "ctx_compute_ready_read", "Type" : "None", "Direction" : "I"},
			{"Name" : "ctx_compute_done_read", "Type" : "None", "Direction" : "I"},
			{"Name" : "ctx_compute_op_read", "Type" : "None", "Direction" : "I"},
			{"Name" : "ctx_start_head_read", "Type" : "None", "Direction" : "I"},
			{"Name" : "ctx_q_started_read", "Type" : "None", "Direction" : "I"},
			{"Name" : "ctx_k_started_read", "Type" : "None", "Direction" : "I"},
			{"Name" : "ctx_v_started_read", "Type" : "None", "Direction" : "I"},
			{"Name" : "ctx_att_scores_started_read", "Type" : "None", "Direction" : "I"},
			{"Name" : "ctx_val_scale_started_read", "Type" : "None", "Direction" : "I"},
			{"Name" : "ctx_softmax_started_read", "Type" : "None", "Direction" : "I"},
			{"Name" : "ctx_att_value_started_read", "Type" : "None", "Direction" : "I"},
			{"Name" : "ctx_q_compute_done_read", "Type" : "None", "Direction" : "I"},
			{"Name" : "ctx_k_compute_done_read", "Type" : "None", "Direction" : "I"},
			{"Name" : "ctx_v_compute_done_read", "Type" : "None", "Direction" : "I"},
			{"Name" : "ctx_att_scores_compute_done_read", "Type" : "None", "Direction" : "I"},
			{"Name" : "ctx_val_scale_compute_done_read", "Type" : "None", "Direction" : "I"},
			{"Name" : "ctx_softmax_compute_done_read", "Type" : "None", "Direction" : "I"},
			{"Name" : "ctx_att_value_compute_done_read", "Type" : "None", "Direction" : "I"},
			{"Name" : "ctx_layer_stamp_write", "Type" : "None", "Direction" : "I"}]},
	{"ID" : "2", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.sparsemux_9_2_32_1_1_U22", "Parent" : "0"},
	{"ID" : "3", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.sparsemux_9_2_8_1_1_U23", "Parent" : "0"},
	{"ID" : "4", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.sparsemux_9_2_1_1_1_U24", "Parent" : "0"},
	{"ID" : "5", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.sparsemux_9_2_1_1_1_U25", "Parent" : "0"},
	{"ID" : "6", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.sparsemux_9_2_1_1_1_U26", "Parent" : "0"},
	{"ID" : "7", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.sparsemux_9_2_8_1_1_U27", "Parent" : "0"},
	{"ID" : "8", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.sparsemux_9_2_1_1_1_U28", "Parent" : "0"},
	{"ID" : "9", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.sparsemux_9_2_1_1_1_U29", "Parent" : "0"},
	{"ID" : "10", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.sparsemux_9_2_1_1_1_U30", "Parent" : "0"},
	{"ID" : "11", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.sparsemux_9_2_1_1_1_U31", "Parent" : "0"},
	{"ID" : "12", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.sparsemux_9_2_1_1_1_U32", "Parent" : "0"},
	{"ID" : "13", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.sparsemux_9_2_1_1_1_U33", "Parent" : "0"},
	{"ID" : "14", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.sparsemux_9_2_1_1_1_U34", "Parent" : "0"},
	{"ID" : "15", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.sparsemux_9_2_1_1_1_U35", "Parent" : "0"},
	{"ID" : "16", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.sparsemux_9_2_1_1_1_U36", "Parent" : "0"},
	{"ID" : "17", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.sparsemux_9_2_1_1_1_U37", "Parent" : "0"},
	{"ID" : "18", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.sparsemux_9_2_1_1_1_U38", "Parent" : "0"},
	{"ID" : "19", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.sparsemux_9_2_1_1_1_U39", "Parent" : "0"},
	{"ID" : "20", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.sparsemux_9_2_1_1_1_U40", "Parent" : "0"},
	{"ID" : "21", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.sparsemux_9_2_1_1_1_U41", "Parent" : "0"},
	{"ID" : "22", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.sparsemux_9_2_1_1_1_U42", "Parent" : "0"}]}
