// ==============================================================
// Generated by Vitis HLS v2025.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="ControlMemInterface_ControlMemInterface,hls_ip_2025_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xck26-sfvc784-2LV-c,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=1.977100,HLS_SYN_LAT=0,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=0,HLS_SYN_LUT=1189,HLS_VERSION=2025_1}" *)

module ControlMemInterface (
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        mem_i,
        mem_o,
        mem_o_ap_vld,
        address,
        data_in,
        data_out,
        data_out_ap_vld,
        read_control,
        write_control,
        chip_enable,
        reset_n,
        ap_rst
);


input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [863:0] mem_i;
output  [863:0] mem_o;
output   mem_o_ap_vld;
input  [31:0] address;
input  [31:0] data_in;
output  [31:0] data_out;
output   data_out_ap_vld;
input  [0:0] read_control;
input  [0:0] write_control;
input  [0:0] chip_enable;
input  [0:0] reset_n;
input   ap_rst;

reg[863:0] mem_o;
reg mem_o_ap_vld;
reg data_out_ap_vld;

wire   [0:0] xor_ln132_fu_1071_p2;
reg   [0:0] ap_phi_mux_mem_flag_3_phi_fu_365_p116;
wire   [0:0] chip_enable_read_read_fu_312_p2;
wire   [0:0] read_control_read_read_fu_324_p2;
wire   [31:0] address_read_read_fu_336_p2;
wire   [0:0] write_control_read_read_fu_318_p2;
reg   [863:0] ap_phi_mux_mem_new_3_phi_fu_513_p116;
wire   [863:0] or_ln26_fu_1121_p3;
wire   [863:0] or_ln25_fu_1134_p4;
wire   [863:0] or_ln24_fu_1159_p4;
wire   [863:0] or_ln23_fu_1184_p4;
wire   [863:0] or_ln22_fu_1209_p4;
wire   [863:0] or_ln21_fu_1234_p4;
wire   [863:0] or_ln20_fu_1259_p4;
wire   [863:0] or_ln19_fu_1284_p4;
wire   [863:0] or_ln18_fu_1309_p4;
wire   [863:0] or_ln17_fu_1334_p4;
wire   [863:0] or_ln16_fu_1359_p4;
wire   [863:0] or_ln15_fu_1384_p4;
wire   [863:0] or_ln14_fu_1409_p4;
wire   [863:0] or_ln13_fu_1434_p4;
wire   [863:0] or_ln12_fu_1459_p4;
wire   [863:0] or_ln11_fu_1484_p4;
wire   [863:0] or_ln10_fu_1509_p4;
wire   [863:0] or_ln9_fu_1534_p4;
wire   [863:0] or_ln8_fu_1559_p4;
wire   [863:0] or_ln7_fu_1584_p4;
wire   [863:0] or_ln6_fu_1609_p4;
wire   [863:0] or_ln5_fu_1634_p4;
wire   [863:0] or_ln4_fu_1659_p4;
wire   [863:0] or_ln3_fu_1684_p4;
wire   [863:0] or_ln2_fu_1709_p4;
wire   [863:0] or_ln1_fu_1734_p4;
wire   [863:0] or_ln_fu_1755_p3;
reg   [0:0] ap_phi_mux_data_out_flag_0_phi_fu_666_p116;
wire   [31:0] grp_fu_1061_p4;
reg   [31:0] ap_phi_mux_data_out_new_0_phi_fu_845_p116;
wire   [31:0] trunc_ln6_fu_2039_p1;
wire   [863:0] select_ln132_fu_1108_p3;
wire   [831:0] trunc_ln133_fu_1117_p1;
wire   [799:0] trunc_ln75_fu_1130_p1;
wire   [63:0] tmp_23_fu_1145_p4;
wire   [767:0] trunc_ln74_fu_1155_p1;
wire   [95:0] tmp_22_fu_1170_p4;
wire   [735:0] trunc_ln73_fu_1180_p1;
wire   [127:0] tmp_21_fu_1195_p4;
wire   [703:0] trunc_ln72_fu_1205_p1;
wire   [159:0] tmp_20_fu_1220_p4;
wire   [671:0] trunc_ln71_fu_1230_p1;
wire   [191:0] tmp_19_fu_1245_p4;
wire   [639:0] trunc_ln70_fu_1255_p1;
wire   [223:0] tmp_18_fu_1270_p4;
wire   [607:0] trunc_ln69_fu_1280_p1;
wire   [255:0] tmp_17_fu_1295_p4;
wire   [575:0] trunc_ln67_fu_1305_p1;
wire   [287:0] tmp_16_fu_1320_p4;
wire   [543:0] trunc_ln66_fu_1330_p1;
wire   [319:0] tmp_15_fu_1345_p4;
wire   [511:0] trunc_ln64_fu_1355_p1;
wire   [351:0] tmp_14_fu_1370_p4;
wire   [479:0] trunc_ln63_fu_1380_p1;
wire   [383:0] tmp_13_fu_1395_p4;
wire   [447:0] trunc_ln62_fu_1405_p1;
wire   [415:0] tmp_12_fu_1420_p4;
wire   [415:0] trunc_ln61_fu_1430_p1;
wire   [447:0] tmp_11_fu_1445_p4;
wire   [383:0] trunc_ln60_fu_1455_p1;
wire   [479:0] tmp_10_fu_1470_p4;
wire   [351:0] trunc_ln59_fu_1480_p1;
wire   [511:0] tmp_8_fu_1495_p4;
wire   [319:0] trunc_ln57_fu_1505_p1;
wire   [543:0] tmp_6_fu_1520_p4;
wire   [287:0] trunc_ln56_fu_1530_p1;
wire   [575:0] tmp_4_fu_1545_p4;
wire   [255:0] trunc_ln55_fu_1555_p1;
wire   [607:0] tmp_2_fu_1570_p4;
wire   [223:0] trunc_ln53_fu_1580_p1;
wire   [639:0] tmp_s_fu_1595_p4;
wire   [191:0] trunc_ln52_fu_1605_p1;
wire   [671:0] tmp_9_fu_1620_p4;
wire   [159:0] trunc_ln51_fu_1630_p1;
wire   [703:0] tmp_7_fu_1645_p4;
wire   [127:0] trunc_ln49_fu_1655_p1;
wire   [735:0] tmp_5_fu_1670_p4;
wire   [95:0] trunc_ln48_fu_1680_p1;
wire   [767:0] tmp_3_fu_1695_p4;
wire   [63:0] trunc_ln47_fu_1705_p1;
wire   [799:0] tmp_1_fu_1720_p4;
wire   [31:0] trunc_ln46_fu_1730_p1;
wire   [831:0] tmp_fu_1745_p4;
wire    ap_ce_reg;

always @ (*) begin
    if ((chip_enable_read_read_fu_312_p2 == 1'd0)) begin
        ap_phi_mux_data_out_flag_0_phi_fu_666_p116 = 1'd0;
    end else if ((((32'd36 == address_read_read_fu_336_p2) & (read_control_read_read_fu_324_p2 == 1'd1) & (chip_enable_read_read_fu_312_p2 == 1'd1)) | ((32'd36 == address_read_read_fu_336_p2) & (read_control_read_read_fu_324_p2 == 1'd0) & (chip_enable_read_read_fu_312_p2 == 1'd1) & (write_control_read_read_fu_318_p2 == 1'd1)) | ((32'd40 == address_read_read_fu_336_p2) & (read_control_read_read_fu_324_p2 == 1'd1) & (chip_enable_read_read_fu_312_p2 == 1'd1)) | ((32'd40 == address_read_read_fu_336_p2) & (read_control_read_read_fu_324_p2 == 1'd0) & (chip_enable_read_read_fu_312_p2 == 1'd1) & (write_control_read_read_fu_318_p2 == 1'd1)) | ((32'd44 == address_read_read_fu_336_p2) & (read_control_read_read_fu_324_p2 == 1'd1) & (chip_enable_read_read_fu_312_p2 == 1'd1)) | ((32'd44 == address_read_read_fu_336_p2) & (read_control_read_read_fu_324_p2 == 1'd0) & (chip_enable_read_read_fu_312_p2 == 1'd1) & (write_control_read_read_fu_318_p2 == 1'd1)) | ((32'd48 == address_read_read_fu_336_p2) & (read_control_read_read_fu_324_p2 == 1'd1) & 
    (chip_enable_read_read_fu_312_p2 == 1'd1)) | ((32'd48 == address_read_read_fu_336_p2) & (read_control_read_read_fu_324_p2 == 1'd0) & (chip_enable_read_read_fu_312_p2 == 1'd1) & (write_control_read_read_fu_318_p2 == 1'd1)) | ((32'd52 == address_read_read_fu_336_p2) & (read_control_read_read_fu_324_p2 == 1'd1) & (chip_enable_read_read_fu_312_p2 == 1'd1)) | ((32'd52 == address_read_read_fu_336_p2) & (read_control_read_read_fu_324_p2 == 1'd0) & (chip_enable_read_read_fu_312_p2 == 1'd1) & (write_control_read_read_fu_318_p2 == 1'd1)) | ((32'd56 == address_read_read_fu_336_p2) & (read_control_read_read_fu_324_p2 == 1'd1) & (chip_enable_read_read_fu_312_p2 == 1'd1)) | ((32'd56 == address_read_read_fu_336_p2) & (read_control_read_read_fu_324_p2 == 1'd0) & (chip_enable_read_read_fu_312_p2 == 1'd1) & (write_control_read_read_fu_318_p2 == 1'd1)) | ((32'd60 == address_read_read_fu_336_p2) & (read_control_read_read_fu_324_p2 == 1'd1) & (chip_enable_read_read_fu_312_p2 == 1'd1)) | ((32'd60 == address_read_read_fu_336_p2) & (read_control_read_read_fu_324_p2 
    == 1'd0) & (chip_enable_read_read_fu_312_p2 == 1'd1) & (write_control_read_read_fu_318_p2 == 1'd1)) | ((32'd64 == address_read_read_fu_336_p2) & (read_control_read_read_fu_324_p2 == 1'd1) & (chip_enable_read_read_fu_312_p2 == 1'd1)) | ((32'd64 == address_read_read_fu_336_p2) & (read_control_read_read_fu_324_p2 == 1'd0) & (chip_enable_read_read_fu_312_p2 == 1'd1) & (write_control_read_read_fu_318_p2 == 1'd1)) | ((32'd68 == address_read_read_fu_336_p2) & (read_control_read_read_fu_324_p2 == 1'd1) & (chip_enable_read_read_fu_312_p2 == 1'd1)) | ((32'd68 == address_read_read_fu_336_p2) & (read_control_read_read_fu_324_p2 == 1'd0) & (chip_enable_read_read_fu_312_p2 == 1'd1) & (write_control_read_read_fu_318_p2 == 1'd1)) | ((32'd72 == address_read_read_fu_336_p2) & (read_control_read_read_fu_324_p2 == 1'd1) & (chip_enable_read_read_fu_312_p2 == 1'd1)) | ((32'd72 == address_read_read_fu_336_p2) & (read_control_read_read_fu_324_p2 == 1'd0) & (chip_enable_read_read_fu_312_p2 == 1'd1) & (write_control_read_read_fu_318_p2 
    == 1'd1)) | ((32'd76 == address_read_read_fu_336_p2) & (read_control_read_read_fu_324_p2 == 1'd1) & (chip_enable_read_read_fu_312_p2 == 1'd1)) | ((32'd76 == address_read_read_fu_336_p2) & (read_control_read_read_fu_324_p2 == 1'd0) & (chip_enable_read_read_fu_312_p2 == 1'd1) & (write_control_read_read_fu_318_p2 == 1'd1)) | ((32'd80 == address_read_read_fu_336_p2) & (read_control_read_read_fu_324_p2 == 1'd1) & (chip_enable_read_read_fu_312_p2 == 1'd1)) | ((32'd80 == address_read_read_fu_336_p2) & (read_control_read_read_fu_324_p2 == 1'd0) & (chip_enable_read_read_fu_312_p2 == 1'd1) & (write_control_read_read_fu_318_p2 == 1'd1)) | ((32'd84 == address_read_read_fu_336_p2) & (read_control_read_read_fu_324_p2 == 1'd1) & (chip_enable_read_read_fu_312_p2 == 1'd1)) | ((32'd84 == address_read_read_fu_336_p2) & (read_control_read_read_fu_324_p2 == 1'd0) & (chip_enable_read_read_fu_312_p2 == 1'd1) & (write_control_read_read_fu_318_p2 == 1'd1)) | ((32'd88 == address_read_read_fu_336_p2) & (read_control_read_read_fu_324_p2 
    == 1'd1) & (chip_enable_read_read_fu_312_p2 == 1'd1)) | ((32'd88 == address_read_read_fu_336_p2) & (read_control_read_read_fu_324_p2 == 1'd0) & (chip_enable_read_read_fu_312_p2 == 1'd1) & (write_control_read_read_fu_318_p2 == 1'd1)) | ((32'd92 == address_read_read_fu_336_p2) & (read_control_read_read_fu_324_p2 == 1'd1) & (chip_enable_read_read_fu_312_p2 == 1'd1)) | ((32'd92 == address_read_read_fu_336_p2) & (read_control_read_read_fu_324_p2 == 1'd0) & (chip_enable_read_read_fu_312_p2 == 1'd1) & (write_control_read_read_fu_318_p2 == 1'd1)) | ((32'd96 == address_read_read_fu_336_p2) & (read_control_read_read_fu_324_p2 == 1'd1) & (chip_enable_read_read_fu_312_p2 == 1'd1)) | ((32'd96 == address_read_read_fu_336_p2) & (read_control_read_read_fu_324_p2 == 1'd0) & (chip_enable_read_read_fu_312_p2 == 1'd1) & (write_control_read_read_fu_318_p2 == 1'd1)) | ((32'd100 == address_read_read_fu_336_p2) & (read_control_read_read_fu_324_p2 == 1'd1) & (chip_enable_read_read_fu_312_p2 == 1'd1)) | ((32'd100 == address_read_read_fu_336_p2) 
    & (read_control_read_read_fu_324_p2 == 1'd0) & (chip_enable_read_read_fu_312_p2 == 1'd1) & (write_control_read_read_fu_318_p2 == 1'd1)) | ((32'd104 == address_read_read_fu_336_p2) & (read_control_read_read_fu_324_p2 == 1'd1) & (chip_enable_read_read_fu_312_p2 == 1'd1)) | ((32'd104 == address_read_read_fu_336_p2) & (read_control_read_read_fu_324_p2 == 1'd0) & (chip_enable_read_read_fu_312_p2 == 1'd1) & (write_control_read_read_fu_318_p2 == 1'd1)) | ((read_control_read_read_fu_324_p2 == 1'd1) & (chip_enable_read_read_fu_312_p2 == 1'd1) & (32'd0 == address_read_read_fu_336_p2)) | ((read_control_read_read_fu_324_p2 == 1'd1) & (chip_enable_read_read_fu_312_p2 == 1'd1) & (32'd4 == address_read_read_fu_336_p2)) | ((read_control_read_read_fu_324_p2 == 1'd1) & (chip_enable_read_read_fu_312_p2 == 1'd1) & (32'd8 == address_read_read_fu_336_p2)) | ((read_control_read_read_fu_324_p2 == 1'd1) & (chip_enable_read_read_fu_312_p2 == 1'd1) & (32'd12 == address_read_read_fu_336_p2)) | ((read_control_read_read_fu_324_p2 == 1'd1) 
    & (chip_enable_read_read_fu_312_p2 == 1'd1) & (32'd16 == address_read_read_fu_336_p2)) | ((read_control_read_read_fu_324_p2 == 1'd1) & (chip_enable_read_read_fu_312_p2 == 1'd1) & (32'd20 == address_read_read_fu_336_p2)) | ((read_control_read_read_fu_324_p2 == 1'd1) & (chip_enable_read_read_fu_312_p2 == 1'd1) & (32'd24 == address_read_read_fu_336_p2)) | ((read_control_read_read_fu_324_p2 == 1'd1) & (chip_enable_read_read_fu_312_p2 == 1'd1) & (32'd28 == address_read_read_fu_336_p2)) | ((read_control_read_read_fu_324_p2 == 1'd1) & (chip_enable_read_read_fu_312_p2 == 1'd1) & (32'd32 == address_read_read_fu_336_p2)) | ((read_control_read_read_fu_324_p2 == 1'd0) & (chip_enable_read_read_fu_312_p2 == 1'd1) & (write_control_read_read_fu_318_p2 == 1'd0)) | ((read_control_read_read_fu_324_p2 == 1'd0) & (chip_enable_read_read_fu_312_p2 == 1'd1) & (write_control_read_read_fu_318_p2 == 1'd1) & (32'd0 == address_read_read_fu_336_p2)) | ((read_control_read_read_fu_324_p2 == 1'd0) & (chip_enable_read_read_fu_312_p2 == 1'd1) & 
    (write_control_read_read_fu_318_p2 == 1'd1) & (32'd4 == address_read_read_fu_336_p2)) | ((read_control_read_read_fu_324_p2 == 1'd0) & (chip_enable_read_read_fu_312_p2 == 1'd1) & (write_control_read_read_fu_318_p2 == 1'd1) & (32'd8 == address_read_read_fu_336_p2)) | ((read_control_read_read_fu_324_p2 == 1'd0) & (chip_enable_read_read_fu_312_p2 == 1'd1) & (write_control_read_read_fu_318_p2 == 1'd1) & (32'd12 == address_read_read_fu_336_p2)) | ((read_control_read_read_fu_324_p2 == 1'd0) & (chip_enable_read_read_fu_312_p2 == 1'd1) & (write_control_read_read_fu_318_p2 == 1'd1) & (32'd16 == address_read_read_fu_336_p2)) | ((read_control_read_read_fu_324_p2 == 1'd0) & (chip_enable_read_read_fu_312_p2 == 1'd1) & (write_control_read_read_fu_318_p2 == 1'd1) & (32'd20 == address_read_read_fu_336_p2)) | ((read_control_read_read_fu_324_p2 == 1'd0) & (chip_enable_read_read_fu_312_p2 == 1'd1) & (write_control_read_read_fu_318_p2 == 1'd1) & (32'd24 == address_read_read_fu_336_p2)) | ((read_control_read_read_fu_324_p2 == 1'd0) 
    & (chip_enable_read_read_fu_312_p2 == 1'd1) & (write_control_read_read_fu_318_p2 == 1'd1) & (32'd28 == address_read_read_fu_336_p2)) | ((read_control_read_read_fu_324_p2 == 1'd0) & (chip_enable_read_read_fu_312_p2 == 1'd1) & (write_control_read_read_fu_318_p2 == 1'd1) & (32'd32 == address_read_read_fu_336_p2)) | (~(32'd36 == address_read_read_fu_336_p2) & ~(32'd40 == address_read_read_fu_336_p2) & ~(32'd44 == address_read_read_fu_336_p2) & ~(32'd48 == address_read_read_fu_336_p2) & ~(32'd52 == address_read_read_fu_336_p2) & ~(32'd56 == address_read_read_fu_336_p2) & ~(32'd60 == address_read_read_fu_336_p2) & ~(32'd64 == address_read_read_fu_336_p2) & ~(32'd68 == address_read_read_fu_336_p2) & ~(32'd72 == address_read_read_fu_336_p2) & ~(32'd76 == address_read_read_fu_336_p2) & ~(32'd80 == address_read_read_fu_336_p2) & ~(32'd84 == address_read_read_fu_336_p2) & ~(32'd88 == address_read_read_fu_336_p2) & ~(32'd92 == address_read_read_fu_336_p2) & ~(32'd96 == address_read_read_fu_336_p2) & ~(32'd100 == address_read_read_fu_336_p2) 
    & ~(32'd104 == address_read_read_fu_336_p2) & ~(32'd0 == address_read_read_fu_336_p2) & ~(32'd4 == address_read_read_fu_336_p2) & ~(32'd8 == address_read_read_fu_336_p2) & ~(32'd12 == address_read_read_fu_336_p2) & ~(32'd16 == address_read_read_fu_336_p2) & ~(32'd20 == address_read_read_fu_336_p2) & ~(32'd24 == address_read_read_fu_336_p2) & ~(32'd28 == address_read_read_fu_336_p2) & ~(32'd32 == address_read_read_fu_336_p2) & (read_control_read_read_fu_324_p2 == 1'd1) & (chip_enable_read_read_fu_312_p2 == 1'd1)) | (~(32'd36 == address_read_read_fu_336_p2) & ~(32'd40 == address_read_read_fu_336_p2) & ~(32'd44 == address_read_read_fu_336_p2) & ~(32'd48 == address_read_read_fu_336_p2) & ~(32'd52 == address_read_read_fu_336_p2) & ~(32'd56 == address_read_read_fu_336_p2) & ~(32'd60 == address_read_read_fu_336_p2) & ~(32'd64 == address_read_read_fu_336_p2) & ~(32'd68 == address_read_read_fu_336_p2) & ~(32'd72 == address_read_read_fu_336_p2) & ~(32'd76 == address_read_read_fu_336_p2) & ~(32'd80 == address_read_read_fu_336_p2) 
    & ~(32'd84 == address_read_read_fu_336_p2) & ~(32'd88 == address_read_read_fu_336_p2) & ~(32'd92 == address_read_read_fu_336_p2) & ~(32'd96 == address_read_read_fu_336_p2) & ~(32'd100 == address_read_read_fu_336_p2) & ~(32'd104 == address_read_read_fu_336_p2) & ~(32'd0 == address_read_read_fu_336_p2) & ~(32'd4 == address_read_read_fu_336_p2) & ~(32'd8 == address_read_read_fu_336_p2) & ~(32'd12 == address_read_read_fu_336_p2) & ~(32'd16 == address_read_read_fu_336_p2) & ~(32'd20 == address_read_read_fu_336_p2) & ~(32'd24 == address_read_read_fu_336_p2) & ~(32'd28 == address_read_read_fu_336_p2) & ~(32'd32 == address_read_read_fu_336_p2) & (read_control_read_read_fu_324_p2 == 1'd0) & (chip_enable_read_read_fu_312_p2 == 1'd1) & (write_control_read_read_fu_318_p2 == 1'd1)))) begin
        ap_phi_mux_data_out_flag_0_phi_fu_666_p116 = 1'd1;
    end else begin
        ap_phi_mux_data_out_flag_0_phi_fu_666_p116 = 'bx;
    end
end

always @ (*) begin
    if ((((32'd36 == address_read_read_fu_336_p2) & (read_control_read_read_fu_324_p2 == 1'd0) & (chip_enable_read_read_fu_312_p2 == 1'd1) & (write_control_read_read_fu_318_p2 == 1'd1)) | ((32'd40 == address_read_read_fu_336_p2) & (read_control_read_read_fu_324_p2 == 1'd0) & (chip_enable_read_read_fu_312_p2 == 1'd1) & (write_control_read_read_fu_318_p2 == 1'd1)) | ((32'd44 == address_read_read_fu_336_p2) & (read_control_read_read_fu_324_p2 == 1'd0) & (chip_enable_read_read_fu_312_p2 == 1'd1) & (write_control_read_read_fu_318_p2 == 1'd1)) | ((32'd48 == address_read_read_fu_336_p2) & (read_control_read_read_fu_324_p2 == 1'd0) & (chip_enable_read_read_fu_312_p2 == 1'd1) & (write_control_read_read_fu_318_p2 == 1'd1)) | ((32'd52 == address_read_read_fu_336_p2) & (read_control_read_read_fu_324_p2 == 1'd0) & (chip_enable_read_read_fu_312_p2 == 1'd1) & (write_control_read_read_fu_318_p2 == 1'd1)) | ((32'd56 == address_read_read_fu_336_p2) & (read_control_read_read_fu_324_p2 == 1'd0) & (chip_enable_read_read_fu_312_p2 == 1'd1) 
    & (write_control_read_read_fu_318_p2 == 1'd1)) | ((32'd60 == address_read_read_fu_336_p2) & (read_control_read_read_fu_324_p2 == 1'd0) & (chip_enable_read_read_fu_312_p2 == 1'd1) & (write_control_read_read_fu_318_p2 == 1'd1)) | ((32'd64 == address_read_read_fu_336_p2) & (read_control_read_read_fu_324_p2 == 1'd0) & (chip_enable_read_read_fu_312_p2 == 1'd1) & (write_control_read_read_fu_318_p2 == 1'd1)) | ((32'd68 == address_read_read_fu_336_p2) & (read_control_read_read_fu_324_p2 == 1'd0) & (chip_enable_read_read_fu_312_p2 == 1'd1) & (write_control_read_read_fu_318_p2 == 1'd1)) | ((32'd72 == address_read_read_fu_336_p2) & (read_control_read_read_fu_324_p2 == 1'd0) & (chip_enable_read_read_fu_312_p2 == 1'd1) & (write_control_read_read_fu_318_p2 == 1'd1)) | ((32'd76 == address_read_read_fu_336_p2) & (read_control_read_read_fu_324_p2 == 1'd0) & (chip_enable_read_read_fu_312_p2 == 1'd1) & (write_control_read_read_fu_318_p2 == 1'd1)) | ((32'd80 == address_read_read_fu_336_p2) & (read_control_read_read_fu_324_p2 == 1'd0) 
    & (chip_enable_read_read_fu_312_p2 == 1'd1) & (write_control_read_read_fu_318_p2 == 1'd1)) | ((32'd84 == address_read_read_fu_336_p2) & (read_control_read_read_fu_324_p2 == 1'd0) & (chip_enable_read_read_fu_312_p2 == 1'd1) & (write_control_read_read_fu_318_p2 == 1'd1)) | ((32'd88 == address_read_read_fu_336_p2) & (read_control_read_read_fu_324_p2 == 1'd0) & (chip_enable_read_read_fu_312_p2 == 1'd1) & (write_control_read_read_fu_318_p2 == 1'd1)) | ((32'd92 == address_read_read_fu_336_p2) & (read_control_read_read_fu_324_p2 == 1'd0) & (chip_enable_read_read_fu_312_p2 == 1'd1) & (write_control_read_read_fu_318_p2 == 1'd1)) | ((32'd96 == address_read_read_fu_336_p2) & (read_control_read_read_fu_324_p2 == 1'd0) & (chip_enable_read_read_fu_312_p2 == 1'd1) & (write_control_read_read_fu_318_p2 == 1'd1)) | ((32'd100 == address_read_read_fu_336_p2) & (read_control_read_read_fu_324_p2 == 1'd0) & (chip_enable_read_read_fu_312_p2 == 1'd1) & (write_control_read_read_fu_318_p2 == 1'd1)) | ((32'd104 == address_read_read_fu_336_p2) 
    & (read_control_read_read_fu_324_p2 == 1'd0) & (chip_enable_read_read_fu_312_p2 == 1'd1) & (write_control_read_read_fu_318_p2 == 1'd1)) | ((read_control_read_read_fu_324_p2 == 1'd0) & (chip_enable_read_read_fu_312_p2 == 1'd1) & (write_control_read_read_fu_318_p2 == 1'd0)) | ((read_control_read_read_fu_324_p2 == 1'd0) & (chip_enable_read_read_fu_312_p2 == 1'd1) & (write_control_read_read_fu_318_p2 == 1'd1) & (32'd0 == address_read_read_fu_336_p2)) | ((read_control_read_read_fu_324_p2 == 1'd0) & (chip_enable_read_read_fu_312_p2 == 1'd1) & (write_control_read_read_fu_318_p2 == 1'd1) & (32'd4 == address_read_read_fu_336_p2)) | ((read_control_read_read_fu_324_p2 == 1'd0) & (chip_enable_read_read_fu_312_p2 == 1'd1) & (write_control_read_read_fu_318_p2 == 1'd1) & (32'd8 == address_read_read_fu_336_p2)) | ((read_control_read_read_fu_324_p2 == 1'd0) & (chip_enable_read_read_fu_312_p2 == 1'd1) & (write_control_read_read_fu_318_p2 == 1'd1) & (32'd12 == address_read_read_fu_336_p2)) | ((read_control_read_read_fu_324_p2 == 
    1'd0) & (chip_enable_read_read_fu_312_p2 == 1'd1) & (write_control_read_read_fu_318_p2 == 1'd1) & (32'd16 == address_read_read_fu_336_p2)) | ((read_control_read_read_fu_324_p2 == 1'd0) & (chip_enable_read_read_fu_312_p2 == 1'd1) & (write_control_read_read_fu_318_p2 == 1'd1) & (32'd20 == address_read_read_fu_336_p2)) | ((read_control_read_read_fu_324_p2 == 1'd0) & (chip_enable_read_read_fu_312_p2 == 1'd1) & (write_control_read_read_fu_318_p2 == 1'd1) & (32'd24 == address_read_read_fu_336_p2)) | ((read_control_read_read_fu_324_p2 == 1'd0) & (chip_enable_read_read_fu_312_p2 == 1'd1) & (write_control_read_read_fu_318_p2 == 1'd1) & (32'd28 == address_read_read_fu_336_p2)) | ((read_control_read_read_fu_324_p2 == 1'd0) & (chip_enable_read_read_fu_312_p2 == 1'd1) & (write_control_read_read_fu_318_p2 == 1'd1) & (32'd32 == address_read_read_fu_336_p2)) | (~(32'd36 == address_read_read_fu_336_p2) & ~(32'd40 == address_read_read_fu_336_p2) & ~(32'd44 == address_read_read_fu_336_p2) & ~(32'd48 == address_read_read_fu_336_p2) 
    & ~(32'd52 == address_read_read_fu_336_p2) & ~(32'd56 == address_read_read_fu_336_p2) & ~(32'd60 == address_read_read_fu_336_p2) & ~(32'd64 == address_read_read_fu_336_p2) & ~(32'd68 == address_read_read_fu_336_p2) & ~(32'd72 == address_read_read_fu_336_p2) & ~(32'd76 == address_read_read_fu_336_p2) & ~(32'd80 == address_read_read_fu_336_p2) & ~(32'd84 == address_read_read_fu_336_p2) & ~(32'd88 == address_read_read_fu_336_p2) & ~(32'd92 == address_read_read_fu_336_p2) & ~(32'd96 == address_read_read_fu_336_p2) & ~(32'd100 == address_read_read_fu_336_p2) & ~(32'd104 == address_read_read_fu_336_p2) & ~(32'd0 == address_read_read_fu_336_p2) & ~(32'd4 == address_read_read_fu_336_p2) & ~(32'd8 == address_read_read_fu_336_p2) & ~(32'd12 == address_read_read_fu_336_p2) & ~(32'd16 == address_read_read_fu_336_p2) & ~(32'd20 == address_read_read_fu_336_p2) & ~(32'd24 == address_read_read_fu_336_p2) & ~(32'd28 == address_read_read_fu_336_p2) & ~(32'd32 == address_read_read_fu_336_p2) & (read_control_read_read_fu_324_p2 == 
    1'd1) & (chip_enable_read_read_fu_312_p2 == 1'd1)) | (~(32'd36 == address_read_read_fu_336_p2) & ~(32'd40 == address_read_read_fu_336_p2) & ~(32'd44 == address_read_read_fu_336_p2) & ~(32'd48 == address_read_read_fu_336_p2) & ~(32'd52 == address_read_read_fu_336_p2) & ~(32'd56 == address_read_read_fu_336_p2) & ~(32'd60 == address_read_read_fu_336_p2) & ~(32'd64 == address_read_read_fu_336_p2) & ~(32'd68 == address_read_read_fu_336_p2) & ~(32'd72 == address_read_read_fu_336_p2) & ~(32'd76 == address_read_read_fu_336_p2) & ~(32'd80 == address_read_read_fu_336_p2) & ~(32'd84 == address_read_read_fu_336_p2) & ~(32'd88 == address_read_read_fu_336_p2) & ~(32'd92 == address_read_read_fu_336_p2) & ~(32'd96 == address_read_read_fu_336_p2) & ~(32'd100 == address_read_read_fu_336_p2) & ~(32'd104 == address_read_read_fu_336_p2) & ~(32'd0 == address_read_read_fu_336_p2) & ~(32'd4 == address_read_read_fu_336_p2) & ~(32'd8 == address_read_read_fu_336_p2) & ~(32'd12 == address_read_read_fu_336_p2) & ~(32'd16 == address_read_read_fu_336_p2) 
    & ~(32'd20 == address_read_read_fu_336_p2) & ~(32'd24 == address_read_read_fu_336_p2) & ~(32'd28 == address_read_read_fu_336_p2) & ~(32'd32 == address_read_read_fu_336_p2) & (read_control_read_read_fu_324_p2 == 1'd0) & (chip_enable_read_read_fu_312_p2 == 1'd1) & (write_control_read_read_fu_318_p2 == 1'd1)))) begin
        ap_phi_mux_data_out_new_0_phi_fu_845_p116 = 32'd0;
    end else if (((read_control_read_read_fu_324_p2 == 1'd1) & (chip_enable_read_read_fu_312_p2 == 1'd1) & (32'd0 == address_read_read_fu_336_p2))) begin
        ap_phi_mux_data_out_new_0_phi_fu_845_p116 = trunc_ln6_fu_2039_p1;
    end else if (((read_control_read_read_fu_324_p2 == 1'd1) & (chip_enable_read_read_fu_312_p2 == 1'd1) & (32'd4 == address_read_read_fu_336_p2))) begin
        ap_phi_mux_data_out_new_0_phi_fu_845_p116 = {{select_ln132_fu_1108_p3[63:32]}};
    end else if (((read_control_read_read_fu_324_p2 == 1'd1) & (chip_enable_read_read_fu_312_p2 == 1'd1) & (32'd8 == address_read_read_fu_336_p2))) begin
        ap_phi_mux_data_out_new_0_phi_fu_845_p116 = {{select_ln132_fu_1108_p3[95:64]}};
    end else if (((read_control_read_read_fu_324_p2 == 1'd1) & (chip_enable_read_read_fu_312_p2 == 1'd1) & (32'd12 == address_read_read_fu_336_p2))) begin
        ap_phi_mux_data_out_new_0_phi_fu_845_p116 = {{select_ln132_fu_1108_p3[127:96]}};
    end else if (((read_control_read_read_fu_324_p2 == 1'd1) & (chip_enable_read_read_fu_312_p2 == 1'd1) & (32'd16 == address_read_read_fu_336_p2))) begin
        ap_phi_mux_data_out_new_0_phi_fu_845_p116 = {{select_ln132_fu_1108_p3[159:128]}};
    end else if (((read_control_read_read_fu_324_p2 == 1'd1) & (chip_enable_read_read_fu_312_p2 == 1'd1) & (32'd20 == address_read_read_fu_336_p2))) begin
        ap_phi_mux_data_out_new_0_phi_fu_845_p116 = {{select_ln132_fu_1108_p3[191:160]}};
    end else if (((read_control_read_read_fu_324_p2 == 1'd1) & (chip_enable_read_read_fu_312_p2 == 1'd1) & (32'd24 == address_read_read_fu_336_p2))) begin
        ap_phi_mux_data_out_new_0_phi_fu_845_p116 = {{select_ln132_fu_1108_p3[223:192]}};
    end else if (((read_control_read_read_fu_324_p2 == 1'd1) & (chip_enable_read_read_fu_312_p2 == 1'd1) & (32'd28 == address_read_read_fu_336_p2))) begin
        ap_phi_mux_data_out_new_0_phi_fu_845_p116 = {{select_ln132_fu_1108_p3[255:224]}};
    end else if (((read_control_read_read_fu_324_p2 == 1'd1) & (chip_enable_read_read_fu_312_p2 == 1'd1) & (32'd32 == address_read_read_fu_336_p2))) begin
        ap_phi_mux_data_out_new_0_phi_fu_845_p116 = {{select_ln132_fu_1108_p3[287:256]}};
    end else if (((32'd36 == address_read_read_fu_336_p2) & (read_control_read_read_fu_324_p2 == 1'd1) & (chip_enable_read_read_fu_312_p2 == 1'd1))) begin
        ap_phi_mux_data_out_new_0_phi_fu_845_p116 = {{select_ln132_fu_1108_p3[319:288]}};
    end else if (((32'd40 == address_read_read_fu_336_p2) & (read_control_read_read_fu_324_p2 == 1'd1) & (chip_enable_read_read_fu_312_p2 == 1'd1))) begin
        ap_phi_mux_data_out_new_0_phi_fu_845_p116 = {{select_ln132_fu_1108_p3[351:320]}};
    end else if (((32'd44 == address_read_read_fu_336_p2) & (read_control_read_read_fu_324_p2 == 1'd1) & (chip_enable_read_read_fu_312_p2 == 1'd1))) begin
        ap_phi_mux_data_out_new_0_phi_fu_845_p116 = {{select_ln132_fu_1108_p3[383:352]}};
    end else if (((32'd48 == address_read_read_fu_336_p2) & (read_control_read_read_fu_324_p2 == 1'd1) & (chip_enable_read_read_fu_312_p2 == 1'd1))) begin
        ap_phi_mux_data_out_new_0_phi_fu_845_p116 = {{select_ln132_fu_1108_p3[415:384]}};
    end else if (((32'd52 == address_read_read_fu_336_p2) & (read_control_read_read_fu_324_p2 == 1'd1) & (chip_enable_read_read_fu_312_p2 == 1'd1))) begin
        ap_phi_mux_data_out_new_0_phi_fu_845_p116 = {{select_ln132_fu_1108_p3[447:416]}};
    end else if (((32'd56 == address_read_read_fu_336_p2) & (read_control_read_read_fu_324_p2 == 1'd1) & (chip_enable_read_read_fu_312_p2 == 1'd1))) begin
        ap_phi_mux_data_out_new_0_phi_fu_845_p116 = {{select_ln132_fu_1108_p3[479:448]}};
    end else if (((32'd60 == address_read_read_fu_336_p2) & (read_control_read_read_fu_324_p2 == 1'd1) & (chip_enable_read_read_fu_312_p2 == 1'd1))) begin
        ap_phi_mux_data_out_new_0_phi_fu_845_p116 = {{select_ln132_fu_1108_p3[511:480]}};
    end else if (((32'd64 == address_read_read_fu_336_p2) & (read_control_read_read_fu_324_p2 == 1'd1) & (chip_enable_read_read_fu_312_p2 == 1'd1))) begin
        ap_phi_mux_data_out_new_0_phi_fu_845_p116 = {{select_ln132_fu_1108_p3[543:512]}};
    end else if (((32'd68 == address_read_read_fu_336_p2) & (read_control_read_read_fu_324_p2 == 1'd1) & (chip_enable_read_read_fu_312_p2 == 1'd1))) begin
        ap_phi_mux_data_out_new_0_phi_fu_845_p116 = {{select_ln132_fu_1108_p3[575:544]}};
    end else if (((32'd72 == address_read_read_fu_336_p2) & (read_control_read_read_fu_324_p2 == 1'd1) & (chip_enable_read_read_fu_312_p2 == 1'd1))) begin
        ap_phi_mux_data_out_new_0_phi_fu_845_p116 = {{select_ln132_fu_1108_p3[607:576]}};
    end else if (((32'd76 == address_read_read_fu_336_p2) & (read_control_read_read_fu_324_p2 == 1'd1) & (chip_enable_read_read_fu_312_p2 == 1'd1))) begin
        ap_phi_mux_data_out_new_0_phi_fu_845_p116 = {{select_ln132_fu_1108_p3[639:608]}};
    end else if (((32'd80 == address_read_read_fu_336_p2) & (read_control_read_read_fu_324_p2 == 1'd1) & (chip_enable_read_read_fu_312_p2 == 1'd1))) begin
        ap_phi_mux_data_out_new_0_phi_fu_845_p116 = {{select_ln132_fu_1108_p3[671:640]}};
    end else if (((32'd84 == address_read_read_fu_336_p2) & (read_control_read_read_fu_324_p2 == 1'd1) & (chip_enable_read_read_fu_312_p2 == 1'd1))) begin
        ap_phi_mux_data_out_new_0_phi_fu_845_p116 = {{select_ln132_fu_1108_p3[703:672]}};
    end else if (((32'd88 == address_read_read_fu_336_p2) & (read_control_read_read_fu_324_p2 == 1'd1) & (chip_enable_read_read_fu_312_p2 == 1'd1))) begin
        ap_phi_mux_data_out_new_0_phi_fu_845_p116 = {{select_ln132_fu_1108_p3[735:704]}};
    end else if (((32'd92 == address_read_read_fu_336_p2) & (read_control_read_read_fu_324_p2 == 1'd1) & (chip_enable_read_read_fu_312_p2 == 1'd1))) begin
        ap_phi_mux_data_out_new_0_phi_fu_845_p116 = {{select_ln132_fu_1108_p3[767:736]}};
    end else if (((32'd96 == address_read_read_fu_336_p2) & (read_control_read_read_fu_324_p2 == 1'd1) & (chip_enable_read_read_fu_312_p2 == 1'd1))) begin
        ap_phi_mux_data_out_new_0_phi_fu_845_p116 = {{select_ln132_fu_1108_p3[799:768]}};
    end else if (((32'd100 == address_read_read_fu_336_p2) & (read_control_read_read_fu_324_p2 == 1'd1) & (chip_enable_read_read_fu_312_p2 == 1'd1))) begin
        ap_phi_mux_data_out_new_0_phi_fu_845_p116 = {{select_ln132_fu_1108_p3[831:800]}};
    end else if (((32'd104 == address_read_read_fu_336_p2) & (read_control_read_read_fu_324_p2 == 1'd1) & (chip_enable_read_read_fu_312_p2 == 1'd1))) begin
        ap_phi_mux_data_out_new_0_phi_fu_845_p116 = {{select_ln132_fu_1108_p3[863:832]}};
    end else begin
        ap_phi_mux_data_out_new_0_phi_fu_845_p116 = 'bx;
    end
end

always @ (*) begin
    if ((((32'd36 == address_read_read_fu_336_p2) & (read_control_read_read_fu_324_p2 == 1'd0) & (chip_enable_read_read_fu_312_p2 == 1'd1) & (write_control_read_read_fu_318_p2 == 1'd1)) | ((32'd40 == address_read_read_fu_336_p2) & (read_control_read_read_fu_324_p2 == 1'd0) & (chip_enable_read_read_fu_312_p2 == 1'd1) & (write_control_read_read_fu_318_p2 == 1'd1)) | ((32'd44 == address_read_read_fu_336_p2) & (read_control_read_read_fu_324_p2 == 1'd0) & (chip_enable_read_read_fu_312_p2 == 1'd1) & (write_control_read_read_fu_318_p2 == 1'd1)) | ((32'd48 == address_read_read_fu_336_p2) & (read_control_read_read_fu_324_p2 == 1'd0) & (chip_enable_read_read_fu_312_p2 == 1'd1) & (write_control_read_read_fu_318_p2 == 1'd1)) | ((32'd52 == address_read_read_fu_336_p2) & (read_control_read_read_fu_324_p2 == 1'd0) & (chip_enable_read_read_fu_312_p2 == 1'd1) & (write_control_read_read_fu_318_p2 == 1'd1)) | ((32'd56 == address_read_read_fu_336_p2) & (read_control_read_read_fu_324_p2 == 1'd0) & (chip_enable_read_read_fu_312_p2 == 1'd1) 
    & (write_control_read_read_fu_318_p2 == 1'd1)) | ((32'd60 == address_read_read_fu_336_p2) & (read_control_read_read_fu_324_p2 == 1'd0) & (chip_enable_read_read_fu_312_p2 == 1'd1) & (write_control_read_read_fu_318_p2 == 1'd1)) | ((32'd64 == address_read_read_fu_336_p2) & (read_control_read_read_fu_324_p2 == 1'd0) & (chip_enable_read_read_fu_312_p2 == 1'd1) & (write_control_read_read_fu_318_p2 == 1'd1)) | ((32'd68 == address_read_read_fu_336_p2) & (read_control_read_read_fu_324_p2 == 1'd0) & (chip_enable_read_read_fu_312_p2 == 1'd1) & (write_control_read_read_fu_318_p2 == 1'd1)) | ((32'd72 == address_read_read_fu_336_p2) & (read_control_read_read_fu_324_p2 == 1'd0) & (chip_enable_read_read_fu_312_p2 == 1'd1) & (write_control_read_read_fu_318_p2 == 1'd1)) | ((32'd76 == address_read_read_fu_336_p2) & (read_control_read_read_fu_324_p2 == 1'd0) & (chip_enable_read_read_fu_312_p2 == 1'd1) & (write_control_read_read_fu_318_p2 == 1'd1)) | ((32'd80 == address_read_read_fu_336_p2) & (read_control_read_read_fu_324_p2 == 1'd0) 
    & (chip_enable_read_read_fu_312_p2 == 1'd1) & (write_control_read_read_fu_318_p2 == 1'd1)) | ((32'd84 == address_read_read_fu_336_p2) & (read_control_read_read_fu_324_p2 == 1'd0) & (chip_enable_read_read_fu_312_p2 == 1'd1) & (write_control_read_read_fu_318_p2 == 1'd1)) | ((32'd88 == address_read_read_fu_336_p2) & (read_control_read_read_fu_324_p2 == 1'd0) & (chip_enable_read_read_fu_312_p2 == 1'd1) & (write_control_read_read_fu_318_p2 == 1'd1)) | ((32'd92 == address_read_read_fu_336_p2) & (read_control_read_read_fu_324_p2 == 1'd0) & (chip_enable_read_read_fu_312_p2 == 1'd1) & (write_control_read_read_fu_318_p2 == 1'd1)) | ((32'd96 == address_read_read_fu_336_p2) & (read_control_read_read_fu_324_p2 == 1'd0) & (chip_enable_read_read_fu_312_p2 == 1'd1) & (write_control_read_read_fu_318_p2 == 1'd1)) | ((32'd100 == address_read_read_fu_336_p2) & (read_control_read_read_fu_324_p2 == 1'd0) & (chip_enable_read_read_fu_312_p2 == 1'd1) & (write_control_read_read_fu_318_p2 == 1'd1)) | ((32'd104 == address_read_read_fu_336_p2) 
    & (read_control_read_read_fu_324_p2 == 1'd0) & (chip_enable_read_read_fu_312_p2 == 1'd1) & (write_control_read_read_fu_318_p2 == 1'd1)) | ((read_control_read_read_fu_324_p2 == 1'd0) & (chip_enable_read_read_fu_312_p2 == 1'd1) & (write_control_read_read_fu_318_p2 == 1'd1) & (32'd0 == address_read_read_fu_336_p2)) | ((read_control_read_read_fu_324_p2 == 1'd0) & (chip_enable_read_read_fu_312_p2 == 1'd1) & (write_control_read_read_fu_318_p2 == 1'd1) & (32'd4 == address_read_read_fu_336_p2)) | ((read_control_read_read_fu_324_p2 == 1'd0) & (chip_enable_read_read_fu_312_p2 == 1'd1) & (write_control_read_read_fu_318_p2 == 1'd1) & (32'd8 == address_read_read_fu_336_p2)) | ((read_control_read_read_fu_324_p2 == 1'd0) & (chip_enable_read_read_fu_312_p2 == 1'd1) & (write_control_read_read_fu_318_p2 == 1'd1) & (32'd12 == address_read_read_fu_336_p2)) | ((read_control_read_read_fu_324_p2 == 1'd0) & (chip_enable_read_read_fu_312_p2 == 1'd1) & (write_control_read_read_fu_318_p2 == 1'd1) & (32'd16 == address_read_read_fu_336_p2)) 
    | ((read_control_read_read_fu_324_p2 == 1'd0) & (chip_enable_read_read_fu_312_p2 == 1'd1) & (write_control_read_read_fu_318_p2 == 1'd1) & (32'd20 == address_read_read_fu_336_p2)) | ((read_control_read_read_fu_324_p2 == 1'd0) & (chip_enable_read_read_fu_312_p2 == 1'd1) & (write_control_read_read_fu_318_p2 == 1'd1) & (32'd24 == address_read_read_fu_336_p2)) | ((read_control_read_read_fu_324_p2 == 1'd0) & (chip_enable_read_read_fu_312_p2 == 1'd1) & (write_control_read_read_fu_318_p2 == 1'd1) & (32'd28 == address_read_read_fu_336_p2)) | ((read_control_read_read_fu_324_p2 == 1'd0) & (chip_enable_read_read_fu_312_p2 == 1'd1) & (write_control_read_read_fu_318_p2 == 1'd1) & (32'd32 == address_read_read_fu_336_p2)))) begin
        ap_phi_mux_mem_flag_3_phi_fu_365_p116 = 1'd1;
    end else if (((chip_enable_read_read_fu_312_p2 == 1'd0) | ((32'd36 == address_read_read_fu_336_p2) & (read_control_read_read_fu_324_p2 == 1'd1) & (chip_enable_read_read_fu_312_p2 == 1'd1)) | ((32'd40 == address_read_read_fu_336_p2) & (read_control_read_read_fu_324_p2 == 1'd1) & (chip_enable_read_read_fu_312_p2 == 1'd1)) | ((32'd44 == address_read_read_fu_336_p2) & (read_control_read_read_fu_324_p2 == 1'd1) & (chip_enable_read_read_fu_312_p2 == 1'd1)) | ((32'd48 == address_read_read_fu_336_p2) & (read_control_read_read_fu_324_p2 == 1'd1) & (chip_enable_read_read_fu_312_p2 == 1'd1)) | ((32'd52 == address_read_read_fu_336_p2) & (read_control_read_read_fu_324_p2 == 1'd1) & (chip_enable_read_read_fu_312_p2 == 1'd1)) | ((32'd56 == address_read_read_fu_336_p2) & (read_control_read_read_fu_324_p2 == 1'd1) & (chip_enable_read_read_fu_312_p2 == 1'd1)) | ((32'd60 == address_read_read_fu_336_p2) & (read_control_read_read_fu_324_p2 == 1'd1) & (chip_enable_read_read_fu_312_p2 == 1'd1)) | ((32'd64 == address_read_read_fu_336_p2) & (read_control_read_read_fu_324_p2 
    == 1'd1) & (chip_enable_read_read_fu_312_p2 == 1'd1)) | ((32'd68 == address_read_read_fu_336_p2) & (read_control_read_read_fu_324_p2 == 1'd1) & (chip_enable_read_read_fu_312_p2 == 1'd1)) | ((32'd72 == address_read_read_fu_336_p2) & (read_control_read_read_fu_324_p2 == 1'd1) & (chip_enable_read_read_fu_312_p2 == 1'd1)) | ((32'd76 == address_read_read_fu_336_p2) & (read_control_read_read_fu_324_p2 == 1'd1) & (chip_enable_read_read_fu_312_p2 == 1'd1)) | ((32'd80 == address_read_read_fu_336_p2) & (read_control_read_read_fu_324_p2 == 1'd1) & (chip_enable_read_read_fu_312_p2 == 1'd1)) | ((32'd84 == address_read_read_fu_336_p2) & (read_control_read_read_fu_324_p2 == 1'd1) & (chip_enable_read_read_fu_312_p2 == 1'd1)) | ((32'd88 == address_read_read_fu_336_p2) & (read_control_read_read_fu_324_p2 == 1'd1) & (chip_enable_read_read_fu_312_p2 == 1'd1)) | ((32'd92 == address_read_read_fu_336_p2) & (read_control_read_read_fu_324_p2 == 1'd1) & (chip_enable_read_read_fu_312_p2 == 1'd1)) | ((32'd96 == address_read_read_fu_336_p2) 
    & (read_control_read_read_fu_324_p2 == 1'd1) & (chip_enable_read_read_fu_312_p2 == 1'd1)) | ((32'd100 == address_read_read_fu_336_p2) & (read_control_read_read_fu_324_p2 == 1'd1) & (chip_enable_read_read_fu_312_p2 == 1'd1)) | ((32'd104 == address_read_read_fu_336_p2) & (read_control_read_read_fu_324_p2 == 1'd1) & (chip_enable_read_read_fu_312_p2 == 1'd1)) | ((read_control_read_read_fu_324_p2 == 1'd1) & (chip_enable_read_read_fu_312_p2 == 1'd1) & (32'd0 == address_read_read_fu_336_p2)) | ((read_control_read_read_fu_324_p2 == 1'd1) & (chip_enable_read_read_fu_312_p2 == 1'd1) & (32'd4 == address_read_read_fu_336_p2)) | ((read_control_read_read_fu_324_p2 == 1'd1) & (chip_enable_read_read_fu_312_p2 == 1'd1) & (32'd8 == address_read_read_fu_336_p2)) | ((read_control_read_read_fu_324_p2 == 1'd1) & (chip_enable_read_read_fu_312_p2 == 1'd1) & (32'd12 == address_read_read_fu_336_p2)) | ((read_control_read_read_fu_324_p2 == 1'd1) & (chip_enable_read_read_fu_312_p2 == 1'd1) & (32'd16 == address_read_read_fu_336_p2)) | ((read_control_read_read_fu_324_p2 
    == 1'd1) & (chip_enable_read_read_fu_312_p2 == 1'd1) & (32'd20 == address_read_read_fu_336_p2)) | ((read_control_read_read_fu_324_p2 == 1'd1) & (chip_enable_read_read_fu_312_p2 == 1'd1) & (32'd24 == address_read_read_fu_336_p2)) | ((read_control_read_read_fu_324_p2 == 1'd1) & (chip_enable_read_read_fu_312_p2 == 1'd1) & (32'd28 == address_read_read_fu_336_p2)) | ((read_control_read_read_fu_324_p2 == 1'd1) & (chip_enable_read_read_fu_312_p2 == 1'd1) & (32'd32 == address_read_read_fu_336_p2)) | ((read_control_read_read_fu_324_p2 == 1'd0) & (chip_enable_read_read_fu_312_p2 == 1'd1) & (write_control_read_read_fu_318_p2 == 1'd0)) | (~(32'd36 == address_read_read_fu_336_p2) & ~(32'd40 == address_read_read_fu_336_p2) & ~(32'd44 == address_read_read_fu_336_p2) & ~(32'd48 == address_read_read_fu_336_p2) & ~(32'd52 == address_read_read_fu_336_p2) & ~(32'd56 == address_read_read_fu_336_p2) & ~(32'd60 == address_read_read_fu_336_p2) & ~(32'd64 == address_read_read_fu_336_p2) & ~(32'd68 == address_read_read_fu_336_p2) & ~(32'd72 
    == address_read_read_fu_336_p2) & ~(32'd76 == address_read_read_fu_336_p2) & ~(32'd80 == address_read_read_fu_336_p2) & ~(32'd84 == address_read_read_fu_336_p2) & ~(32'd88 == address_read_read_fu_336_p2) & ~(32'd92 == address_read_read_fu_336_p2) & ~(32'd96 == address_read_read_fu_336_p2) & ~(32'd100 == address_read_read_fu_336_p2) & ~(32'd104 == address_read_read_fu_336_p2) & ~(32'd0 == address_read_read_fu_336_p2) & ~(32'd4 == address_read_read_fu_336_p2) & ~(32'd8 == address_read_read_fu_336_p2) & ~(32'd12 == address_read_read_fu_336_p2) & ~(32'd16 == address_read_read_fu_336_p2) & ~(32'd20 == address_read_read_fu_336_p2) & ~(32'd24 == address_read_read_fu_336_p2) & ~(32'd28 == address_read_read_fu_336_p2) & ~(32'd32 == address_read_read_fu_336_p2) & (read_control_read_read_fu_324_p2 == 1'd1) & (chip_enable_read_read_fu_312_p2 == 1'd1)) | (~(32'd36 == address_read_read_fu_336_p2) & ~(32'd40 == address_read_read_fu_336_p2) & ~(32'd44 == address_read_read_fu_336_p2) & ~(32'd48 == address_read_read_fu_336_p2) 
    & ~(32'd52 == address_read_read_fu_336_p2) & ~(32'd56 == address_read_read_fu_336_p2) & ~(32'd60 == address_read_read_fu_336_p2) & ~(32'd64 == address_read_read_fu_336_p2) & ~(32'd68 == address_read_read_fu_336_p2) & ~(32'd72 == address_read_read_fu_336_p2) & ~(32'd76 == address_read_read_fu_336_p2) & ~(32'd80 == address_read_read_fu_336_p2) & ~(32'd84 == address_read_read_fu_336_p2) & ~(32'd88 == address_read_read_fu_336_p2) & ~(32'd92 == address_read_read_fu_336_p2) & ~(32'd96 == address_read_read_fu_336_p2) & ~(32'd100 == address_read_read_fu_336_p2) & ~(32'd104 == address_read_read_fu_336_p2) & ~(32'd0 == address_read_read_fu_336_p2) & ~(32'd4 == address_read_read_fu_336_p2) & ~(32'd8 == address_read_read_fu_336_p2) & ~(32'd12 == address_read_read_fu_336_p2) & ~(32'd16 == address_read_read_fu_336_p2) & ~(32'd20 == address_read_read_fu_336_p2) & ~(32'd24 == address_read_read_fu_336_p2) & ~(32'd28 == address_read_read_fu_336_p2) & ~(32'd32 == address_read_read_fu_336_p2) & (read_control_read_read_fu_324_p2 == 
    1'd0) & (chip_enable_read_read_fu_312_p2 == 1'd1) & (write_control_read_read_fu_318_p2 == 1'd1)))) begin
        ap_phi_mux_mem_flag_3_phi_fu_365_p116 = xor_ln132_fu_1071_p2;
    end else begin
        ap_phi_mux_mem_flag_3_phi_fu_365_p116 = 'bx;
    end
end

always @ (*) begin
    if (((read_control_read_read_fu_324_p2 == 1'd0) & (chip_enable_read_read_fu_312_p2 == 1'd1) & (write_control_read_read_fu_318_p2 == 1'd1) & (32'd0 == address_read_read_fu_336_p2))) begin
        ap_phi_mux_mem_new_3_phi_fu_513_p116 = or_ln_fu_1755_p3;
    end else if (((read_control_read_read_fu_324_p2 == 1'd0) & (chip_enable_read_read_fu_312_p2 == 1'd1) & (write_control_read_read_fu_318_p2 == 1'd1) & (32'd4 == address_read_read_fu_336_p2))) begin
        ap_phi_mux_mem_new_3_phi_fu_513_p116 = or_ln1_fu_1734_p4;
    end else if (((read_control_read_read_fu_324_p2 == 1'd0) & (chip_enable_read_read_fu_312_p2 == 1'd1) & (write_control_read_read_fu_318_p2 == 1'd1) & (32'd8 == address_read_read_fu_336_p2))) begin
        ap_phi_mux_mem_new_3_phi_fu_513_p116 = or_ln2_fu_1709_p4;
    end else if (((read_control_read_read_fu_324_p2 == 1'd0) & (chip_enable_read_read_fu_312_p2 == 1'd1) & (write_control_read_read_fu_318_p2 == 1'd1) & (32'd12 == address_read_read_fu_336_p2))) begin
        ap_phi_mux_mem_new_3_phi_fu_513_p116 = or_ln3_fu_1684_p4;
    end else if (((read_control_read_read_fu_324_p2 == 1'd0) & (chip_enable_read_read_fu_312_p2 == 1'd1) & (write_control_read_read_fu_318_p2 == 1'd1) & (32'd16 == address_read_read_fu_336_p2))) begin
        ap_phi_mux_mem_new_3_phi_fu_513_p116 = or_ln4_fu_1659_p4;
    end else if (((read_control_read_read_fu_324_p2 == 1'd0) & (chip_enable_read_read_fu_312_p2 == 1'd1) & (write_control_read_read_fu_318_p2 == 1'd1) & (32'd20 == address_read_read_fu_336_p2))) begin
        ap_phi_mux_mem_new_3_phi_fu_513_p116 = or_ln5_fu_1634_p4;
    end else if (((read_control_read_read_fu_324_p2 == 1'd0) & (chip_enable_read_read_fu_312_p2 == 1'd1) & (write_control_read_read_fu_318_p2 == 1'd1) & (32'd24 == address_read_read_fu_336_p2))) begin
        ap_phi_mux_mem_new_3_phi_fu_513_p116 = or_ln6_fu_1609_p4;
    end else if (((read_control_read_read_fu_324_p2 == 1'd0) & (chip_enable_read_read_fu_312_p2 == 1'd1) & (write_control_read_read_fu_318_p2 == 1'd1) & (32'd28 == address_read_read_fu_336_p2))) begin
        ap_phi_mux_mem_new_3_phi_fu_513_p116 = or_ln7_fu_1584_p4;
    end else if (((read_control_read_read_fu_324_p2 == 1'd0) & (chip_enable_read_read_fu_312_p2 == 1'd1) & (write_control_read_read_fu_318_p2 == 1'd1) & (32'd32 == address_read_read_fu_336_p2))) begin
        ap_phi_mux_mem_new_3_phi_fu_513_p116 = or_ln8_fu_1559_p4;
    end else if (((32'd36 == address_read_read_fu_336_p2) & (read_control_read_read_fu_324_p2 == 1'd0) & (chip_enable_read_read_fu_312_p2 == 1'd1) & (write_control_read_read_fu_318_p2 == 1'd1))) begin
        ap_phi_mux_mem_new_3_phi_fu_513_p116 = or_ln9_fu_1534_p4;
    end else if (((32'd40 == address_read_read_fu_336_p2) & (read_control_read_read_fu_324_p2 == 1'd0) & (chip_enable_read_read_fu_312_p2 == 1'd1) & (write_control_read_read_fu_318_p2 == 1'd1))) begin
        ap_phi_mux_mem_new_3_phi_fu_513_p116 = or_ln10_fu_1509_p4;
    end else if (((32'd44 == address_read_read_fu_336_p2) & (read_control_read_read_fu_324_p2 == 1'd0) & (chip_enable_read_read_fu_312_p2 == 1'd1) & (write_control_read_read_fu_318_p2 == 1'd1))) begin
        ap_phi_mux_mem_new_3_phi_fu_513_p116 = or_ln11_fu_1484_p4;
    end else if (((32'd48 == address_read_read_fu_336_p2) & (read_control_read_read_fu_324_p2 == 1'd0) & (chip_enable_read_read_fu_312_p2 == 1'd1) & (write_control_read_read_fu_318_p2 == 1'd1))) begin
        ap_phi_mux_mem_new_3_phi_fu_513_p116 = or_ln12_fu_1459_p4;
    end else if (((32'd52 == address_read_read_fu_336_p2) & (read_control_read_read_fu_324_p2 == 1'd0) & (chip_enable_read_read_fu_312_p2 == 1'd1) & (write_control_read_read_fu_318_p2 == 1'd1))) begin
        ap_phi_mux_mem_new_3_phi_fu_513_p116 = or_ln13_fu_1434_p4;
    end else if (((32'd56 == address_read_read_fu_336_p2) & (read_control_read_read_fu_324_p2 == 1'd0) & (chip_enable_read_read_fu_312_p2 == 1'd1) & (write_control_read_read_fu_318_p2 == 1'd1))) begin
        ap_phi_mux_mem_new_3_phi_fu_513_p116 = or_ln14_fu_1409_p4;
    end else if (((32'd60 == address_read_read_fu_336_p2) & (read_control_read_read_fu_324_p2 == 1'd0) & (chip_enable_read_read_fu_312_p2 == 1'd1) & (write_control_read_read_fu_318_p2 == 1'd1))) begin
        ap_phi_mux_mem_new_3_phi_fu_513_p116 = or_ln15_fu_1384_p4;
    end else if (((32'd64 == address_read_read_fu_336_p2) & (read_control_read_read_fu_324_p2 == 1'd0) & (chip_enable_read_read_fu_312_p2 == 1'd1) & (write_control_read_read_fu_318_p2 == 1'd1))) begin
        ap_phi_mux_mem_new_3_phi_fu_513_p116 = or_ln16_fu_1359_p4;
    end else if (((32'd68 == address_read_read_fu_336_p2) & (read_control_read_read_fu_324_p2 == 1'd0) & (chip_enable_read_read_fu_312_p2 == 1'd1) & (write_control_read_read_fu_318_p2 == 1'd1))) begin
        ap_phi_mux_mem_new_3_phi_fu_513_p116 = or_ln17_fu_1334_p4;
    end else if (((32'd72 == address_read_read_fu_336_p2) & (read_control_read_read_fu_324_p2 == 1'd0) & (chip_enable_read_read_fu_312_p2 == 1'd1) & (write_control_read_read_fu_318_p2 == 1'd1))) begin
        ap_phi_mux_mem_new_3_phi_fu_513_p116 = or_ln18_fu_1309_p4;
    end else if (((32'd76 == address_read_read_fu_336_p2) & (read_control_read_read_fu_324_p2 == 1'd0) & (chip_enable_read_read_fu_312_p2 == 1'd1) & (write_control_read_read_fu_318_p2 == 1'd1))) begin
        ap_phi_mux_mem_new_3_phi_fu_513_p116 = or_ln19_fu_1284_p4;
    end else if (((32'd80 == address_read_read_fu_336_p2) & (read_control_read_read_fu_324_p2 == 1'd0) & (chip_enable_read_read_fu_312_p2 == 1'd1) & (write_control_read_read_fu_318_p2 == 1'd1))) begin
        ap_phi_mux_mem_new_3_phi_fu_513_p116 = or_ln20_fu_1259_p4;
    end else if (((32'd84 == address_read_read_fu_336_p2) & (read_control_read_read_fu_324_p2 == 1'd0) & (chip_enable_read_read_fu_312_p2 == 1'd1) & (write_control_read_read_fu_318_p2 == 1'd1))) begin
        ap_phi_mux_mem_new_3_phi_fu_513_p116 = or_ln21_fu_1234_p4;
    end else if (((32'd88 == address_read_read_fu_336_p2) & (read_control_read_read_fu_324_p2 == 1'd0) & (chip_enable_read_read_fu_312_p2 == 1'd1) & (write_control_read_read_fu_318_p2 == 1'd1))) begin
        ap_phi_mux_mem_new_3_phi_fu_513_p116 = or_ln22_fu_1209_p4;
    end else if (((32'd92 == address_read_read_fu_336_p2) & (read_control_read_read_fu_324_p2 == 1'd0) & (chip_enable_read_read_fu_312_p2 == 1'd1) & (write_control_read_read_fu_318_p2 == 1'd1))) begin
        ap_phi_mux_mem_new_3_phi_fu_513_p116 = or_ln23_fu_1184_p4;
    end else if (((32'd96 == address_read_read_fu_336_p2) & (read_control_read_read_fu_324_p2 == 1'd0) & (chip_enable_read_read_fu_312_p2 == 1'd1) & (write_control_read_read_fu_318_p2 == 1'd1))) begin
        ap_phi_mux_mem_new_3_phi_fu_513_p116 = or_ln24_fu_1159_p4;
    end else if (((32'd100 == address_read_read_fu_336_p2) & (read_control_read_read_fu_324_p2 == 1'd0) & (chip_enable_read_read_fu_312_p2 == 1'd1) & (write_control_read_read_fu_318_p2 == 1'd1))) begin
        ap_phi_mux_mem_new_3_phi_fu_513_p116 = or_ln25_fu_1134_p4;
    end else if (((32'd104 == address_read_read_fu_336_p2) & (read_control_read_read_fu_324_p2 == 1'd0) & (chip_enable_read_read_fu_312_p2 == 1'd1) & (write_control_read_read_fu_318_p2 == 1'd1))) begin
        ap_phi_mux_mem_new_3_phi_fu_513_p116 = or_ln26_fu_1121_p3;
    end else if (((chip_enable_read_read_fu_312_p2 == 1'd0) | ((32'd36 == address_read_read_fu_336_p2) & (read_control_read_read_fu_324_p2 == 1'd1) & (chip_enable_read_read_fu_312_p2 == 1'd1)) | ((32'd40 == address_read_read_fu_336_p2) & (read_control_read_read_fu_324_p2 == 1'd1) & (chip_enable_read_read_fu_312_p2 == 1'd1)) | ((32'd44 == address_read_read_fu_336_p2) & (read_control_read_read_fu_324_p2 == 1'd1) & (chip_enable_read_read_fu_312_p2 == 1'd1)) | ((32'd48 == address_read_read_fu_336_p2) & (read_control_read_read_fu_324_p2 == 1'd1) & (chip_enable_read_read_fu_312_p2 == 1'd1)) | ((32'd52 == address_read_read_fu_336_p2) & (read_control_read_read_fu_324_p2 == 1'd1) & (chip_enable_read_read_fu_312_p2 == 1'd1)) | ((32'd56 == address_read_read_fu_336_p2) & (read_control_read_read_fu_324_p2 == 1'd1) & (chip_enable_read_read_fu_312_p2 == 1'd1)) | ((32'd60 == address_read_read_fu_336_p2) & (read_control_read_read_fu_324_p2 == 1'd1) & (chip_enable_read_read_fu_312_p2 == 1'd1)) | ((32'd64 == address_read_read_fu_336_p2) & (read_control_read_read_fu_324_p2 
    == 1'd1) & (chip_enable_read_read_fu_312_p2 == 1'd1)) | ((32'd68 == address_read_read_fu_336_p2) & (read_control_read_read_fu_324_p2 == 1'd1) & (chip_enable_read_read_fu_312_p2 == 1'd1)) | ((32'd72 == address_read_read_fu_336_p2) & (read_control_read_read_fu_324_p2 == 1'd1) & (chip_enable_read_read_fu_312_p2 == 1'd1)) | ((32'd76 == address_read_read_fu_336_p2) & (read_control_read_read_fu_324_p2 == 1'd1) & (chip_enable_read_read_fu_312_p2 == 1'd1)) | ((32'd80 == address_read_read_fu_336_p2) & (read_control_read_read_fu_324_p2 == 1'd1) & (chip_enable_read_read_fu_312_p2 == 1'd1)) | ((32'd84 == address_read_read_fu_336_p2) & (read_control_read_read_fu_324_p2 == 1'd1) & (chip_enable_read_read_fu_312_p2 == 1'd1)) | ((32'd88 == address_read_read_fu_336_p2) & (read_control_read_read_fu_324_p2 == 1'd1) & (chip_enable_read_read_fu_312_p2 == 1'd1)) | ((32'd92 == address_read_read_fu_336_p2) & (read_control_read_read_fu_324_p2 == 1'd1) & (chip_enable_read_read_fu_312_p2 == 1'd1)) | ((32'd96 == address_read_read_fu_336_p2) 
    & (read_control_read_read_fu_324_p2 == 1'd1) & (chip_enable_read_read_fu_312_p2 == 1'd1)) | ((32'd100 == address_read_read_fu_336_p2) & (read_control_read_read_fu_324_p2 == 1'd1) & (chip_enable_read_read_fu_312_p2 == 1'd1)) | ((32'd104 == address_read_read_fu_336_p2) & (read_control_read_read_fu_324_p2 == 1'd1) & (chip_enable_read_read_fu_312_p2 == 1'd1)) | ((read_control_read_read_fu_324_p2 == 1'd1) & (chip_enable_read_read_fu_312_p2 == 1'd1) & (32'd0 == address_read_read_fu_336_p2)) | ((read_control_read_read_fu_324_p2 == 1'd1) & (chip_enable_read_read_fu_312_p2 == 1'd1) & (32'd4 == address_read_read_fu_336_p2)) | ((read_control_read_read_fu_324_p2 == 1'd1) & (chip_enable_read_read_fu_312_p2 == 1'd1) & (32'd8 == address_read_read_fu_336_p2)) | ((read_control_read_read_fu_324_p2 == 1'd1) & (chip_enable_read_read_fu_312_p2 == 1'd1) & (32'd12 == address_read_read_fu_336_p2)) | ((read_control_read_read_fu_324_p2 == 1'd1) & (chip_enable_read_read_fu_312_p2 == 1'd1) & (32'd16 == address_read_read_fu_336_p2)) | ((read_control_read_read_fu_324_p2 
    == 1'd1) & (chip_enable_read_read_fu_312_p2 == 1'd1) & (32'd20 == address_read_read_fu_336_p2)) | ((read_control_read_read_fu_324_p2 == 1'd1) & (chip_enable_read_read_fu_312_p2 == 1'd1) & (32'd24 == address_read_read_fu_336_p2)) | ((read_control_read_read_fu_324_p2 == 1'd1) & (chip_enable_read_read_fu_312_p2 == 1'd1) & (32'd28 == address_read_read_fu_336_p2)) | ((read_control_read_read_fu_324_p2 == 1'd1) & (chip_enable_read_read_fu_312_p2 == 1'd1) & (32'd32 == address_read_read_fu_336_p2)) | ((read_control_read_read_fu_324_p2 == 1'd0) & (chip_enable_read_read_fu_312_p2 == 1'd1) & (write_control_read_read_fu_318_p2 == 1'd0)) | (~(32'd36 == address_read_read_fu_336_p2) & ~(32'd40 == address_read_read_fu_336_p2) & ~(32'd44 == address_read_read_fu_336_p2) & ~(32'd48 == address_read_read_fu_336_p2) & ~(32'd52 == address_read_read_fu_336_p2) & ~(32'd56 == address_read_read_fu_336_p2) & ~(32'd60 == address_read_read_fu_336_p2) & ~(32'd64 == address_read_read_fu_336_p2) & ~(32'd68 == address_read_read_fu_336_p2) & ~(32'd72 
    == address_read_read_fu_336_p2) & ~(32'd76 == address_read_read_fu_336_p2) & ~(32'd80 == address_read_read_fu_336_p2) & ~(32'd84 == address_read_read_fu_336_p2) & ~(32'd88 == address_read_read_fu_336_p2) & ~(32'd92 == address_read_read_fu_336_p2) & ~(32'd96 == address_read_read_fu_336_p2) & ~(32'd100 == address_read_read_fu_336_p2) & ~(32'd104 == address_read_read_fu_336_p2) & ~(32'd0 == address_read_read_fu_336_p2) & ~(32'd4 == address_read_read_fu_336_p2) & ~(32'd8 == address_read_read_fu_336_p2) & ~(32'd12 == address_read_read_fu_336_p2) & ~(32'd16 == address_read_read_fu_336_p2) & ~(32'd20 == address_read_read_fu_336_p2) & ~(32'd24 == address_read_read_fu_336_p2) & ~(32'd28 == address_read_read_fu_336_p2) & ~(32'd32 == address_read_read_fu_336_p2) & (read_control_read_read_fu_324_p2 == 1'd1) & (chip_enable_read_read_fu_312_p2 == 1'd1)) | (~(32'd36 == address_read_read_fu_336_p2) & ~(32'd40 == address_read_read_fu_336_p2) & ~(32'd44 == address_read_read_fu_336_p2) & ~(32'd48 == address_read_read_fu_336_p2) 
    & ~(32'd52 == address_read_read_fu_336_p2) & ~(32'd56 == address_read_read_fu_336_p2) & ~(32'd60 == address_read_read_fu_336_p2) & ~(32'd64 == address_read_read_fu_336_p2) & ~(32'd68 == address_read_read_fu_336_p2) & ~(32'd72 == address_read_read_fu_336_p2) & ~(32'd76 == address_read_read_fu_336_p2) & ~(32'd80 == address_read_read_fu_336_p2) & ~(32'd84 == address_read_read_fu_336_p2) & ~(32'd88 == address_read_read_fu_336_p2) & ~(32'd92 == address_read_read_fu_336_p2) & ~(32'd96 == address_read_read_fu_336_p2) & ~(32'd100 == address_read_read_fu_336_p2) & ~(32'd104 == address_read_read_fu_336_p2) & ~(32'd0 == address_read_read_fu_336_p2) & ~(32'd4 == address_read_read_fu_336_p2) & ~(32'd8 == address_read_read_fu_336_p2) & ~(32'd12 == address_read_read_fu_336_p2) & ~(32'd16 == address_read_read_fu_336_p2) & ~(32'd20 == address_read_read_fu_336_p2) & ~(32'd24 == address_read_read_fu_336_p2) & ~(32'd28 == address_read_read_fu_336_p2) & ~(32'd32 == address_read_read_fu_336_p2) & (read_control_read_read_fu_324_p2 == 
    1'd0) & (chip_enable_read_read_fu_312_p2 == 1'd1) & (write_control_read_read_fu_318_p2 == 1'd1)))) begin
        ap_phi_mux_mem_new_3_phi_fu_513_p116 = 864'd5104235503814076951950619111476523171842;
    end else begin
        ap_phi_mux_mem_new_3_phi_fu_513_p116 = 'bx;
    end
end

always @ (*) begin
    if (((ap_phi_mux_data_out_flag_0_phi_fu_666_p116 == 1'd1) & (ap_start == 1'b1))) begin
        data_out_ap_vld = 1'b1;
    end else begin
        data_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b1) & (ap_phi_mux_mem_flag_3_phi_fu_365_p116 == 1'd1))) begin
        mem_o = ap_phi_mux_mem_new_3_phi_fu_513_p116;
    end else begin
        mem_o = mem_i;
    end
end

always @ (*) begin
    if (((ap_start == 1'b1) & (ap_phi_mux_mem_flag_3_phi_fu_365_p116 == 1'd1))) begin
        mem_o_ap_vld = 1'b1;
    end else begin
        mem_o_ap_vld = 1'b0;
    end
end

assign address_read_read_fu_336_p2 = address;

assign ap_done = ap_start;

assign ap_idle = 1'b1;

assign ap_ready = ap_start;

assign chip_enable_read_read_fu_312_p2 = chip_enable;

assign data_out = ap_phi_mux_data_out_new_0_phi_fu_845_p116;

assign grp_fu_1061_p4 = {{select_ln132_fu_1108_p3[863:832]}};

assign or_ln10_fu_1509_p4 = {{{tmp_8_fu_1495_p4}, {data_in}}, {trunc_ln57_fu_1505_p1}};

assign or_ln11_fu_1484_p4 = {{{tmp_10_fu_1470_p4}, {data_in}}, {trunc_ln59_fu_1480_p1}};

assign or_ln12_fu_1459_p4 = {{{tmp_11_fu_1445_p4}, {data_in}}, {trunc_ln60_fu_1455_p1}};

assign or_ln13_fu_1434_p4 = {{{tmp_12_fu_1420_p4}, {data_in}}, {trunc_ln61_fu_1430_p1}};

assign or_ln14_fu_1409_p4 = {{{tmp_13_fu_1395_p4}, {data_in}}, {trunc_ln62_fu_1405_p1}};

assign or_ln15_fu_1384_p4 = {{{tmp_14_fu_1370_p4}, {data_in}}, {trunc_ln63_fu_1380_p1}};

assign or_ln16_fu_1359_p4 = {{{tmp_15_fu_1345_p4}, {data_in}}, {trunc_ln64_fu_1355_p1}};

assign or_ln17_fu_1334_p4 = {{{tmp_16_fu_1320_p4}, {data_in}}, {trunc_ln66_fu_1330_p1}};

assign or_ln18_fu_1309_p4 = {{{tmp_17_fu_1295_p4}, {data_in}}, {trunc_ln67_fu_1305_p1}};

assign or_ln19_fu_1284_p4 = {{{tmp_18_fu_1270_p4}, {data_in}}, {trunc_ln69_fu_1280_p1}};

assign or_ln1_fu_1734_p4 = {{{tmp_1_fu_1720_p4}, {data_in}}, {trunc_ln46_fu_1730_p1}};

assign or_ln20_fu_1259_p4 = {{{tmp_19_fu_1245_p4}, {data_in}}, {trunc_ln70_fu_1255_p1}};

assign or_ln21_fu_1234_p4 = {{{tmp_20_fu_1220_p4}, {data_in}}, {trunc_ln71_fu_1230_p1}};

assign or_ln22_fu_1209_p4 = {{{tmp_21_fu_1195_p4}, {data_in}}, {trunc_ln72_fu_1205_p1}};

assign or_ln23_fu_1184_p4 = {{{tmp_22_fu_1170_p4}, {data_in}}, {trunc_ln73_fu_1180_p1}};

assign or_ln24_fu_1159_p4 = {{{tmp_23_fu_1145_p4}, {data_in}}, {trunc_ln74_fu_1155_p1}};

assign or_ln25_fu_1134_p4 = {{{grp_fu_1061_p4}, {data_in}}, {trunc_ln75_fu_1130_p1}};

assign or_ln26_fu_1121_p3 = {{data_in}, {trunc_ln133_fu_1117_p1}};

assign or_ln2_fu_1709_p4 = {{{tmp_3_fu_1695_p4}, {data_in}}, {trunc_ln47_fu_1705_p1}};

assign or_ln3_fu_1684_p4 = {{{tmp_5_fu_1670_p4}, {data_in}}, {trunc_ln48_fu_1680_p1}};

assign or_ln4_fu_1659_p4 = {{{tmp_7_fu_1645_p4}, {data_in}}, {trunc_ln49_fu_1655_p1}};

assign or_ln5_fu_1634_p4 = {{{tmp_9_fu_1620_p4}, {data_in}}, {trunc_ln51_fu_1630_p1}};

assign or_ln6_fu_1609_p4 = {{{tmp_s_fu_1595_p4}, {data_in}}, {trunc_ln52_fu_1605_p1}};

assign or_ln7_fu_1584_p4 = {{{tmp_2_fu_1570_p4}, {data_in}}, {trunc_ln53_fu_1580_p1}};

assign or_ln8_fu_1559_p4 = {{{tmp_4_fu_1545_p4}, {data_in}}, {trunc_ln55_fu_1555_p1}};

assign or_ln9_fu_1534_p4 = {{{tmp_6_fu_1520_p4}, {data_in}}, {trunc_ln56_fu_1530_p1}};

assign or_ln_fu_1755_p3 = {{tmp_fu_1745_p4}, {data_in}};

assign read_control_read_read_fu_324_p2 = read_control;

assign select_ln132_fu_1108_p3 = ((reset_n[0:0] == 1'b1) ? mem_i : 864'd5104235503814076951950619111476523171842);

assign tmp_10_fu_1470_p4 = {{select_ln132_fu_1108_p3[863:384]}};

assign tmp_11_fu_1445_p4 = {{select_ln132_fu_1108_p3[863:416]}};

assign tmp_12_fu_1420_p4 = {{select_ln132_fu_1108_p3[863:448]}};

assign tmp_13_fu_1395_p4 = {{select_ln132_fu_1108_p3[863:480]}};

assign tmp_14_fu_1370_p4 = {{select_ln132_fu_1108_p3[863:512]}};

assign tmp_15_fu_1345_p4 = {{select_ln132_fu_1108_p3[863:544]}};

assign tmp_16_fu_1320_p4 = {{select_ln132_fu_1108_p3[863:576]}};

assign tmp_17_fu_1295_p4 = {{select_ln132_fu_1108_p3[863:608]}};

assign tmp_18_fu_1270_p4 = {{select_ln132_fu_1108_p3[863:640]}};

assign tmp_19_fu_1245_p4 = {{select_ln132_fu_1108_p3[863:672]}};

assign tmp_1_fu_1720_p4 = {{select_ln132_fu_1108_p3[863:64]}};

assign tmp_20_fu_1220_p4 = {{select_ln132_fu_1108_p3[863:704]}};

assign tmp_21_fu_1195_p4 = {{select_ln132_fu_1108_p3[863:736]}};

assign tmp_22_fu_1170_p4 = {{select_ln132_fu_1108_p3[863:768]}};

assign tmp_23_fu_1145_p4 = {{select_ln132_fu_1108_p3[863:800]}};

assign tmp_2_fu_1570_p4 = {{select_ln132_fu_1108_p3[863:256]}};

assign tmp_3_fu_1695_p4 = {{select_ln132_fu_1108_p3[863:96]}};

assign tmp_4_fu_1545_p4 = {{select_ln132_fu_1108_p3[863:288]}};

assign tmp_5_fu_1670_p4 = {{select_ln132_fu_1108_p3[863:128]}};

assign tmp_6_fu_1520_p4 = {{select_ln132_fu_1108_p3[863:320]}};

assign tmp_7_fu_1645_p4 = {{select_ln132_fu_1108_p3[863:160]}};

assign tmp_8_fu_1495_p4 = {{select_ln132_fu_1108_p3[863:352]}};

assign tmp_9_fu_1620_p4 = {{select_ln132_fu_1108_p3[863:192]}};

assign tmp_fu_1745_p4 = {{select_ln132_fu_1108_p3[863:32]}};

assign tmp_s_fu_1595_p4 = {{select_ln132_fu_1108_p3[863:224]}};

assign trunc_ln133_fu_1117_p1 = select_ln132_fu_1108_p3[831:0];

assign trunc_ln46_fu_1730_p1 = select_ln132_fu_1108_p3[31:0];

assign trunc_ln47_fu_1705_p1 = select_ln132_fu_1108_p3[63:0];

assign trunc_ln48_fu_1680_p1 = select_ln132_fu_1108_p3[95:0];

assign trunc_ln49_fu_1655_p1 = select_ln132_fu_1108_p3[127:0];

assign trunc_ln51_fu_1630_p1 = select_ln132_fu_1108_p3[159:0];

assign trunc_ln52_fu_1605_p1 = select_ln132_fu_1108_p3[191:0];

assign trunc_ln53_fu_1580_p1 = select_ln132_fu_1108_p3[223:0];

assign trunc_ln55_fu_1555_p1 = select_ln132_fu_1108_p3[255:0];

assign trunc_ln56_fu_1530_p1 = select_ln132_fu_1108_p3[287:0];

assign trunc_ln57_fu_1505_p1 = select_ln132_fu_1108_p3[319:0];

assign trunc_ln59_fu_1480_p1 = select_ln132_fu_1108_p3[351:0];

assign trunc_ln60_fu_1455_p1 = select_ln132_fu_1108_p3[383:0];

assign trunc_ln61_fu_1430_p1 = select_ln132_fu_1108_p3[415:0];

assign trunc_ln62_fu_1405_p1 = select_ln132_fu_1108_p3[447:0];

assign trunc_ln63_fu_1380_p1 = select_ln132_fu_1108_p3[479:0];

assign trunc_ln64_fu_1355_p1 = select_ln132_fu_1108_p3[511:0];

assign trunc_ln66_fu_1330_p1 = select_ln132_fu_1108_p3[543:0];

assign trunc_ln67_fu_1305_p1 = select_ln132_fu_1108_p3[575:0];

assign trunc_ln69_fu_1280_p1 = select_ln132_fu_1108_p3[607:0];

assign trunc_ln6_fu_2039_p1 = select_ln132_fu_1108_p3[31:0];

assign trunc_ln70_fu_1255_p1 = select_ln132_fu_1108_p3[639:0];

assign trunc_ln71_fu_1230_p1 = select_ln132_fu_1108_p3[671:0];

assign trunc_ln72_fu_1205_p1 = select_ln132_fu_1108_p3[703:0];

assign trunc_ln73_fu_1180_p1 = select_ln132_fu_1108_p3[735:0];

assign trunc_ln74_fu_1155_p1 = select_ln132_fu_1108_p3[767:0];

assign trunc_ln75_fu_1130_p1 = select_ln132_fu_1108_p3[799:0];

assign write_control_read_read_fu_318_p2 = write_control;

assign xor_ln132_fu_1071_p2 = (reset_n ^ 1'd1);

endmodule //ControlMemInterface
