// ==============================================================
// Generated by Vitis HLS v2025.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="run_single_head_run_single_head,hls_ip_2025_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xck26-sfvc784-2LV-c,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=3.819500,HLS_SYN_LAT=0,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=0,HLS_SYN_LUT=232,HLS_VERSION=2025_1}" *)

module run_single_head (
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        ctx_i,
        ctx_o,
        ctx_o_ap_vld,
        head_idx,
        layer_idx,
        ap_return,
        ap_rst
);


input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [76:0] ctx_i;
output  [76:0] ctx_o;
output   ctx_o_ap_vld;
input  [31:0] head_idx;
input  [31:0] layer_idx;
output  [0:0] ap_return;
input   ap_rst;

reg ctx_o_ap_vld;

wire   [43:0] or_ln_fu_346_p4;
reg   [43:0] ap_phi_mux_ctx_new_0_phi_fu_94_p6;
wire   [0:0] tmp_1_fu_316_p3;
wire   [0:0] tmp_3_fu_324_p3;
wire   [43:0] select_ln27_fu_306_p3;
reg   [0:0] ap_phi_mux_empty_phi_fu_105_p6;
wire   [46:0] zext_ln38_fu_357_p1;
reg   [46:0] ap_phi_mux_ctx_new_1_phi_fu_119_p26;
wire   [7:0] trunc_ln3_fu_368_p4;
wire   [46:0] zext_ln73_fu_431_p1;
wire   [0:0] grp_fu_262_p3;
wire  signed [46:0] sext_ln69_fu_408_p1;
wire   [0:0] grp_fu_244_p3;
wire   [46:0] zext_ln61_fu_471_p1;
wire   [46:0] or_ln4_fu_440_p5;
wire   [46:0] zext_ln49_fu_519_p1;
wire   [46:0] zext_ln45_fu_496_p1;
reg   [0:0] ap_phi_mux_empty_6_phi_fu_150_p26;
reg   [7:0] ap_phi_mux_empty_7_phi_fu_194_p26;
wire   [0:0] xor_ln80_fu_535_p2;
reg   [0:0] ap_phi_mux_finished_phi_fu_237_p4;
wire   [0:0] icmp_ln80_fu_529_p2;
wire   [31:0] trunc_ln27_fu_292_p1;
wire   [0:0] icmp_ln27_fu_296_p2;
wire   [43:0] zext_ln27_fu_302_p1;
wire   [43:0] trunc_ln23_fu_288_p1;
wire   [1:0] tmp_fu_332_p4;
wire   [39:0] trunc_ln33_fu_342_p1;
wire   [2:0] grp_fu_252_p4;
wire   [39:0] trunc_ln68_fu_392_p1;
wire   [44:0] or_ln6_fu_396_p5;
wire   [1:0] grp_fu_270_p4;
wire   [0:0] grp_fu_280_p3;
wire   [31:0] trunc_ln71_fu_413_p1;
wire   [43:0] or_ln5_fu_417_p6;
wire   [39:0] trunc_ln56_fu_436_p1;
wire   [31:0] trunc_ln59_fu_453_p1;
wire   [43:0] or_ln3_fu_457_p6;
wire   [39:0] trunc_ln44_fu_476_p1;
wire   [44:0] or_ln2_fu_480_p5;
wire  signed [45:0] sext_ln45_fu_492_p1;
wire   [31:0] trunc_ln47_fu_501_p1;
wire   [43:0] or_ln1_fu_505_p6;
wire    ap_ce_reg;

always @ (*) begin
    if (((tmp_1_fu_316_p3 == 1'd0) | ((tmp_3_fu_324_p3 == 1'd0) & (tmp_1_fu_316_p3 == 1'd1)))) begin
        ap_phi_mux_ctx_new_0_phi_fu_94_p6 = select_ln27_fu_306_p3;
    end else if (((tmp_3_fu_324_p3 == 1'd1) & (tmp_1_fu_316_p3 == 1'd1))) begin
        ap_phi_mux_ctx_new_0_phi_fu_94_p6 = or_ln_fu_346_p4;
    end else begin
        ap_phi_mux_ctx_new_0_phi_fu_94_p6 = 'bx;
    end
end

always @ (*) begin
    if (((grp_fu_244_p3 == 1'd1) & (trunc_ln3_fu_368_p4 == 8'd0) & (ap_phi_mux_empty_phi_fu_105_p6 == 1'd0))) begin
        ap_phi_mux_ctx_new_1_phi_fu_119_p26 = zext_ln45_fu_496_p1;
    end else if (((grp_fu_262_p3 == 1'd1) & (trunc_ln3_fu_368_p4 == 8'd0) & (ap_phi_mux_empty_phi_fu_105_p6 == 1'd1))) begin
        ap_phi_mux_ctx_new_1_phi_fu_119_p26 = zext_ln49_fu_519_p1;
    end else if (((grp_fu_244_p3 == 1'd1) & (trunc_ln3_fu_368_p4 == 8'd1) & (ap_phi_mux_empty_phi_fu_105_p6 == 1'd0))) begin
        ap_phi_mux_ctx_new_1_phi_fu_119_p26 = or_ln4_fu_440_p5;
    end else if (((grp_fu_262_p3 == 1'd1) & (trunc_ln3_fu_368_p4 == 8'd1) & (ap_phi_mux_empty_phi_fu_105_p6 == 1'd1))) begin
        ap_phi_mux_ctx_new_1_phi_fu_119_p26 = zext_ln61_fu_471_p1;
    end else if (((grp_fu_244_p3 == 1'd1) & (trunc_ln3_fu_368_p4 == 8'd4) & (ap_phi_mux_empty_phi_fu_105_p6 == 1'd0))) begin
        ap_phi_mux_ctx_new_1_phi_fu_119_p26 = sext_ln69_fu_408_p1;
    end else if (((grp_fu_262_p3 == 1'd1) & (trunc_ln3_fu_368_p4 == 8'd4) & (ap_phi_mux_empty_phi_fu_105_p6 == 1'd1))) begin
        ap_phi_mux_ctx_new_1_phi_fu_119_p26 = zext_ln73_fu_431_p1;
    end else if ((((grp_fu_244_p3 == 1'd0) & (trunc_ln3_fu_368_p4 == 8'd4) & (ap_phi_mux_empty_phi_fu_105_p6 == 1'd0)) | ((grp_fu_244_p3 == 1'd0) & (trunc_ln3_fu_368_p4 == 8'd1) & (ap_phi_mux_empty_phi_fu_105_p6 == 1'd0)) | ((grp_fu_244_p3 == 1'd0) & (trunc_ln3_fu_368_p4 == 8'd0) & (ap_phi_mux_empty_phi_fu_105_p6 == 1'd0)) | ((grp_fu_262_p3 == 1'd0) & (trunc_ln3_fu_368_p4 == 8'd4) & (ap_phi_mux_empty_phi_fu_105_p6 == 1'd1)) | ((grp_fu_262_p3 == 1'd0) & (trunc_ln3_fu_368_p4 == 8'd1) & (ap_phi_mux_empty_phi_fu_105_p6 == 1'd1)) | ((grp_fu_262_p3 == 1'd0) & (trunc_ln3_fu_368_p4 == 8'd0) & (ap_phi_mux_empty_phi_fu_105_p6 == 1'd1)) | (~(trunc_ln3_fu_368_p4 == 8'd4) & ~(trunc_ln3_fu_368_p4 == 8'd1) & ~(trunc_ln3_fu_368_p4 == 8'd0)))) begin
        ap_phi_mux_ctx_new_1_phi_fu_119_p26 = zext_ln38_fu_357_p1;
    end else begin
        ap_phi_mux_ctx_new_1_phi_fu_119_p26 = 'bx;
    end
end

always @ (*) begin
    if ((((grp_fu_244_p3 == 1'd0) & (trunc_ln3_fu_368_p4 == 8'd4) & (ap_phi_mux_empty_phi_fu_105_p6 == 1'd0)) | ((grp_fu_244_p3 == 1'd0) & (trunc_ln3_fu_368_p4 == 8'd1) & (ap_phi_mux_empty_phi_fu_105_p6 == 1'd0)) | ((grp_fu_244_p3 == 1'd0) & (trunc_ln3_fu_368_p4 == 8'd0) & (ap_phi_mux_empty_phi_fu_105_p6 == 1'd0)))) begin
        ap_phi_mux_empty_6_phi_fu_150_p26 = 1'd0;
    end else if ((((grp_fu_244_p3 == 1'd1) & (trunc_ln3_fu_368_p4 == 8'd4) & (ap_phi_mux_empty_phi_fu_105_p6 == 1'd0)) | ((grp_fu_244_p3 == 1'd1) & (trunc_ln3_fu_368_p4 == 8'd1) & (ap_phi_mux_empty_phi_fu_105_p6 == 1'd0)) | ((grp_fu_244_p3 == 1'd1) & (trunc_ln3_fu_368_p4 == 8'd0) & (ap_phi_mux_empty_phi_fu_105_p6 == 1'd0)) | ((grp_fu_262_p3 == 1'd0) & (trunc_ln3_fu_368_p4 == 8'd4) & (ap_phi_mux_empty_phi_fu_105_p6 == 1'd1)) | ((grp_fu_262_p3 == 1'd0) & (trunc_ln3_fu_368_p4 == 8'd1) & (ap_phi_mux_empty_phi_fu_105_p6 == 1'd1)) | ((grp_fu_262_p3 == 1'd0) & (trunc_ln3_fu_368_p4 == 8'd0) & (ap_phi_mux_empty_phi_fu_105_p6 == 1'd1)) | ((grp_fu_262_p3 == 1'd1) & (trunc_ln3_fu_368_p4 == 8'd4) & (ap_phi_mux_empty_phi_fu_105_p6 == 1'd1)) | ((grp_fu_262_p3 == 1'd1) & (trunc_ln3_fu_368_p4 == 8'd1) & (ap_phi_mux_empty_phi_fu_105_p6 == 1'd1)) | ((grp_fu_262_p3 == 1'd1) & (trunc_ln3_fu_368_p4 == 8'd0) & (ap_phi_mux_empty_phi_fu_105_p6 == 1'd1)))) begin
        ap_phi_mux_empty_6_phi_fu_150_p26 = 1'd1;
    end else if ((~(trunc_ln3_fu_368_p4 == 8'd4) & ~(trunc_ln3_fu_368_p4 == 8'd1) & ~(trunc_ln3_fu_368_p4 == 8'd0))) begin
        ap_phi_mux_empty_6_phi_fu_150_p26 = ap_phi_mux_empty_phi_fu_105_p6;
    end else begin
        ap_phi_mux_empty_6_phi_fu_150_p26 = 'bx;
    end
end

always @ (*) begin
    if ((((grp_fu_244_p3 == 1'd0) & (trunc_ln3_fu_368_p4 == 8'd0) & (ap_phi_mux_empty_phi_fu_105_p6 == 1'd0)) | ((grp_fu_244_p3 == 1'd1) & (trunc_ln3_fu_368_p4 == 8'd0) & (ap_phi_mux_empty_phi_fu_105_p6 == 1'd0)) | ((grp_fu_262_p3 == 1'd0) & (trunc_ln3_fu_368_p4 == 8'd0) & (ap_phi_mux_empty_phi_fu_105_p6 == 1'd1)))) begin
        ap_phi_mux_empty_7_phi_fu_194_p26 = 8'd0;
    end else if ((((grp_fu_244_p3 == 1'd0) & (trunc_ln3_fu_368_p4 == 8'd1) & (ap_phi_mux_empty_phi_fu_105_p6 == 1'd0)) | ((grp_fu_244_p3 == 1'd1) & (trunc_ln3_fu_368_p4 == 8'd1) & (ap_phi_mux_empty_phi_fu_105_p6 == 1'd0)) | ((grp_fu_262_p3 == 1'd0) & (trunc_ln3_fu_368_p4 == 8'd1) & (ap_phi_mux_empty_phi_fu_105_p6 == 1'd1)) | ((grp_fu_262_p3 == 1'd1) & (trunc_ln3_fu_368_p4 == 8'd0) & (ap_phi_mux_empty_phi_fu_105_p6 == 1'd1)))) begin
        ap_phi_mux_empty_7_phi_fu_194_p26 = 8'd1;
    end else if ((((grp_fu_244_p3 == 1'd0) & (trunc_ln3_fu_368_p4 == 8'd4) & (ap_phi_mux_empty_phi_fu_105_p6 == 1'd0)) | ((grp_fu_244_p3 == 1'd1) & (trunc_ln3_fu_368_p4 == 8'd4) & (ap_phi_mux_empty_phi_fu_105_p6 == 1'd0)) | ((grp_fu_262_p3 == 1'd0) & (trunc_ln3_fu_368_p4 == 8'd4) & (ap_phi_mux_empty_phi_fu_105_p6 == 1'd1)) | ((grp_fu_262_p3 == 1'd1) & (trunc_ln3_fu_368_p4 == 8'd1) & (ap_phi_mux_empty_phi_fu_105_p6 == 1'd1)))) begin
        ap_phi_mux_empty_7_phi_fu_194_p26 = 8'd4;
    end else if (((grp_fu_262_p3 == 1'd1) & (trunc_ln3_fu_368_p4 == 8'd4) & (ap_phi_mux_empty_phi_fu_105_p6 == 1'd1))) begin
        ap_phi_mux_empty_7_phi_fu_194_p26 = 8'd13;
    end else if ((~(trunc_ln3_fu_368_p4 == 8'd4) & ~(trunc_ln3_fu_368_p4 == 8'd1) & ~(trunc_ln3_fu_368_p4 == 8'd0))) begin
        ap_phi_mux_empty_7_phi_fu_194_p26 = {{ap_phi_mux_ctx_new_0_phi_fu_94_p6[39:32]}};
    end else begin
        ap_phi_mux_empty_7_phi_fu_194_p26 = 'bx;
    end
end

always @ (*) begin
    if (((tmp_3_fu_324_p3 == 1'd0) & (tmp_1_fu_316_p3 == 1'd1))) begin
        ap_phi_mux_empty_phi_fu_105_p6 = 1'd1;
    end else if (((tmp_1_fu_316_p3 == 1'd0) | ((tmp_3_fu_324_p3 == 1'd1) & (tmp_1_fu_316_p3 == 1'd1)))) begin
        ap_phi_mux_empty_phi_fu_105_p6 = 1'd0;
    end else begin
        ap_phi_mux_empty_phi_fu_105_p6 = 'bx;
    end
end

always @ (*) begin
    if ((icmp_ln80_fu_529_p2 == 1'd0)) begin
        ap_phi_mux_finished_phi_fu_237_p4 = 1'd0;
    end else if ((icmp_ln80_fu_529_p2 == 1'd1)) begin
        ap_phi_mux_finished_phi_fu_237_p4 = xor_ln80_fu_535_p2;
    end else begin
        ap_phi_mux_finished_phi_fu_237_p4 = 'bx;
    end
end

always @ (*) begin
    if ((ap_start == 1'b1)) begin
        ctx_o_ap_vld = 1'b1;
    end else begin
        ctx_o_ap_vld = 1'b0;
    end
end

assign ap_done = ap_start;

assign ap_idle = 1'b1;

assign ap_ready = ap_start;

assign ap_return = ap_phi_mux_finished_phi_fu_237_p4;

assign ctx_o = ap_phi_mux_ctx_new_1_phi_fu_119_p26;

assign grp_fu_244_p3 = ap_phi_mux_ctx_new_0_phi_fu_94_p6[32'd42];

assign grp_fu_252_p4 = {{ap_phi_mux_ctx_new_0_phi_fu_94_p6[43:41]}};

assign grp_fu_262_p3 = ap_phi_mux_ctx_new_0_phi_fu_94_p6[32'd41];

assign grp_fu_270_p4 = {{ap_phi_mux_ctx_new_0_phi_fu_94_p6[43:42]}};

assign grp_fu_280_p3 = ap_phi_mux_ctx_new_0_phi_fu_94_p6[32'd40];

assign icmp_ln27_fu_296_p2 = ((trunc_ln27_fu_292_p1 != layer_idx) ? 1'b1 : 1'b0);

assign icmp_ln80_fu_529_p2 = ((ap_phi_mux_empty_7_phi_fu_194_p26 == 8'd13) ? 1'b1 : 1'b0);

assign or_ln1_fu_505_p6 = {{{{{grp_fu_270_p4}, {1'd0}}, {grp_fu_280_p3}}, {8'd1}}, {trunc_ln47_fu_501_p1}};

assign or_ln2_fu_480_p5 = {{{{{{1'd1}, {grp_fu_252_p4}}}, {1'd1}}}, {trunc_ln44_fu_476_p1}};

assign or_ln3_fu_457_p6 = {{{{{grp_fu_270_p4}, {1'd0}}, {grp_fu_280_p3}}, {8'd4}}, {trunc_ln59_fu_453_p1}};

assign or_ln4_fu_440_p5 = {{{{{{3'd5}, {grp_fu_252_p4}}}, {1'd1}}}, {trunc_ln56_fu_436_p1}};

assign or_ln5_fu_417_p6 = {{{{{grp_fu_270_p4}, {1'd0}}, {grp_fu_280_p3}}, {8'd13}}, {trunc_ln71_fu_413_p1}};

assign or_ln6_fu_396_p5 = {{{{{{1'd1}, {grp_fu_252_p4}}}, {1'd1}}}, {trunc_ln68_fu_392_p1}};

assign or_ln_fu_346_p4 = {{{tmp_fu_332_p4}, {2'd2}}, {trunc_ln33_fu_342_p1}};

assign select_ln27_fu_306_p3 = ((icmp_ln27_fu_296_p2[0:0] == 1'b1) ? zext_ln27_fu_302_p1 : trunc_ln23_fu_288_p1);

assign sext_ln45_fu_492_p1 = $signed(or_ln2_fu_480_p5);

assign sext_ln69_fu_408_p1 = $signed(or_ln6_fu_396_p5);

assign tmp_1_fu_316_p3 = select_ln27_fu_306_p3[32'd40];

assign tmp_3_fu_324_p3 = select_ln27_fu_306_p3[32'd43];

assign tmp_fu_332_p4 = {{select_ln27_fu_306_p3[43:42]}};

assign trunc_ln23_fu_288_p1 = ctx_i[43:0];

assign trunc_ln27_fu_292_p1 = ctx_i[31:0];

assign trunc_ln33_fu_342_p1 = select_ln27_fu_306_p3[39:0];

assign trunc_ln3_fu_368_p4 = {{ap_phi_mux_ctx_new_0_phi_fu_94_p6[39:32]}};

assign trunc_ln44_fu_476_p1 = ap_phi_mux_ctx_new_0_phi_fu_94_p6[39:0];

assign trunc_ln47_fu_501_p1 = ap_phi_mux_ctx_new_0_phi_fu_94_p6[31:0];

assign trunc_ln56_fu_436_p1 = ap_phi_mux_ctx_new_0_phi_fu_94_p6[39:0];

assign trunc_ln59_fu_453_p1 = ap_phi_mux_ctx_new_0_phi_fu_94_p6[31:0];

assign trunc_ln68_fu_392_p1 = ap_phi_mux_ctx_new_0_phi_fu_94_p6[39:0];

assign trunc_ln71_fu_413_p1 = ap_phi_mux_ctx_new_0_phi_fu_94_p6[31:0];

assign xor_ln80_fu_535_p2 = (ap_phi_mux_empty_6_phi_fu_150_p26 ^ 1'd1);

assign zext_ln27_fu_302_p1 = layer_idx;

assign zext_ln38_fu_357_p1 = ap_phi_mux_ctx_new_0_phi_fu_94_p6;

assign zext_ln45_fu_496_p1 = $unsigned(sext_ln45_fu_492_p1);

assign zext_ln49_fu_519_p1 = or_ln1_fu_505_p6;

assign zext_ln61_fu_471_p1 = or_ln3_fu_457_p6;

assign zext_ln73_fu_431_p1 = or_ln5_fu_417_p6;

endmodule //run_single_head
