// ==============================================================
// Generated by Vitis HLS v2025.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module drive_group_head_phase_run_single_head (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        head_ctx_ref_address0,
        head_ctx_ref_ce0,
        head_ctx_ref_we0,
        head_ctx_ref_d0,
        head_ctx_ref_q0,
        ctx,
        layer_idx,
        start_r,
        ap_return
);

parameter    ap_ST_fsm_state1 = 5'd1;
parameter    ap_ST_fsm_state2 = 5'd2;
parameter    ap_ST_fsm_state3 = 5'd4;
parameter    ap_ST_fsm_state4 = 5'd8;
parameter    ap_ST_fsm_state5 = 5'd16;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [1:0] head_ctx_ref_address0;
output   head_ctx_ref_ce0;
output   head_ctx_ref_we0;
output  [65:0] head_ctx_ref_d0;
input  [65:0] head_ctx_ref_q0;
input  [5:0] ctx;
input  [31:0] layer_idx;
input  [0:0] start_r;
output  [0:0] ap_return;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg[0:0] ap_return;

(* fsm_encoding = "none" *) reg   [4:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg   [1:0] head_ctx_ref_addr_reg_1863;
wire   [3:0] trunc_ln47_fu_413_p1;
reg   [3:0] trunc_ln47_reg_1868;
wire   [0:0] start_read_read_fu_220_p2;
wire    ap_CS_fsm_state2;
wire   [65:0] zext_ln47_1_fu_424_p1;
reg   [65:0] zext_ln47_1_reg_1877;
wire   [65:0] select_ln50_fu_472_p3;
wire   [0:0] tmp_fu_487_p3;
reg   [0:0] tmp_reg_1909;
wire   [65:0] select_ln61_fu_725_p3;
reg   [65:0] select_ln61_reg_1913;
wire   [0:0] or_ln62_5_fu_757_p2;
reg   [0:0] or_ln62_5_reg_1921;
wire   [0:0] tmp_13_fu_768_p3;
reg   [0:0] tmp_13_reg_1925;
wire    ap_CS_fsm_state3;
wire   [7:0] trunc_ln9_fu_793_p4;
reg   [7:0] trunc_ln9_reg_1929;
wire    ap_CS_fsm_state4;
wire   [0:0] grp_fu_380_p3;
reg   [0:0] tmp_25_reg_1934;
wire   [0:0] tmp_62_fu_835_p3;
reg   [0:0] tmp_62_reg_1938;
wire   [0:0] tmp_66_fu_843_p3;
reg   [0:0] tmp_66_reg_1942;
wire   [0:0] tmp_81_fu_851_p3;
reg   [0:0] tmp_81_reg_1946;
reg   [0:0] tmp_24_reg_1950;
wire   [0:0] tmp_54_fu_859_p3;
reg   [0:0] tmp_54_reg_1954;
wire   [0:0] tmp_58_fu_867_p3;
reg   [0:0] tmp_58_reg_1958;
wire   [0:0] tmp_80_fu_875_p3;
reg   [0:0] tmp_80_reg_1962;
reg   [0:0] tmp_23_reg_1966;
wire   [0:0] tmp_47_fu_883_p3;
reg   [0:0] tmp_47_reg_1970;
wire   [0:0] tmp_50_fu_891_p3;
reg   [0:0] tmp_50_reg_1974;
wire   [0:0] tmp_79_fu_899_p3;
reg   [0:0] tmp_79_reg_1978;
reg   [0:0] tmp_22_reg_1982;
wire   [0:0] tmp_41_fu_907_p3;
reg   [0:0] tmp_41_reg_1986;
wire   [0:0] tmp_44_fu_915_p3;
reg   [0:0] tmp_44_reg_1990;
wire   [0:0] tmp_78_fu_923_p3;
reg   [0:0] tmp_78_reg_1994;
reg   [0:0] tmp_18_reg_1998;
wire   [0:0] tmp_35_fu_931_p3;
reg   [0:0] tmp_35_reg_2002;
wire   [0:0] tmp_38_fu_939_p3;
reg   [0:0] tmp_38_reg_2006;
wire   [0:0] tmp_77_fu_947_p3;
reg   [0:0] tmp_77_reg_2010;
reg   [0:0] tmp_15_reg_2014;
wire   [0:0] tmp_31_fu_955_p3;
reg   [0:0] tmp_31_reg_2018;
wire   [0:0] tmp_32_fu_963_p3;
reg   [0:0] tmp_32_reg_2022;
wire   [0:0] tmp_74_fu_971_p3;
reg   [0:0] tmp_74_reg_2026;
reg   [0:0] tmp_14_reg_2030;
wire   [0:0] tmp_28_fu_979_p3;
reg   [0:0] tmp_28_reg_2034;
wire   [0:0] tmp_29_fu_987_p3;
reg   [0:0] tmp_29_reg_2038;
wire   [0:0] tmp_71_fu_995_p3;
reg   [0:0] tmp_71_reg_2042;
wire   [65:0] or_ln62_4_fu_778_p3;
reg   [65:0] ap_phi_mux_empty_phi_fu_248_p6;
reg   [65:0] empty_reg_245;
reg   [7:0] ap_phi_mux_empty_11_phi_fu_268_p74;
reg   [7:0] empty_11_reg_257;
wire    ap_CS_fsm_state5;
wire   [63:0] zext_ln47_fu_408_p1;
reg    head_ctx_ref_ce0_local;
reg   [1:0] head_ctx_ref_address0_local;
reg    head_ctx_ref_we0_local;
reg   [65:0] head_ctx_ref_d0_local;
wire   [65:0] shl_ln50_fu_480_p2;
wire   [65:0] shl_ln62_fu_763_p2;
wire   [65:0] shl_ln62_1_fu_787_p2;
wire   [65:0] shl_ln186_fu_1017_p2;
wire   [65:0] shl_ln178_fu_1061_p2;
wire   [65:0] shl_ln182_fu_1109_p2;
wire   [65:0] shl_ln167_fu_1153_p2;
wire   [65:0] shl_ln171_fu_1209_p2;
wire   [65:0] shl_ln156_fu_1253_p2;
wire   [65:0] shl_ln160_fu_1311_p2;
wire   [65:0] shl_ln145_fu_1355_p2;
wire   [65:0] shl_ln149_fu_1413_p2;
wire   [65:0] shl_ln139_fu_1433_p2;
wire   [65:0] shl_ln136_fu_1453_p2;
wire   [65:0] shl_ln133_fu_1473_p2;
wire   [65:0] shl_ln124_fu_1517_p2;
wire   [65:0] shl_ln129_fu_1575_p2;
wire   [65:0] shl_ln118_fu_1595_p2;
wire   [65:0] shl_ln115_fu_1615_p2;
wire   [65:0] shl_ln106_fu_1659_p2;
wire   [65:0] shl_ln111_fu_1717_p2;
wire   [65:0] shl_ln94_fu_1759_p2;
wire   [65:0] shl_ln99_fu_1817_p2;
wire   [65:0] shl_ln87_fu_1851_p2;
wire   [1:0] lshr_ln47_1_fu_398_p4;
wire   [6:0] shl_ln_fu_417_p3;
wire   [65:0] lshr_ln47_fu_428_p2;
wire   [14:0] tmp_1_fu_434_p4;
wire   [41:0] trunc_ln47_1_fu_444_p1;
wire   [31:0] trunc_ln50_fu_458_p1;
wire   [0:0] icmp_ln50_fu_462_p2;
wire   [65:0] zext_ln6_fu_468_p1;
wire   [65:0] and_ln_fu_448_p4;
wire   [5:0] tmp_3_fu_503_p4;
wire   [58:0] trunc_ln56_fu_513_p1;
wire   [0:0] tmp_2_fu_495_p3;
wire   [65:0] or_ln_fu_517_p4;
wire   [65:0] select_ln56_fu_527_p3;
wire   [4:0] tmp_5_fu_543_p4;
wire   [59:0] trunc_ln57_fu_553_p1;
wire   [0:0] tmp_4_fu_535_p3;
wire   [65:0] or_ln1_fu_557_p4;
wire   [65:0] select_ln57_fu_567_p3;
wire   [3:0] tmp_7_fu_583_p4;
wire   [60:0] trunc_ln58_fu_593_p1;
wire   [0:0] tmp_6_fu_575_p3;
wire   [65:0] or_ln2_fu_597_p4;
wire   [65:0] select_ln58_fu_607_p3;
wire   [2:0] tmp_9_fu_623_p4;
wire   [61:0] trunc_ln59_fu_633_p1;
wire   [0:0] tmp_8_fu_615_p3;
wire   [65:0] or_ln3_fu_637_p4;
wire   [65:0] select_ln59_fu_647_p3;
wire   [1:0] tmp_s_fu_663_p4;
wire   [62:0] trunc_ln60_fu_673_p1;
wire   [0:0] tmp_10_fu_655_p3;
wire   [65:0] or_ln4_fu_677_p4;
wire   [65:0] select_ln60_fu_687_p3;
wire   [0:0] tmp_12_fu_703_p3;
wire   [63:0] trunc_ln61_fu_711_p1;
wire   [0:0] tmp_11_fu_695_p3;
wire   [65:0] or_ln5_fu_715_p4;
wire   [0:0] or_ln62_fu_733_p2;
wire   [0:0] or_ln62_2_fu_745_p2;
wire   [0:0] or_ln62_3_fu_751_p2;
wire   [0:0] or_ln62_1_fu_739_p2;
wire   [64:0] trunc_ln62_fu_775_p1;
wire   [25:0] grp_fu_388_p4;
wire   [31:0] trunc_ln186_fu_1003_p1;
wire   [65:0] or_ln11_fu_1007_p4;
wire   [6:0] tmp_48_fu_1023_p4;
wire   [6:0] tmp_49_fu_1033_p4;
wire   [41:0] trunc_ln176_fu_1043_p1;
wire   [65:0] or_ln19_fu_1047_p6;
wire   [5:0] tmp_75_fu_1067_p4;
wire   [17:0] tmp_76_fu_1077_p4;
wire   [31:0] trunc_ln180_fu_1087_p1;
wire   [64:0] or_ln26_fu_1091_p6;
wire   [65:0] zext_ln182_fu_1105_p1;
wire   [7:0] tmp_45_fu_1115_p4;
wire   [5:0] tmp_46_fu_1125_p4;
wire   [41:0] trunc_ln165_fu_1135_p1;
wire   [65:0] or_ln18_fu_1139_p6;
wire   [0:0] tmp_82_fu_1159_p3;
wire   [5:0] tmp_72_fu_1167_p4;
wire   [16:0] tmp_73_fu_1177_p4;
wire   [31:0] trunc_ln169_fu_1187_p1;
wire   [65:0] or_ln25_fu_1191_p8;
wire   [8:0] tmp_42_fu_1215_p4;
wire   [4:0] tmp_43_fu_1225_p4;
wire   [41:0] trunc_ln154_fu_1235_p1;
wire   [65:0] or_ln17_fu_1239_p6;
wire   [1:0] tmp_67_fu_1259_p4;
wire   [5:0] tmp_68_fu_1269_p4;
wire   [15:0] tmp_69_fu_1279_p4;
wire   [31:0] trunc_ln158_fu_1289_p1;
wire   [65:0] or_ln24_fu_1293_p8;
wire   [9:0] tmp_39_fu_1317_p4;
wire   [3:0] tmp_40_fu_1327_p4;
wire   [41:0] trunc_ln143_fu_1337_p1;
wire   [65:0] or_ln16_fu_1341_p6;
wire   [2:0] tmp_63_fu_1361_p4;
wire   [5:0] tmp_64_fu_1371_p4;
wire   [14:0] tmp_65_fu_1381_p4;
wire   [31:0] trunc_ln147_fu_1391_p1;
wire   [65:0] or_ln23_fu_1395_p8;
wire   [31:0] trunc_ln139_fu_1419_p1;
wire   [65:0] or_ln10_fu_1423_p4;
wire   [31:0] trunc_ln136_fu_1439_p1;
wire   [65:0] or_ln9_fu_1443_p4;
wire   [31:0] trunc_ln133_fu_1459_p1;
wire   [65:0] or_ln8_fu_1463_p4;
wire   [10:0] tmp_36_fu_1479_p4;
wire   [2:0] tmp_37_fu_1489_p4;
wire   [41:0] trunc_ln122_fu_1499_p1;
wire   [65:0] or_ln15_fu_1503_p6;
wire   [3:0] tmp_59_fu_1523_p4;
wire   [5:0] tmp_60_fu_1533_p4;
wire   [13:0] tmp_61_fu_1543_p4;
wire   [31:0] trunc_ln127_fu_1553_p1;
wire   [65:0] or_ln22_fu_1557_p8;
wire   [31:0] trunc_ln118_fu_1581_p1;
wire   [65:0] or_ln7_fu_1585_p4;
wire   [31:0] trunc_ln115_fu_1601_p1;
wire   [65:0] or_ln6_fu_1605_p4;
wire   [11:0] tmp_33_fu_1621_p4;
wire   [1:0] tmp_34_fu_1631_p4;
wire   [41:0] trunc_ln104_fu_1641_p1;
wire   [65:0] or_ln14_fu_1645_p6;
wire   [4:0] tmp_55_fu_1665_p4;
wire   [5:0] tmp_56_fu_1675_p4;
wire   [12:0] tmp_57_fu_1685_p4;
wire   [31:0] trunc_ln109_fu_1695_p1;
wire   [65:0] or_ln21_fu_1699_p8;
wire   [12:0] tmp_30_fu_1723_p4;
wire   [0:0] tmp_70_fu_1733_p3;
wire   [41:0] trunc_ln92_fu_1741_p1;
wire   [65:0] or_ln13_fu_1745_p6;
wire   [5:0] tmp_51_fu_1765_p4;
wire   [5:0] tmp_52_fu_1775_p4;
wire   [11:0] tmp_53_fu_1785_p4;
wire   [31:0] trunc_ln97_fu_1795_p1;
wire   [65:0] or_ln20_fu_1799_p8;
wire   [8:0] tmp_27_fu_1823_p4;
wire   [31:0] trunc_ln70_fu_1833_p1;
wire   [51:0] or_ln12_fu_1837_p4;
wire   [65:0] zext_ln87_fu_1847_p1;
wire   [0:0] icmp_ln194_fu_1857_p2;
reg   [0:0] ap_return_preg;
reg   [4:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
wire    ap_ST_fsm_state5_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 5'd1;
#0 ap_return_preg = 1'd0;
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_preg <= 1'd0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state5)) begin
            ap_return_preg <= icmp_ln194_fu_1857_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state5) & (((trunc_ln9_reg_1929 == 8'd2) & (tmp_74_reg_2026 == 1'd1) & (tmp_32_reg_2022 == 1'd1) & (tmp_15_reg_2014 == 1'd0)) | ((trunc_ln9_reg_1929 == 8'd2) & (tmp_74_reg_2026 == 1'd1) & (tmp_32_reg_2022 == 1'd1) & (tmp_31_reg_2018 == 1'd1))))) begin
        empty_11_reg_257 <= 8'd3;
    end else if (((1'b1 == ap_CS_fsm_state5) & (((trunc_ln9_reg_1929 == 8'd5) & (tmp_77_reg_2010 == 1'd1) & (tmp_38_reg_2006 == 1'd1) & (tmp_18_reg_1998 == 1'd0)) | ((trunc_ln9_reg_1929 == 8'd5) & (tmp_77_reg_2010 == 1'd1) & (tmp_38_reg_2006 == 1'd1) & (tmp_35_reg_2002 == 1'd1))))) begin
        empty_11_reg_257 <= 8'd6;
    end else if (((1'b1 == ap_CS_fsm_state5) & (((tmp_81_reg_1946 == 1'd1) & (tmp_66_reg_1942 == 1'd1) & (tmp_25_reg_1934 == 1'd0) & (trunc_ln9_reg_1929 == 8'd12)) | ((tmp_81_reg_1946 == 1'd1) & (tmp_66_reg_1942 == 1'd1) & (tmp_62_reg_1938 == 1'd1) & (trunc_ln9_reg_1929 == 8'd12))))) begin
        empty_11_reg_257 <= 8'd13;
    end else if (((trunc_ln9_fu_793_p4 == 8'd0) & (start_read_read_fu_220_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state4))) begin
        empty_11_reg_257 <= 8'd0;
    end else if ((~(trunc_ln9_fu_793_p4 == 8'd13) & ~(trunc_ln9_fu_793_p4 == 8'd12) & ~(trunc_ln9_fu_793_p4 == 8'd11) & ~(trunc_ln9_fu_793_p4 == 8'd10) & ~(trunc_ln9_fu_793_p4 == 8'd9) & ~(trunc_ln9_fu_793_p4 == 8'd8) & ~(trunc_ln9_fu_793_p4 == 8'd7) & ~(trunc_ln9_fu_793_p4 == 8'd6) & ~(trunc_ln9_fu_793_p4 == 8'd5) & ~(trunc_ln9_fu_793_p4 == 8'd4) & ~(trunc_ln9_fu_793_p4 == 8'd3) & ~(trunc_ln9_fu_793_p4 == 8'd2) & ~(trunc_ln9_fu_793_p4 == 8'd1) & ~(trunc_ln9_fu_793_p4 == 8'd0) & (1'b1 == ap_CS_fsm_state4))) begin
        empty_11_reg_257 <= {{ap_phi_mux_empty_phi_fu_248_p6[39:32]}};
    end else if ((((1'b1 == ap_CS_fsm_state4) & (((grp_fu_380_p3 == 1'd0) & (trunc_ln9_fu_793_p4 == 8'd1) & (tmp_71_fu_995_p3 == 1'd0) & (tmp_29_fu_987_p3 == 1'd1)) | ((trunc_ln9_fu_793_p4 == 8'd1) & (tmp_71_fu_995_p3 == 1'd0) & (tmp_29_fu_987_p3 == 1'd1) & (tmp_28_fu_979_p3 == 1'd1)))) | ((1'b1 == ap_CS_fsm_state4) & (((grp_fu_380_p3 == 1'd0) & (trunc_ln9_fu_793_p4 == 8'd1) & (tmp_29_fu_987_p3 == 1'd0)) | ((trunc_ln9_fu_793_p4 == 8'd1) & (tmp_29_fu_987_p3 == 1'd0) & (tmp_28_fu_979_p3 == 1'd1)))) | ((trunc_ln9_reg_1929 == 8'd0) & (start_read_read_fu_220_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state5)) | ((trunc_ln9_reg_1929 == 8'd1) & (1'b1 == ap_CS_fsm_state5) & (tmp_28_reg_2034 == 1'd0) & (tmp_14_reg_2030 == 1'd1)))) begin
        empty_11_reg_257 <= 8'd1;
    end else if ((((1'b1 == ap_CS_fsm_state4) & (((grp_fu_380_p3 == 1'd0) & (trunc_ln9_fu_793_p4 == 8'd2) & (tmp_74_fu_971_p3 == 1'd0) & (tmp_32_fu_963_p3 == 1'd1)) | ((trunc_ln9_fu_793_p4 == 8'd2) & (tmp_74_fu_971_p3 == 1'd0) & (tmp_32_fu_963_p3 == 1'd1) & (tmp_31_fu_955_p3 == 1'd1)))) | ((1'b1 == ap_CS_fsm_state4) & (((grp_fu_380_p3 == 1'd0) & (trunc_ln9_fu_793_p4 == 8'd2) & (tmp_32_fu_963_p3 == 1'd0)) | ((trunc_ln9_fu_793_p4 == 8'd2) & (tmp_32_fu_963_p3 == 1'd0) & (tmp_31_fu_955_p3 == 1'd1)))) | ((trunc_ln9_reg_1929 == 8'd2) & (1'b1 == ap_CS_fsm_state5) & (tmp_31_reg_2018 == 1'd0) & (tmp_15_reg_2014 == 1'd1)) | ((1'b1 == ap_CS_fsm_state5) & (((trunc_ln9_reg_1929 == 8'd1) & (tmp_71_reg_2042 == 1'd1) & (tmp_29_reg_2038 == 1'd1) & (tmp_14_reg_2030 == 1'd0)) | ((trunc_ln9_reg_1929 == 8'd1) & (tmp_71_reg_2042 == 1'd1) & (tmp_29_reg_2038 == 1'd1) & (tmp_28_reg_2034 == 1'd1)))))) begin
        empty_11_reg_257 <= 8'd2;
    end else if ((((1'b1 == ap_CS_fsm_state4) & (((tmp_79_fu_899_p3 == 1'd0) & (tmp_50_fu_891_p3 == 1'd1) & (tmp_47_fu_883_p3 == 1'd1) & (trunc_ln9_fu_793_p4 == 8'd10)) | ((tmp_79_fu_899_p3 == 1'd0) & (tmp_50_fu_891_p3 == 1'd1) & (grp_fu_380_p3 == 1'd0) & (trunc_ln9_fu_793_p4 == 8'd10)))) | ((1'b1 == ap_CS_fsm_state4) & (((tmp_50_fu_891_p3 == 1'd0) & (tmp_47_fu_883_p3 == 1'd1) & (trunc_ln9_fu_793_p4 == 8'd10)) | ((tmp_50_fu_891_p3 == 1'd0) & (grp_fu_380_p3 == 1'd0) & (trunc_ln9_fu_793_p4 == 8'd10)))) | ((tmp_47_reg_1970 == 1'd0) & (tmp_23_reg_1966 == 1'd1) & (trunc_ln9_reg_1929 == 8'd10) & (1'b1 == ap_CS_fsm_state5)) | ((1'b1 == ap_CS_fsm_state5) & (((tmp_44_reg_1990 == 1'd1) & (tmp_22_reg_1982 == 1'd0) & (trunc_ln9_reg_1929 == 8'd9) & (tmp_78_reg_1994 == 1'd1)) | ((tmp_44_reg_1990 == 1'd1) & (tmp_41_reg_1986 == 1'd1) & (trunc_ln9_reg_1929 == 8'd9) & (tmp_78_reg_1994 == 1'd1)))))) begin
        empty_11_reg_257 <= 8'd10;
    end else if ((((1'b1 == ap_CS_fsm_state4) & (((tmp_80_fu_875_p3 == 1'd0) & (tmp_58_fu_867_p3 == 1'd1) & (tmp_54_fu_859_p3 == 1'd1) & (trunc_ln9_fu_793_p4 == 8'd11)) | ((tmp_80_fu_875_p3 == 1'd0) & (tmp_58_fu_867_p3 == 1'd1) & (grp_fu_380_p3 == 1'd0) & (trunc_ln9_fu_793_p4 == 8'd11)))) | ((1'b1 == ap_CS_fsm_state4) & (((tmp_58_fu_867_p3 == 1'd0) & (tmp_54_fu_859_p3 == 1'd1) & (trunc_ln9_fu_793_p4 == 8'd11)) | ((tmp_58_fu_867_p3 == 1'd0) & (grp_fu_380_p3 == 1'd0) & (trunc_ln9_fu_793_p4 == 8'd11)))) | ((tmp_54_reg_1954 == 1'd0) & (tmp_24_reg_1950 == 1'd1) & (trunc_ln9_reg_1929 == 8'd11) & (1'b1 == ap_CS_fsm_state5)) | ((1'b1 == ap_CS_fsm_state5) & (((tmp_79_reg_1978 == 1'd1) & (tmp_50_reg_1974 == 1'd1) & (tmp_23_reg_1966 == 1'd0) & (trunc_ln9_reg_1929 == 8'd10)) | ((tmp_79_reg_1978 == 1'd1) & (tmp_50_reg_1974 == 1'd1) & (tmp_47_reg_1970 == 1'd1) & (trunc_ln9_reg_1929 == 8'd10)))))) begin
        empty_11_reg_257 <= 8'd11;
    end else if ((((1'b1 == ap_CS_fsm_state4) & (((tmp_81_fu_851_p3 == 1'd0) & (tmp_66_fu_843_p3 == 1'd1) & (tmp_62_fu_835_p3 == 1'd1) & (trunc_ln9_fu_793_p4 == 8'd12)) | ((tmp_81_fu_851_p3 == 1'd0) & (tmp_66_fu_843_p3 == 1'd1) & (grp_fu_380_p3 == 1'd0) & (trunc_ln9_fu_793_p4 == 8'd12)))) | ((1'b1 == ap_CS_fsm_state4) & (((tmp_66_fu_843_p3 == 1'd0) & (tmp_62_fu_835_p3 == 1'd1) & (trunc_ln9_fu_793_p4 == 8'd12)) | ((tmp_66_fu_843_p3 == 1'd0) & (grp_fu_380_p3 == 1'd0) & (trunc_ln9_fu_793_p4 == 8'd12)))) | ((tmp_62_reg_1938 == 1'd0) & (tmp_25_reg_1934 == 1'd1) & (trunc_ln9_reg_1929 == 8'd12) & (1'b1 == ap_CS_fsm_state5)) | ((1'b1 == ap_CS_fsm_state5) & (((tmp_80_reg_1962 == 1'd1) & (tmp_58_reg_1958 == 1'd1) & (tmp_24_reg_1950 == 1'd0) & (trunc_ln9_reg_1929 == 8'd11)) | ((tmp_80_reg_1962 == 1'd1) & (tmp_58_reg_1958 == 1'd1) & (tmp_54_reg_1954 == 1'd1) & (trunc_ln9_reg_1929 == 8'd11)))))) begin
        empty_11_reg_257 <= 8'd12;
    end else if (((trunc_ln9_reg_1929 == 8'd3) & (1'b1 == ap_CS_fsm_state5))) begin
        empty_11_reg_257 <= 8'd4;
    end else if ((((1'b1 == ap_CS_fsm_state4) & (((grp_fu_380_p3 == 1'd0) & (trunc_ln9_fu_793_p4 == 8'd5) & (tmp_77_fu_947_p3 == 1'd0) & (tmp_38_fu_939_p3 == 1'd1)) | ((trunc_ln9_fu_793_p4 == 8'd5) & (tmp_77_fu_947_p3 == 1'd0) & (tmp_38_fu_939_p3 == 1'd1) & (tmp_35_fu_931_p3 == 1'd1)))) | ((1'b1 == ap_CS_fsm_state4) & (((grp_fu_380_p3 == 1'd0) & (trunc_ln9_fu_793_p4 == 8'd5) & (tmp_38_fu_939_p3 == 1'd0)) | ((trunc_ln9_fu_793_p4 == 8'd5) & (tmp_38_fu_939_p3 == 1'd0) & (tmp_35_fu_931_p3 == 1'd1)))) | ((trunc_ln9_reg_1929 == 8'd5) & (1'b1 == ap_CS_fsm_state5) & (tmp_35_reg_2002 == 1'd0) & (tmp_18_reg_1998 == 1'd1)) | ((trunc_ln9_reg_1929 == 8'd4) & (1'b1 == ap_CS_fsm_state5)))) begin
        empty_11_reg_257 <= 8'd5;
    end else if (((trunc_ln9_reg_1929 == 8'd6) & (1'b1 == ap_CS_fsm_state5))) begin
        empty_11_reg_257 <= 8'd7;
    end else if (((trunc_ln9_reg_1929 == 8'd7) & (1'b1 == ap_CS_fsm_state5))) begin
        empty_11_reg_257 <= 8'd8;
    end else if ((((1'b1 == ap_CS_fsm_state4) & (((tmp_78_fu_923_p3 == 1'd0) & (tmp_44_fu_915_p3 == 1'd1) & (tmp_41_fu_907_p3 == 1'd1) & (trunc_ln9_fu_793_p4 == 8'd9)) | ((tmp_78_fu_923_p3 == 1'd0) & (tmp_44_fu_915_p3 == 1'd1) & (grp_fu_380_p3 == 1'd0) & (trunc_ln9_fu_793_p4 == 8'd9)))) | ((1'b1 == ap_CS_fsm_state4) & (((tmp_44_fu_915_p3 == 1'd0) & (tmp_41_fu_907_p3 == 1'd1) & (trunc_ln9_fu_793_p4 == 8'd9)) | ((tmp_44_fu_915_p3 == 1'd0) & (grp_fu_380_p3 == 1'd0) & (trunc_ln9_fu_793_p4 == 8'd9)))) | ((tmp_41_reg_1986 == 1'd0) & (tmp_22_reg_1982 == 1'd1) & (trunc_ln9_reg_1929 == 8'd9) & (1'b1 == ap_CS_fsm_state5)) | ((trunc_ln9_reg_1929 == 8'd8) & (1'b1 == ap_CS_fsm_state5)))) begin
        empty_11_reg_257 <= 8'd9;
    end else if (((trunc_ln9_reg_1929 == 8'd13) & (1'b1 == ap_CS_fsm_state5))) begin
        empty_11_reg_257 <= 8'd14;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_13_fu_768_p3 == 1'd0) & (1'b1 == ap_CS_fsm_state3))) begin
                empty_reg_245[41 : 0] <= select_ln61_reg_1913[41 : 0];
        empty_reg_245[65 : 51] <= select_ln61_reg_1913[65 : 51];
    end else if (((tmp_fu_487_p3 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
                empty_reg_245[41 : 0] <= select_ln50_fu_472_p3[41 : 0];
        empty_reg_245[65 : 51] <= select_ln50_fu_472_p3[65 : 51];
    end else if (((tmp_13_reg_1925 == 1'd1) & (tmp_reg_1909 == 1'd1) & (1'b1 == ap_CS_fsm_state4))) begin
                empty_reg_245[41 : 0] <= or_ln62_4_fu_778_p3[41 : 0];
        empty_reg_245[65 : 51] <= or_ln62_4_fu_778_p3[65 : 51];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        head_ctx_ref_addr_reg_1863 <= zext_ln47_fu_408_p1;
        trunc_ln47_reg_1868 <= trunc_ln47_fu_413_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        or_ln62_5_reg_1921 <= or_ln62_5_fu_757_p2;
        select_ln61_reg_1913[41 : 0] <= select_ln61_fu_725_p3[41 : 0];
select_ln61_reg_1913[65 : 51] <= select_ln61_fu_725_p3[65 : 51];
        tmp_reg_1909 <= select_ln50_fu_472_p3[32'd41];
        zext_ln47_1_reg_1877[6 : 3] <= zext_ln47_1_fu_424_p1[6 : 3];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        tmp_13_reg_1925 <= select_ln61_reg_1913[32'd58];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        tmp_14_reg_2030 <= ap_phi_mux_empty_phi_fu_248_p6[32'd40];
        tmp_15_reg_2014 <= ap_phi_mux_empty_phi_fu_248_p6[32'd40];
        tmp_18_reg_1998 <= ap_phi_mux_empty_phi_fu_248_p6[32'd40];
        tmp_22_reg_1982 <= ap_phi_mux_empty_phi_fu_248_p6[32'd40];
        tmp_23_reg_1966 <= ap_phi_mux_empty_phi_fu_248_p6[32'd40];
        tmp_24_reg_1950 <= ap_phi_mux_empty_phi_fu_248_p6[32'd40];
        tmp_25_reg_1934 <= ap_phi_mux_empty_phi_fu_248_p6[32'd40];
        tmp_28_reg_2034 <= ap_phi_mux_empty_phi_fu_248_p6[32'd52];
        tmp_29_reg_2038 <= ap_phi_mux_empty_phi_fu_248_p6[32'd59];
        tmp_31_reg_2018 <= ap_phi_mux_empty_phi_fu_248_p6[32'd53];
        tmp_32_reg_2022 <= ap_phi_mux_empty_phi_fu_248_p6[32'd60];
        tmp_35_reg_2002 <= ap_phi_mux_empty_phi_fu_248_p6[32'd54];
        tmp_38_reg_2006 <= ap_phi_mux_empty_phi_fu_248_p6[32'd61];
        tmp_41_reg_1986 <= ap_phi_mux_empty_phi_fu_248_p6[32'd55];
        tmp_44_reg_1990 <= ap_phi_mux_empty_phi_fu_248_p6[32'd62];
        tmp_47_reg_1970 <= ap_phi_mux_empty_phi_fu_248_p6[32'd56];
        tmp_50_reg_1974 <= ap_phi_mux_empty_phi_fu_248_p6[32'd63];
        tmp_54_reg_1954 <= ap_phi_mux_empty_phi_fu_248_p6[32'd57];
        tmp_58_reg_1958 <= ap_phi_mux_empty_phi_fu_248_p6[32'd64];
        tmp_62_reg_1938 <= ap_phi_mux_empty_phi_fu_248_p6[32'd58];
        tmp_66_reg_1942 <= ap_phi_mux_empty_phi_fu_248_p6[32'd65];
        tmp_71_reg_2042 <= ap_phi_mux_empty_phi_fu_248_p6[32'd52];
        tmp_74_reg_2026 <= ap_phi_mux_empty_phi_fu_248_p6[32'd53];
        tmp_77_reg_2010 <= ap_phi_mux_empty_phi_fu_248_p6[32'd54];
        tmp_78_reg_1994 <= ap_phi_mux_empty_phi_fu_248_p6[32'd55];
        tmp_79_reg_1978 <= ap_phi_mux_empty_phi_fu_248_p6[32'd56];
        tmp_80_reg_1962 <= ap_phi_mux_empty_phi_fu_248_p6[32'd57];
        tmp_81_reg_1946 <= ap_phi_mux_empty_phi_fu_248_p6[32'd58];
        trunc_ln9_reg_1929 <= {{ap_phi_mux_empty_phi_fu_248_p6[39:32]}};
    end
end

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

assign ap_ST_fsm_state3_blk = 1'b0;

assign ap_ST_fsm_state4_blk = 1'b0;

assign ap_ST_fsm_state5_blk = 1'b0;

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state5) | ((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state5) & (((trunc_ln9_reg_1929 == 8'd2) & (tmp_74_reg_2026 == 1'd1) & (tmp_32_reg_2022 == 1'd1) & (tmp_15_reg_2014 == 1'd0)) | ((trunc_ln9_reg_1929 == 8'd2) & (tmp_74_reg_2026 == 1'd1) & (tmp_32_reg_2022 == 1'd1) & (tmp_31_reg_2018 == 1'd1))))) begin
        ap_phi_mux_empty_11_phi_fu_268_p74 = 8'd3;
    end else if (((1'b1 == ap_CS_fsm_state5) & (((trunc_ln9_reg_1929 == 8'd5) & (tmp_77_reg_2010 == 1'd1) & (tmp_38_reg_2006 == 1'd1) & (tmp_18_reg_1998 == 1'd0)) | ((trunc_ln9_reg_1929 == 8'd5) & (tmp_77_reg_2010 == 1'd1) & (tmp_38_reg_2006 == 1'd1) & (tmp_35_reg_2002 == 1'd1))))) begin
        ap_phi_mux_empty_11_phi_fu_268_p74 = 8'd6;
    end else if (((1'b1 == ap_CS_fsm_state5) & (((tmp_81_reg_1946 == 1'd1) & (tmp_66_reg_1942 == 1'd1) & (tmp_25_reg_1934 == 1'd0) & (trunc_ln9_reg_1929 == 8'd12)) | ((tmp_81_reg_1946 == 1'd1) & (tmp_66_reg_1942 == 1'd1) & (tmp_62_reg_1938 == 1'd1) & (trunc_ln9_reg_1929 == 8'd12))))) begin
        ap_phi_mux_empty_11_phi_fu_268_p74 = 8'd13;
    end else if ((((trunc_ln9_reg_1929 == 8'd0) & (start_read_read_fu_220_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state5)) | ((trunc_ln9_reg_1929 == 8'd1) & (1'b1 == ap_CS_fsm_state5) & (tmp_28_reg_2034 == 1'd0) & (tmp_14_reg_2030 == 1'd1)))) begin
        ap_phi_mux_empty_11_phi_fu_268_p74 = 8'd1;
    end else if ((((trunc_ln9_reg_1929 == 8'd2) & (1'b1 == ap_CS_fsm_state5) & (tmp_31_reg_2018 == 1'd0) & (tmp_15_reg_2014 == 1'd1)) | ((1'b1 == ap_CS_fsm_state5) & (((trunc_ln9_reg_1929 == 8'd1) & (tmp_71_reg_2042 == 1'd1) & (tmp_29_reg_2038 == 1'd1) & (tmp_14_reg_2030 == 1'd0)) | ((trunc_ln9_reg_1929 == 8'd1) & (tmp_71_reg_2042 == 1'd1) & (tmp_29_reg_2038 == 1'd1) & (tmp_28_reg_2034 == 1'd1)))))) begin
        ap_phi_mux_empty_11_phi_fu_268_p74 = 8'd2;
    end else if ((((tmp_47_reg_1970 == 1'd0) & (tmp_23_reg_1966 == 1'd1) & (trunc_ln9_reg_1929 == 8'd10) & (1'b1 == ap_CS_fsm_state5)) | ((1'b1 == ap_CS_fsm_state5) & (((tmp_44_reg_1990 == 1'd1) & (tmp_22_reg_1982 == 1'd0) & (trunc_ln9_reg_1929 == 8'd9) & (tmp_78_reg_1994 == 1'd1)) | ((tmp_44_reg_1990 == 1'd1) & (tmp_41_reg_1986 == 1'd1) & (trunc_ln9_reg_1929 == 8'd9) & (tmp_78_reg_1994 == 1'd1)))))) begin
        ap_phi_mux_empty_11_phi_fu_268_p74 = 8'd10;
    end else if ((((tmp_54_reg_1954 == 1'd0) & (tmp_24_reg_1950 == 1'd1) & (trunc_ln9_reg_1929 == 8'd11) & (1'b1 == ap_CS_fsm_state5)) | ((1'b1 == ap_CS_fsm_state5) & (((tmp_79_reg_1978 == 1'd1) & (tmp_50_reg_1974 == 1'd1) & (tmp_23_reg_1966 == 1'd0) & (trunc_ln9_reg_1929 == 8'd10)) | ((tmp_79_reg_1978 == 1'd1) & (tmp_50_reg_1974 == 1'd1) & (tmp_47_reg_1970 == 1'd1) & (trunc_ln9_reg_1929 == 8'd10)))))) begin
        ap_phi_mux_empty_11_phi_fu_268_p74 = 8'd11;
    end else if ((((tmp_62_reg_1938 == 1'd0) & (tmp_25_reg_1934 == 1'd1) & (trunc_ln9_reg_1929 == 8'd12) & (1'b1 == ap_CS_fsm_state5)) | ((1'b1 == ap_CS_fsm_state5) & (((tmp_80_reg_1962 == 1'd1) & (tmp_58_reg_1958 == 1'd1) & (tmp_24_reg_1950 == 1'd0) & (trunc_ln9_reg_1929 == 8'd11)) | ((tmp_80_reg_1962 == 1'd1) & (tmp_58_reg_1958 == 1'd1) & (tmp_54_reg_1954 == 1'd1) & (trunc_ln9_reg_1929 == 8'd11)))))) begin
        ap_phi_mux_empty_11_phi_fu_268_p74 = 8'd12;
    end else if (((trunc_ln9_reg_1929 == 8'd3) & (1'b1 == ap_CS_fsm_state5))) begin
        ap_phi_mux_empty_11_phi_fu_268_p74 = 8'd4;
    end else if ((((trunc_ln9_reg_1929 == 8'd5) & (1'b1 == ap_CS_fsm_state5) & (tmp_35_reg_2002 == 1'd0) & (tmp_18_reg_1998 == 1'd1)) | ((trunc_ln9_reg_1929 == 8'd4) & (1'b1 == ap_CS_fsm_state5)))) begin
        ap_phi_mux_empty_11_phi_fu_268_p74 = 8'd5;
    end else if (((trunc_ln9_reg_1929 == 8'd6) & (1'b1 == ap_CS_fsm_state5))) begin
        ap_phi_mux_empty_11_phi_fu_268_p74 = 8'd7;
    end else if (((trunc_ln9_reg_1929 == 8'd7) & (1'b1 == ap_CS_fsm_state5))) begin
        ap_phi_mux_empty_11_phi_fu_268_p74 = 8'd8;
    end else if ((((tmp_41_reg_1986 == 1'd0) & (tmp_22_reg_1982 == 1'd1) & (trunc_ln9_reg_1929 == 8'd9) & (1'b1 == ap_CS_fsm_state5)) | ((trunc_ln9_reg_1929 == 8'd8) & (1'b1 == ap_CS_fsm_state5)))) begin
        ap_phi_mux_empty_11_phi_fu_268_p74 = 8'd9;
    end else if (((trunc_ln9_reg_1929 == 8'd13) & (1'b1 == ap_CS_fsm_state5))) begin
        ap_phi_mux_empty_11_phi_fu_268_p74 = 8'd14;
    end else begin
        ap_phi_mux_empty_11_phi_fu_268_p74 = empty_11_reg_257;
    end
end

always @ (*) begin
    if (((tmp_13_reg_1925 == 1'd1) & (tmp_reg_1909 == 1'd1) & (1'b1 == ap_CS_fsm_state4))) begin
        ap_phi_mux_empty_phi_fu_248_p6 = or_ln62_4_fu_778_p3;
    end else begin
        ap_phi_mux_empty_phi_fu_248_p6 = empty_reg_245;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        ap_return = icmp_ln194_fu_1857_p2;
    end else begin
        ap_return = ap_return_preg;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state3) | (1'b1 == ap_CS_fsm_state2) | ((trunc_ln9_reg_1929 == 8'd0) & (start_read_read_fu_220_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state5)) | ((trunc_ln9_reg_1929 == 8'd1) & (1'b1 == ap_CS_fsm_state5) & (tmp_28_reg_2034 == 1'd0) & (tmp_14_reg_2030 == 1'd1)) | ((trunc_ln9_reg_1929 == 8'd2) & (1'b1 == ap_CS_fsm_state5) & (tmp_31_reg_2018 == 1'd0) & (tmp_15_reg_2014 == 1'd1)) | ((trunc_ln9_reg_1929 == 8'd5) & (1'b1 == ap_CS_fsm_state5) & (tmp_35_reg_2002 == 1'd0) & (tmp_18_reg_1998 == 1'd1)) | ((tmp_41_reg_1986 == 1'd0) & (tmp_22_reg_1982 == 1'd1) & (trunc_ln9_reg_1929 == 8'd9) & (1'b1 == ap_CS_fsm_state5)) | ((tmp_47_reg_1970 == 1'd0) & (tmp_23_reg_1966 == 1'd1) & (trunc_ln9_reg_1929 == 8'd10) & (1'b1 == ap_CS_fsm_state5)) | ((tmp_54_reg_1954 == 1'd0) & (tmp_24_reg_1950 == 1'd1) & (trunc_ln9_reg_1929 == 8'd11) & (1'b1 == ap_CS_fsm_state5)) | ((tmp_62_reg_1938 == 1'd0) & (tmp_25_reg_1934 == 1'd1) & (trunc_ln9_reg_1929 == 8'd12) & (1'b1 == ap_CS_fsm_state5)) | ((trunc_ln9_reg_1929 
    == 8'd3) & (1'b1 == ap_CS_fsm_state5)) | ((trunc_ln9_reg_1929 == 8'd4) & (1'b1 == ap_CS_fsm_state5)) | ((trunc_ln9_reg_1929 == 8'd6) & (1'b1 == ap_CS_fsm_state5)) | ((trunc_ln9_reg_1929 == 8'd7) & (1'b1 == ap_CS_fsm_state5)) | ((trunc_ln9_reg_1929 == 8'd8) & (1'b1 == ap_CS_fsm_state5)) | ((trunc_ln9_reg_1929 == 8'd13) & (1'b1 == ap_CS_fsm_state5)) | ((1'b1 == ap_CS_fsm_state5) & (((trunc_ln9_reg_1929 == 8'd1) & (tmp_71_reg_2042 == 1'd1) & (tmp_29_reg_2038 == 1'd1) & (tmp_14_reg_2030 == 1'd0)) | ((trunc_ln9_reg_1929 == 8'd1) & (tmp_71_reg_2042 == 1'd1) & (tmp_29_reg_2038 == 1'd1) & (tmp_28_reg_2034 == 1'd1)))) | ((1'b1 == ap_CS_fsm_state5) & (((trunc_ln9_reg_1929 == 8'd2) & (tmp_74_reg_2026 == 1'd1) & (tmp_32_reg_2022 == 1'd1) & (tmp_15_reg_2014 == 1'd0)) | ((trunc_ln9_reg_1929 == 8'd2) & (tmp_74_reg_2026 == 1'd1) & (tmp_32_reg_2022 == 1'd1) & (tmp_31_reg_2018 == 1'd1)))) | ((1'b1 == ap_CS_fsm_state5) & (((trunc_ln9_reg_1929 == 8'd5) & (tmp_77_reg_2010 == 1'd1) & (tmp_38_reg_2006 == 1'd1) & (tmp_18_reg_1998 == 
    1'd0)) | ((trunc_ln9_reg_1929 == 8'd5) & (tmp_77_reg_2010 == 1'd1) & (tmp_38_reg_2006 == 1'd1) & (tmp_35_reg_2002 == 1'd1)))) | ((1'b1 == ap_CS_fsm_state5) & (((tmp_44_reg_1990 == 1'd1) & (tmp_22_reg_1982 == 1'd0) & (trunc_ln9_reg_1929 == 8'd9) & (tmp_78_reg_1994 == 1'd1)) | ((tmp_44_reg_1990 == 1'd1) & (tmp_41_reg_1986 == 1'd1) & (trunc_ln9_reg_1929 == 8'd9) & (tmp_78_reg_1994 == 1'd1)))) | ((1'b1 == ap_CS_fsm_state5) & (((tmp_79_reg_1978 == 1'd1) & (tmp_50_reg_1974 == 1'd1) & (tmp_23_reg_1966 == 1'd0) & (trunc_ln9_reg_1929 == 8'd10)) | ((tmp_79_reg_1978 == 1'd1) & (tmp_50_reg_1974 == 1'd1) & (tmp_47_reg_1970 == 1'd1) & (trunc_ln9_reg_1929 == 8'd10)))) | ((1'b1 == ap_CS_fsm_state5) & (((tmp_80_reg_1962 == 1'd1) & (tmp_58_reg_1958 == 1'd1) & (tmp_24_reg_1950 == 1'd0) & (trunc_ln9_reg_1929 == 8'd11)) | ((tmp_80_reg_1962 == 1'd1) & (tmp_58_reg_1958 == 1'd1) & (tmp_54_reg_1954 == 1'd1) & (trunc_ln9_reg_1929 == 8'd11)))) | ((1'b1 == ap_CS_fsm_state5) & (((tmp_81_reg_1946 == 1'd1) & (tmp_66_reg_1942 == 1'd1) & (tmp_25_reg_1934 
    == 1'd0) & (trunc_ln9_reg_1929 == 8'd12)) | ((tmp_81_reg_1946 == 1'd1) & (tmp_66_reg_1942 == 1'd1) & (tmp_62_reg_1938 == 1'd1) & (trunc_ln9_reg_1929 == 8'd12)))))) begin
        head_ctx_ref_address0_local = head_ctx_ref_addr_reg_1863;
    end else if ((1'b1 == ap_CS_fsm_state1)) begin
        head_ctx_ref_address0_local = zext_ln47_fu_408_p1;
    end else begin
        head_ctx_ref_address0_local = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state3) | (1'b1 == ap_CS_fsm_state2) | ((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1)) | ((trunc_ln9_reg_1929 == 8'd0) & (start_read_read_fu_220_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state5)) | ((trunc_ln9_reg_1929 == 8'd1) & (1'b1 == ap_CS_fsm_state5) & (tmp_28_reg_2034 == 1'd0) & (tmp_14_reg_2030 == 1'd1)) | ((trunc_ln9_reg_1929 == 8'd2) & (1'b1 == ap_CS_fsm_state5) & (tmp_31_reg_2018 == 1'd0) & (tmp_15_reg_2014 == 1'd1)) | ((trunc_ln9_reg_1929 == 8'd5) & (1'b1 == ap_CS_fsm_state5) & (tmp_35_reg_2002 == 1'd0) & (tmp_18_reg_1998 == 1'd1)) | ((tmp_41_reg_1986 == 1'd0) & (tmp_22_reg_1982 == 1'd1) & (trunc_ln9_reg_1929 == 8'd9) & (1'b1 == ap_CS_fsm_state5)) | ((tmp_47_reg_1970 == 1'd0) & (tmp_23_reg_1966 == 1'd1) & (trunc_ln9_reg_1929 == 8'd10) & (1'b1 == ap_CS_fsm_state5)) | ((tmp_54_reg_1954 == 1'd0) & (tmp_24_reg_1950 == 1'd1) & (trunc_ln9_reg_1929 == 8'd11) & (1'b1 == ap_CS_fsm_state5)) | ((tmp_62_reg_1938 == 1'd0) & (tmp_25_reg_1934 == 1'd1) & (trunc_ln9_reg_1929 
    == 8'd12) & (1'b1 == ap_CS_fsm_state5)) | ((trunc_ln9_reg_1929 == 8'd3) & (1'b1 == ap_CS_fsm_state5)) | ((trunc_ln9_reg_1929 == 8'd4) & (1'b1 == ap_CS_fsm_state5)) | ((trunc_ln9_reg_1929 == 8'd6) & (1'b1 == ap_CS_fsm_state5)) | ((trunc_ln9_reg_1929 == 8'd7) & (1'b1 == ap_CS_fsm_state5)) | ((trunc_ln9_reg_1929 == 8'd8) & (1'b1 == ap_CS_fsm_state5)) | ((trunc_ln9_reg_1929 == 8'd13) & (1'b1 == ap_CS_fsm_state5)) | ((1'b1 == ap_CS_fsm_state5) & (((trunc_ln9_reg_1929 == 8'd1) & (tmp_71_reg_2042 == 1'd1) & (tmp_29_reg_2038 == 1'd1) & (tmp_14_reg_2030 == 1'd0)) | ((trunc_ln9_reg_1929 == 8'd1) & (tmp_71_reg_2042 == 1'd1) & (tmp_29_reg_2038 == 1'd1) & (tmp_28_reg_2034 == 1'd1)))) | ((1'b1 == ap_CS_fsm_state5) & (((trunc_ln9_reg_1929 == 8'd2) & (tmp_74_reg_2026 == 1'd1) & (tmp_32_reg_2022 == 1'd1) & (tmp_15_reg_2014 == 1'd0)) | ((trunc_ln9_reg_1929 == 8'd2) & (tmp_74_reg_2026 == 1'd1) & (tmp_32_reg_2022 == 1'd1) & (tmp_31_reg_2018 == 1'd1)))) | ((1'b1 == ap_CS_fsm_state5) & (((trunc_ln9_reg_1929 == 8'd5) & (tmp_77_reg_2010 
    == 1'd1) & (tmp_38_reg_2006 == 1'd1) & (tmp_18_reg_1998 == 1'd0)) | ((trunc_ln9_reg_1929 == 8'd5) & (tmp_77_reg_2010 == 1'd1) & (tmp_38_reg_2006 == 1'd1) & (tmp_35_reg_2002 == 1'd1)))) | ((1'b1 == ap_CS_fsm_state5) & (((tmp_44_reg_1990 == 1'd1) & (tmp_22_reg_1982 == 1'd0) & (trunc_ln9_reg_1929 == 8'd9) & (tmp_78_reg_1994 == 1'd1)) | ((tmp_44_reg_1990 == 1'd1) & (tmp_41_reg_1986 == 1'd1) & (trunc_ln9_reg_1929 == 8'd9) & (tmp_78_reg_1994 == 1'd1)))) | ((1'b1 == ap_CS_fsm_state5) & (((tmp_79_reg_1978 == 1'd1) & (tmp_50_reg_1974 == 1'd1) & (tmp_23_reg_1966 == 1'd0) & (trunc_ln9_reg_1929 == 8'd10)) | ((tmp_79_reg_1978 == 1'd1) & (tmp_50_reg_1974 == 1'd1) & (tmp_47_reg_1970 == 1'd1) & (trunc_ln9_reg_1929 == 8'd10)))) | ((1'b1 == ap_CS_fsm_state5) & (((tmp_80_reg_1962 == 1'd1) & (tmp_58_reg_1958 == 1'd1) & (tmp_24_reg_1950 == 1'd0) & (trunc_ln9_reg_1929 == 8'd11)) | ((tmp_80_reg_1962 == 1'd1) & (tmp_58_reg_1958 == 1'd1) & (tmp_54_reg_1954 == 1'd1) & (trunc_ln9_reg_1929 == 8'd11)))) | ((1'b1 == ap_CS_fsm_state5) & (((tmp_81_reg_1946 
    == 1'd1) & (tmp_66_reg_1942 == 1'd1) & (tmp_25_reg_1934 == 1'd0) & (trunc_ln9_reg_1929 == 8'd12)) | ((tmp_81_reg_1946 == 1'd1) & (tmp_66_reg_1942 == 1'd1) & (tmp_62_reg_1938 == 1'd1) & (trunc_ln9_reg_1929 == 8'd12)))))) begin
        head_ctx_ref_ce0_local = 1'b1;
    end else begin
        head_ctx_ref_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln9_reg_1929 == 8'd0) & (start_read_read_fu_220_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state5))) begin
        head_ctx_ref_d0_local = shl_ln87_fu_1851_p2;
    end else if (((1'b1 == ap_CS_fsm_state5) & (((trunc_ln9_reg_1929 == 8'd1) & (tmp_71_reg_2042 == 1'd1) & (tmp_29_reg_2038 == 1'd1) & (tmp_14_reg_2030 == 1'd0)) | ((trunc_ln9_reg_1929 == 8'd1) & (tmp_71_reg_2042 == 1'd1) & (tmp_29_reg_2038 == 1'd1) & (tmp_28_reg_2034 == 1'd1))))) begin
        head_ctx_ref_d0_local = shl_ln99_fu_1817_p2;
    end else if (((trunc_ln9_reg_1929 == 8'd1) & (1'b1 == ap_CS_fsm_state5) & (tmp_28_reg_2034 == 1'd0) & (tmp_14_reg_2030 == 1'd1))) begin
        head_ctx_ref_d0_local = shl_ln94_fu_1759_p2;
    end else if (((1'b1 == ap_CS_fsm_state5) & (((trunc_ln9_reg_1929 == 8'd2) & (tmp_74_reg_2026 == 1'd1) & (tmp_32_reg_2022 == 1'd1) & (tmp_15_reg_2014 == 1'd0)) | ((trunc_ln9_reg_1929 == 8'd2) & (tmp_74_reg_2026 == 1'd1) & (tmp_32_reg_2022 == 1'd1) & (tmp_31_reg_2018 == 1'd1))))) begin
        head_ctx_ref_d0_local = shl_ln111_fu_1717_p2;
    end else if (((trunc_ln9_reg_1929 == 8'd2) & (1'b1 == ap_CS_fsm_state5) & (tmp_31_reg_2018 == 1'd0) & (tmp_15_reg_2014 == 1'd1))) begin
        head_ctx_ref_d0_local = shl_ln106_fu_1659_p2;
    end else if (((trunc_ln9_reg_1929 == 8'd3) & (1'b1 == ap_CS_fsm_state5))) begin
        head_ctx_ref_d0_local = shl_ln115_fu_1615_p2;
    end else if (((trunc_ln9_reg_1929 == 8'd4) & (1'b1 == ap_CS_fsm_state5))) begin
        head_ctx_ref_d0_local = shl_ln118_fu_1595_p2;
    end else if (((1'b1 == ap_CS_fsm_state5) & (((trunc_ln9_reg_1929 == 8'd5) & (tmp_77_reg_2010 == 1'd1) & (tmp_38_reg_2006 == 1'd1) & (tmp_18_reg_1998 == 1'd0)) | ((trunc_ln9_reg_1929 == 8'd5) & (tmp_77_reg_2010 == 1'd1) & (tmp_38_reg_2006 == 1'd1) & (tmp_35_reg_2002 == 1'd1))))) begin
        head_ctx_ref_d0_local = shl_ln129_fu_1575_p2;
    end else if (((trunc_ln9_reg_1929 == 8'd5) & (1'b1 == ap_CS_fsm_state5) & (tmp_35_reg_2002 == 1'd0) & (tmp_18_reg_1998 == 1'd1))) begin
        head_ctx_ref_d0_local = shl_ln124_fu_1517_p2;
    end else if (((trunc_ln9_reg_1929 == 8'd6) & (1'b1 == ap_CS_fsm_state5))) begin
        head_ctx_ref_d0_local = shl_ln133_fu_1473_p2;
    end else if (((trunc_ln9_reg_1929 == 8'd7) & (1'b1 == ap_CS_fsm_state5))) begin
        head_ctx_ref_d0_local = shl_ln136_fu_1453_p2;
    end else if (((trunc_ln9_reg_1929 == 8'd8) & (1'b1 == ap_CS_fsm_state5))) begin
        head_ctx_ref_d0_local = shl_ln139_fu_1433_p2;
    end else if (((1'b1 == ap_CS_fsm_state5) & (((tmp_44_reg_1990 == 1'd1) & (tmp_22_reg_1982 == 1'd0) & (trunc_ln9_reg_1929 == 8'd9) & (tmp_78_reg_1994 == 1'd1)) | ((tmp_44_reg_1990 == 1'd1) & (tmp_41_reg_1986 == 1'd1) & (trunc_ln9_reg_1929 == 8'd9) & (tmp_78_reg_1994 == 1'd1))))) begin
        head_ctx_ref_d0_local = shl_ln149_fu_1413_p2;
    end else if (((tmp_41_reg_1986 == 1'd0) & (tmp_22_reg_1982 == 1'd1) & (trunc_ln9_reg_1929 == 8'd9) & (1'b1 == ap_CS_fsm_state5))) begin
        head_ctx_ref_d0_local = shl_ln145_fu_1355_p2;
    end else if (((1'b1 == ap_CS_fsm_state5) & (((tmp_79_reg_1978 == 1'd1) & (tmp_50_reg_1974 == 1'd1) & (tmp_23_reg_1966 == 1'd0) & (trunc_ln9_reg_1929 == 8'd10)) | ((tmp_79_reg_1978 == 1'd1) & (tmp_50_reg_1974 == 1'd1) & (tmp_47_reg_1970 == 1'd1) & (trunc_ln9_reg_1929 == 8'd10))))) begin
        head_ctx_ref_d0_local = shl_ln160_fu_1311_p2;
    end else if (((tmp_47_reg_1970 == 1'd0) & (tmp_23_reg_1966 == 1'd1) & (trunc_ln9_reg_1929 == 8'd10) & (1'b1 == ap_CS_fsm_state5))) begin
        head_ctx_ref_d0_local = shl_ln156_fu_1253_p2;
    end else if (((1'b1 == ap_CS_fsm_state5) & (((tmp_80_reg_1962 == 1'd1) & (tmp_58_reg_1958 == 1'd1) & (tmp_24_reg_1950 == 1'd0) & (trunc_ln9_reg_1929 == 8'd11)) | ((tmp_80_reg_1962 == 1'd1) & (tmp_58_reg_1958 == 1'd1) & (tmp_54_reg_1954 == 1'd1) & (trunc_ln9_reg_1929 == 8'd11))))) begin
        head_ctx_ref_d0_local = shl_ln171_fu_1209_p2;
    end else if (((tmp_54_reg_1954 == 1'd0) & (tmp_24_reg_1950 == 1'd1) & (trunc_ln9_reg_1929 == 8'd11) & (1'b1 == ap_CS_fsm_state5))) begin
        head_ctx_ref_d0_local = shl_ln167_fu_1153_p2;
    end else if (((1'b1 == ap_CS_fsm_state5) & (((tmp_81_reg_1946 == 1'd1) & (tmp_66_reg_1942 == 1'd1) & (tmp_25_reg_1934 == 1'd0) & (trunc_ln9_reg_1929 == 8'd12)) | ((tmp_81_reg_1946 == 1'd1) & (tmp_66_reg_1942 == 1'd1) & (tmp_62_reg_1938 == 1'd1) & (trunc_ln9_reg_1929 == 8'd12))))) begin
        head_ctx_ref_d0_local = shl_ln182_fu_1109_p2;
    end else if (((tmp_62_reg_1938 == 1'd0) & (tmp_25_reg_1934 == 1'd1) & (trunc_ln9_reg_1929 == 8'd12) & (1'b1 == ap_CS_fsm_state5))) begin
        head_ctx_ref_d0_local = shl_ln178_fu_1061_p2;
    end else if (((trunc_ln9_reg_1929 == 8'd13) & (1'b1 == ap_CS_fsm_state5))) begin
        head_ctx_ref_d0_local = shl_ln186_fu_1017_p2;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        head_ctx_ref_d0_local = shl_ln62_1_fu_787_p2;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        head_ctx_ref_d0_local = shl_ln62_fu_763_p2;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        head_ctx_ref_d0_local = shl_ln50_fu_480_p2;
    end else begin
        head_ctx_ref_d0_local = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) | ((or_ln62_5_reg_1921 == 1'd1) & (1'b1 == ap_CS_fsm_state3)) | ((trunc_ln9_reg_1929 == 8'd0) & (start_read_read_fu_220_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state5)) | ((trunc_ln9_reg_1929 == 8'd1) & (1'b1 == ap_CS_fsm_state5) & (tmp_28_reg_2034 == 1'd0) & (tmp_14_reg_2030 == 1'd1)) | ((trunc_ln9_reg_1929 == 8'd2) & (1'b1 == ap_CS_fsm_state5) & (tmp_31_reg_2018 == 1'd0) & (tmp_15_reg_2014 == 1'd1)) | ((trunc_ln9_reg_1929 == 8'd5) & (1'b1 == ap_CS_fsm_state5) & (tmp_35_reg_2002 == 1'd0) & (tmp_18_reg_1998 == 1'd1)) | ((tmp_41_reg_1986 == 1'd0) & (tmp_22_reg_1982 == 1'd1) & (trunc_ln9_reg_1929 == 8'd9) & (1'b1 == ap_CS_fsm_state5)) | ((tmp_47_reg_1970 == 1'd0) & (tmp_23_reg_1966 == 1'd1) & (trunc_ln9_reg_1929 == 8'd10) & (1'b1 == ap_CS_fsm_state5)) | ((tmp_54_reg_1954 == 1'd0) & (tmp_24_reg_1950 == 1'd1) & (trunc_ln9_reg_1929 == 8'd11) & (1'b1 == ap_CS_fsm_state5)) | ((tmp_62_reg_1938 == 1'd0) & (tmp_25_reg_1934 == 1'd1) & (trunc_ln9_reg_1929 == 8'd12) & (1'b1 == ap_CS_fsm_state5)) | ((trunc_ln9_reg_1929 
    == 8'd3) & (1'b1 == ap_CS_fsm_state5)) | ((trunc_ln9_reg_1929 == 8'd4) & (1'b1 == ap_CS_fsm_state5)) | ((trunc_ln9_reg_1929 == 8'd6) & (1'b1 == ap_CS_fsm_state5)) | ((trunc_ln9_reg_1929 == 8'd7) & (1'b1 == ap_CS_fsm_state5)) | ((trunc_ln9_reg_1929 == 8'd8) & (1'b1 == ap_CS_fsm_state5)) | ((trunc_ln9_reg_1929 == 8'd13) & (1'b1 == ap_CS_fsm_state5)) | ((1'b1 == ap_CS_fsm_state5) & (((trunc_ln9_reg_1929 == 8'd1) & (tmp_71_reg_2042 == 1'd1) & (tmp_29_reg_2038 == 1'd1) & (tmp_14_reg_2030 == 1'd0)) | ((trunc_ln9_reg_1929 == 8'd1) & (tmp_71_reg_2042 == 1'd1) & (tmp_29_reg_2038 == 1'd1) & (tmp_28_reg_2034 == 1'd1)))) | ((1'b1 == ap_CS_fsm_state5) & (((trunc_ln9_reg_1929 == 8'd2) & (tmp_74_reg_2026 == 1'd1) & (tmp_32_reg_2022 == 1'd1) & (tmp_15_reg_2014 == 1'd0)) | ((trunc_ln9_reg_1929 == 8'd2) & (tmp_74_reg_2026 == 1'd1) & (tmp_32_reg_2022 == 1'd1) & (tmp_31_reg_2018 == 1'd1)))) | ((1'b1 == ap_CS_fsm_state5) & (((trunc_ln9_reg_1929 == 8'd5) & (tmp_77_reg_2010 == 1'd1) & (tmp_38_reg_2006 == 1'd1) & (tmp_18_reg_1998 == 
    1'd0)) | ((trunc_ln9_reg_1929 == 8'd5) & (tmp_77_reg_2010 == 1'd1) & (tmp_38_reg_2006 == 1'd1) & (tmp_35_reg_2002 == 1'd1)))) | ((1'b1 == ap_CS_fsm_state5) & (((tmp_44_reg_1990 == 1'd1) & (tmp_22_reg_1982 == 1'd0) & (trunc_ln9_reg_1929 == 8'd9) & (tmp_78_reg_1994 == 1'd1)) | ((tmp_44_reg_1990 == 1'd1) & (tmp_41_reg_1986 == 1'd1) & (trunc_ln9_reg_1929 == 8'd9) & (tmp_78_reg_1994 == 1'd1)))) | ((1'b1 == ap_CS_fsm_state5) & (((tmp_79_reg_1978 == 1'd1) & (tmp_50_reg_1974 == 1'd1) & (tmp_23_reg_1966 == 1'd0) & (trunc_ln9_reg_1929 == 8'd10)) | ((tmp_79_reg_1978 == 1'd1) & (tmp_50_reg_1974 == 1'd1) & (tmp_47_reg_1970 == 1'd1) & (trunc_ln9_reg_1929 == 8'd10)))) | ((1'b1 == ap_CS_fsm_state5) & (((tmp_80_reg_1962 == 1'd1) & (tmp_58_reg_1958 == 1'd1) & (tmp_24_reg_1950 == 1'd0) & (trunc_ln9_reg_1929 == 8'd11)) | ((tmp_80_reg_1962 == 1'd1) & (tmp_58_reg_1958 == 1'd1) & (tmp_54_reg_1954 == 1'd1) & (trunc_ln9_reg_1929 == 8'd11)))) | ((1'b1 == ap_CS_fsm_state5) & (((tmp_81_reg_1946 == 1'd1) & (tmp_66_reg_1942 == 1'd1) & (tmp_25_reg_1934 
    == 1'd0) & (trunc_ln9_reg_1929 == 8'd12)) | ((tmp_81_reg_1946 == 1'd1) & (tmp_66_reg_1942 == 1'd1) & (tmp_62_reg_1938 == 1'd1) & (trunc_ln9_reg_1929 == 8'd12)))) | ((tmp_13_reg_1925 == 1'd1) & (tmp_reg_1909 == 1'd1) & (1'b1 == ap_CS_fsm_state4)))) begin
        head_ctx_ref_we0_local = 1'b1;
    end else begin
        head_ctx_ref_we0_local = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((tmp_fu_487_p3 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign and_ln_fu_448_p4 = {{{tmp_1_fu_434_p4}, {9'd0}}, {trunc_ln47_1_fu_444_p1}};

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign grp_fu_380_p3 = ap_phi_mux_empty_phi_fu_248_p6[32'd40];

assign grp_fu_388_p4 = {{empty_reg_245[65:40]}};

assign head_ctx_ref_address0 = head_ctx_ref_address0_local;

assign head_ctx_ref_ce0 = head_ctx_ref_ce0_local;

assign head_ctx_ref_d0 = head_ctx_ref_d0_local;

assign head_ctx_ref_we0 = head_ctx_ref_we0_local;

assign icmp_ln194_fu_1857_p2 = ((ap_phi_mux_empty_11_phi_fu_268_p74 == 8'd14) ? 1'b1 : 1'b0);

assign icmp_ln50_fu_462_p2 = ((trunc_ln50_fu_458_p1 != layer_idx) ? 1'b1 : 1'b0);

assign lshr_ln47_1_fu_398_p4 = {{ctx[5:4]}};

assign lshr_ln47_fu_428_p2 = head_ctx_ref_q0 >> zext_ln47_1_fu_424_p1;

assign or_ln10_fu_1423_p4 = {{{grp_fu_388_p4}, {8'd9}}, {trunc_ln139_fu_1419_p1}};

assign or_ln11_fu_1007_p4 = {{{grp_fu_388_p4}, {8'd14}}, {trunc_ln186_fu_1003_p1}};

assign or_ln12_fu_1837_p4 = {{{tmp_27_fu_1823_p4}, {11'd1}}, {trunc_ln70_fu_1833_p1}};

assign or_ln13_fu_1745_p6 = {{{{{tmp_30_fu_1723_p4}, {1'd1}}, {tmp_70_fu_1733_p3}}, {9'd3}}, {trunc_ln92_fu_1741_p1}};

assign or_ln14_fu_1645_p6 = {{{{{tmp_33_fu_1621_p4}, {1'd1}}, {tmp_34_fu_1631_p4}}, {9'd5}}, {trunc_ln104_fu_1641_p1}};

assign or_ln15_fu_1503_p6 = {{{{{tmp_36_fu_1479_p4}, {1'd1}}, {tmp_37_fu_1489_p4}}, {9'd7}}, {trunc_ln122_fu_1499_p1}};

assign or_ln16_fu_1341_p6 = {{{{{tmp_39_fu_1317_p4}, {1'd1}}, {tmp_40_fu_1327_p4}}, {9'd9}}, {trunc_ln143_fu_1337_p1}};

assign or_ln17_fu_1239_p6 = {{{{{tmp_42_fu_1215_p4}, {1'd1}}, {tmp_43_fu_1225_p4}}, {9'd11}}, {trunc_ln154_fu_1235_p1}};

assign or_ln18_fu_1139_p6 = {{{{{tmp_45_fu_1115_p4}, {1'd1}}, {tmp_46_fu_1125_p4}}, {9'd13}}, {trunc_ln165_fu_1135_p1}};

assign or_ln19_fu_1047_p6 = {{{{{tmp_48_fu_1023_p4}, {1'd1}}, {tmp_49_fu_1033_p4}}, {9'd15}}, {trunc_ln176_fu_1043_p1}};

assign or_ln1_fu_557_p4 = {{{tmp_5_fu_543_p4}, {1'd1}}, {trunc_ln57_fu_553_p1}};

assign or_ln20_fu_1799_p8 = {{{{{{{tmp_51_fu_1765_p4}, {1'd0}}, {tmp_52_fu_1775_p4}}, {1'd0}}, {tmp_53_fu_1785_p4}}, {8'd2}}, {trunc_ln97_fu_1795_p1}};

assign or_ln21_fu_1699_p8 = {{{{{{{tmp_55_fu_1665_p4}, {1'd0}}, {tmp_56_fu_1675_p4}}, {1'd0}}, {tmp_57_fu_1685_p4}}, {8'd3}}, {trunc_ln109_fu_1695_p1}};

assign or_ln22_fu_1557_p8 = {{{{{{{tmp_59_fu_1523_p4}, {1'd0}}, {tmp_60_fu_1533_p4}}, {1'd0}}, {tmp_61_fu_1543_p4}}, {8'd6}}, {trunc_ln127_fu_1553_p1}};

assign or_ln23_fu_1395_p8 = {{{{{{{tmp_63_fu_1361_p4}, {1'd0}}, {tmp_64_fu_1371_p4}}, {1'd0}}, {tmp_65_fu_1381_p4}}, {8'd10}}, {trunc_ln147_fu_1391_p1}};

assign or_ln24_fu_1293_p8 = {{{{{{{tmp_67_fu_1259_p4}, {1'd0}}, {tmp_68_fu_1269_p4}}, {1'd0}}, {tmp_69_fu_1279_p4}}, {8'd11}}, {trunc_ln158_fu_1289_p1}};

assign or_ln25_fu_1191_p8 = {{{{{{{tmp_82_fu_1159_p3}, {1'd0}}, {tmp_72_fu_1167_p4}}, {1'd0}}, {tmp_73_fu_1177_p4}}, {8'd12}}, {trunc_ln169_fu_1187_p1}};

assign or_ln26_fu_1091_p6 = {{{{{tmp_75_fu_1067_p4}, {1'd0}}, {tmp_76_fu_1077_p4}}, {8'd13}}, {trunc_ln180_fu_1087_p1}};

assign or_ln2_fu_597_p4 = {{{tmp_7_fu_583_p4}, {1'd1}}, {trunc_ln58_fu_593_p1}};

assign or_ln3_fu_637_p4 = {{{tmp_9_fu_623_p4}, {1'd1}}, {trunc_ln59_fu_633_p1}};

assign or_ln4_fu_677_p4 = {{{tmp_s_fu_663_p4}, {1'd1}}, {trunc_ln60_fu_673_p1}};

assign or_ln5_fu_715_p4 = {{{tmp_12_fu_703_p3}, {1'd1}}, {trunc_ln61_fu_711_p1}};

assign or_ln62_1_fu_739_p2 = (tmp_4_fu_535_p3 | or_ln62_fu_733_p2);

assign or_ln62_2_fu_745_p2 = (tmp_11_fu_695_p3 | tmp_10_fu_655_p3);

assign or_ln62_3_fu_751_p2 = (tmp_8_fu_615_p3 | or_ln62_2_fu_745_p2);

assign or_ln62_4_fu_778_p3 = {{1'd1}, {trunc_ln62_fu_775_p1}};

assign or_ln62_5_fu_757_p2 = (or_ln62_3_fu_751_p2 | or_ln62_1_fu_739_p2);

assign or_ln62_fu_733_p2 = (tmp_6_fu_575_p3 | tmp_2_fu_495_p3);

assign or_ln6_fu_1605_p4 = {{{grp_fu_388_p4}, {8'd4}}, {trunc_ln115_fu_1601_p1}};

assign or_ln7_fu_1585_p4 = {{{grp_fu_388_p4}, {8'd5}}, {trunc_ln118_fu_1581_p1}};

assign or_ln8_fu_1463_p4 = {{{grp_fu_388_p4}, {8'd7}}, {trunc_ln133_fu_1459_p1}};

assign or_ln9_fu_1443_p4 = {{{grp_fu_388_p4}, {8'd8}}, {trunc_ln136_fu_1439_p1}};

assign or_ln_fu_517_p4 = {{{tmp_3_fu_503_p4}, {1'd1}}, {trunc_ln56_fu_513_p1}};

assign select_ln50_fu_472_p3 = ((icmp_ln50_fu_462_p2[0:0] == 1'b1) ? zext_ln6_fu_468_p1 : and_ln_fu_448_p4);

assign select_ln56_fu_527_p3 = ((tmp_2_fu_495_p3[0:0] == 1'b1) ? or_ln_fu_517_p4 : select_ln50_fu_472_p3);

assign select_ln57_fu_567_p3 = ((tmp_4_fu_535_p3[0:0] == 1'b1) ? or_ln1_fu_557_p4 : select_ln56_fu_527_p3);

assign select_ln58_fu_607_p3 = ((tmp_6_fu_575_p3[0:0] == 1'b1) ? or_ln2_fu_597_p4 : select_ln57_fu_567_p3);

assign select_ln59_fu_647_p3 = ((tmp_8_fu_615_p3[0:0] == 1'b1) ? or_ln3_fu_637_p4 : select_ln58_fu_607_p3);

assign select_ln60_fu_687_p3 = ((tmp_10_fu_655_p3[0:0] == 1'b1) ? or_ln4_fu_677_p4 : select_ln59_fu_647_p3);

assign select_ln61_fu_725_p3 = ((tmp_11_fu_695_p3[0:0] == 1'b1) ? or_ln5_fu_715_p4 : select_ln60_fu_687_p3);

assign shl_ln106_fu_1659_p2 = or_ln14_fu_1645_p6 << zext_ln47_1_reg_1877;

assign shl_ln111_fu_1717_p2 = or_ln21_fu_1699_p8 << zext_ln47_1_reg_1877;

assign shl_ln115_fu_1615_p2 = or_ln6_fu_1605_p4 << zext_ln47_1_reg_1877;

assign shl_ln118_fu_1595_p2 = or_ln7_fu_1585_p4 << zext_ln47_1_reg_1877;

assign shl_ln124_fu_1517_p2 = or_ln15_fu_1503_p6 << zext_ln47_1_reg_1877;

assign shl_ln129_fu_1575_p2 = or_ln22_fu_1557_p8 << zext_ln47_1_reg_1877;

assign shl_ln133_fu_1473_p2 = or_ln8_fu_1463_p4 << zext_ln47_1_reg_1877;

assign shl_ln136_fu_1453_p2 = or_ln9_fu_1443_p4 << zext_ln47_1_reg_1877;

assign shl_ln139_fu_1433_p2 = or_ln10_fu_1423_p4 << zext_ln47_1_reg_1877;

assign shl_ln145_fu_1355_p2 = or_ln16_fu_1341_p6 << zext_ln47_1_reg_1877;

assign shl_ln149_fu_1413_p2 = or_ln23_fu_1395_p8 << zext_ln47_1_reg_1877;

assign shl_ln156_fu_1253_p2 = or_ln17_fu_1239_p6 << zext_ln47_1_reg_1877;

assign shl_ln160_fu_1311_p2 = or_ln24_fu_1293_p8 << zext_ln47_1_reg_1877;

assign shl_ln167_fu_1153_p2 = or_ln18_fu_1139_p6 << zext_ln47_1_reg_1877;

assign shl_ln171_fu_1209_p2 = or_ln25_fu_1191_p8 << zext_ln47_1_reg_1877;

assign shl_ln178_fu_1061_p2 = or_ln19_fu_1047_p6 << zext_ln47_1_reg_1877;

assign shl_ln182_fu_1109_p2 = zext_ln182_fu_1105_p1 << zext_ln47_1_reg_1877;

assign shl_ln186_fu_1017_p2 = or_ln11_fu_1007_p4 << zext_ln47_1_reg_1877;

assign shl_ln50_fu_480_p2 = select_ln50_fu_472_p3 << zext_ln47_1_fu_424_p1;

assign shl_ln62_1_fu_787_p2 = or_ln62_4_fu_778_p3 << zext_ln47_1_reg_1877;

assign shl_ln62_fu_763_p2 = select_ln61_reg_1913 << zext_ln47_1_reg_1877;

assign shl_ln87_fu_1851_p2 = zext_ln87_fu_1847_p1 << zext_ln47_1_reg_1877;

assign shl_ln94_fu_1759_p2 = or_ln13_fu_1745_p6 << zext_ln47_1_reg_1877;

assign shl_ln99_fu_1817_p2 = or_ln20_fu_1799_p8 << zext_ln47_1_reg_1877;

assign shl_ln_fu_417_p3 = {{trunc_ln47_reg_1868}, {3'd0}};

assign start_read_read_fu_220_p2 = start_r;

assign tmp_10_fu_655_p3 = select_ln59_fu_647_p3[32'd56];

assign tmp_11_fu_695_p3 = select_ln60_fu_687_p3[32'd57];

assign tmp_12_fu_703_p3 = select_ln60_fu_687_p3[32'd65];

assign tmp_13_fu_768_p3 = select_ln61_reg_1913[32'd58];

assign tmp_1_fu_434_p4 = {{lshr_ln47_fu_428_p2[65:51]}};

assign tmp_27_fu_1823_p4 = {{empty_reg_245[51:43]}};

assign tmp_28_fu_979_p3 = ap_phi_mux_empty_phi_fu_248_p6[32'd52];

assign tmp_29_fu_987_p3 = ap_phi_mux_empty_phi_fu_248_p6[32'd59];

assign tmp_2_fu_495_p3 = select_ln50_fu_472_p3[32'd52];

assign tmp_30_fu_1723_p4 = {{empty_reg_245[65:53]}};

assign tmp_31_fu_955_p3 = ap_phi_mux_empty_phi_fu_248_p6[32'd53];

assign tmp_32_fu_963_p3 = ap_phi_mux_empty_phi_fu_248_p6[32'd60];

assign tmp_33_fu_1621_p4 = {{empty_reg_245[65:54]}};

assign tmp_34_fu_1631_p4 = {{empty_reg_245[52:51]}};

assign tmp_35_fu_931_p3 = ap_phi_mux_empty_phi_fu_248_p6[32'd54];

assign tmp_36_fu_1479_p4 = {{empty_reg_245[65:55]}};

assign tmp_37_fu_1489_p4 = {{empty_reg_245[53:51]}};

assign tmp_38_fu_939_p3 = ap_phi_mux_empty_phi_fu_248_p6[32'd61];

assign tmp_39_fu_1317_p4 = {{empty_reg_245[65:56]}};

assign tmp_3_fu_503_p4 = {{select_ln50_fu_472_p3[65:60]}};

assign tmp_40_fu_1327_p4 = {{empty_reg_245[54:51]}};

assign tmp_41_fu_907_p3 = ap_phi_mux_empty_phi_fu_248_p6[32'd55];

assign tmp_42_fu_1215_p4 = {{empty_reg_245[65:57]}};

assign tmp_43_fu_1225_p4 = {{empty_reg_245[55:51]}};

assign tmp_44_fu_915_p3 = ap_phi_mux_empty_phi_fu_248_p6[32'd62];

assign tmp_45_fu_1115_p4 = {{empty_reg_245[65:58]}};

assign tmp_46_fu_1125_p4 = {{empty_reg_245[56:51]}};

assign tmp_47_fu_883_p3 = ap_phi_mux_empty_phi_fu_248_p6[32'd56];

assign tmp_48_fu_1023_p4 = {{empty_reg_245[65:59]}};

assign tmp_49_fu_1033_p4 = {{empty_reg_245[57:51]}};

assign tmp_4_fu_535_p3 = select_ln56_fu_527_p3[32'd53];

assign tmp_50_fu_891_p3 = ap_phi_mux_empty_phi_fu_248_p6[32'd63];

assign tmp_51_fu_1765_p4 = {{empty_reg_245[65:60]}};

assign tmp_52_fu_1775_p4 = {{empty_reg_245[58:53]}};

assign tmp_53_fu_1785_p4 = {{empty_reg_245[51:40]}};

assign tmp_54_fu_859_p3 = ap_phi_mux_empty_phi_fu_248_p6[32'd57];

assign tmp_55_fu_1665_p4 = {{empty_reg_245[65:61]}};

assign tmp_56_fu_1675_p4 = {{empty_reg_245[59:54]}};

assign tmp_57_fu_1685_p4 = {{empty_reg_245[52:40]}};

assign tmp_58_fu_867_p3 = ap_phi_mux_empty_phi_fu_248_p6[32'd64];

assign tmp_59_fu_1523_p4 = {{empty_reg_245[65:62]}};

assign tmp_5_fu_543_p4 = {{select_ln56_fu_527_p3[65:61]}};

assign tmp_60_fu_1533_p4 = {{empty_reg_245[60:55]}};

assign tmp_61_fu_1543_p4 = {{empty_reg_245[53:40]}};

assign tmp_62_fu_835_p3 = ap_phi_mux_empty_phi_fu_248_p6[32'd58];

assign tmp_63_fu_1361_p4 = {{empty_reg_245[65:63]}};

assign tmp_64_fu_1371_p4 = {{empty_reg_245[61:56]}};

assign tmp_65_fu_1381_p4 = {{empty_reg_245[54:40]}};

assign tmp_66_fu_843_p3 = ap_phi_mux_empty_phi_fu_248_p6[32'd65];

assign tmp_67_fu_1259_p4 = {{empty_reg_245[65:64]}};

assign tmp_68_fu_1269_p4 = {{empty_reg_245[62:57]}};

assign tmp_69_fu_1279_p4 = {{empty_reg_245[55:40]}};

assign tmp_6_fu_575_p3 = select_ln57_fu_567_p3[32'd54];

assign tmp_70_fu_1733_p3 = empty_reg_245[32'd51];

assign tmp_71_fu_995_p3 = ap_phi_mux_empty_phi_fu_248_p6[32'd52];

assign tmp_72_fu_1167_p4 = {{empty_reg_245[63:58]}};

assign tmp_73_fu_1177_p4 = {{empty_reg_245[56:40]}};

assign tmp_74_fu_971_p3 = ap_phi_mux_empty_phi_fu_248_p6[32'd53];

assign tmp_75_fu_1067_p4 = {{empty_reg_245[64:59]}};

assign tmp_76_fu_1077_p4 = {{empty_reg_245[57:40]}};

assign tmp_77_fu_947_p3 = ap_phi_mux_empty_phi_fu_248_p6[32'd54];

assign tmp_78_fu_923_p3 = ap_phi_mux_empty_phi_fu_248_p6[32'd55];

assign tmp_79_fu_899_p3 = ap_phi_mux_empty_phi_fu_248_p6[32'd56];

assign tmp_7_fu_583_p4 = {{select_ln57_fu_567_p3[65:62]}};

assign tmp_80_fu_875_p3 = ap_phi_mux_empty_phi_fu_248_p6[32'd57];

assign tmp_81_fu_851_p3 = ap_phi_mux_empty_phi_fu_248_p6[32'd58];

assign tmp_82_fu_1159_p3 = empty_reg_245[32'd65];

assign tmp_8_fu_615_p3 = select_ln58_fu_607_p3[32'd55];

assign tmp_9_fu_623_p4 = {{select_ln58_fu_607_p3[65:63]}};

assign tmp_fu_487_p3 = select_ln50_fu_472_p3[32'd41];

assign tmp_s_fu_663_p4 = {{select_ln59_fu_647_p3[65:64]}};

assign trunc_ln104_fu_1641_p1 = empty_reg_245[41:0];

assign trunc_ln109_fu_1695_p1 = empty_reg_245[31:0];

assign trunc_ln115_fu_1601_p1 = empty_reg_245[31:0];

assign trunc_ln118_fu_1581_p1 = empty_reg_245[31:0];

assign trunc_ln122_fu_1499_p1 = empty_reg_245[41:0];

assign trunc_ln127_fu_1553_p1 = empty_reg_245[31:0];

assign trunc_ln133_fu_1459_p1 = empty_reg_245[31:0];

assign trunc_ln136_fu_1439_p1 = empty_reg_245[31:0];

assign trunc_ln139_fu_1419_p1 = empty_reg_245[31:0];

assign trunc_ln143_fu_1337_p1 = empty_reg_245[41:0];

assign trunc_ln147_fu_1391_p1 = empty_reg_245[31:0];

assign trunc_ln154_fu_1235_p1 = empty_reg_245[41:0];

assign trunc_ln158_fu_1289_p1 = empty_reg_245[31:0];

assign trunc_ln165_fu_1135_p1 = empty_reg_245[41:0];

assign trunc_ln169_fu_1187_p1 = empty_reg_245[31:0];

assign trunc_ln176_fu_1043_p1 = empty_reg_245[41:0];

assign trunc_ln180_fu_1087_p1 = empty_reg_245[31:0];

assign trunc_ln186_fu_1003_p1 = empty_reg_245[31:0];

assign trunc_ln47_1_fu_444_p1 = lshr_ln47_fu_428_p2[41:0];

assign trunc_ln47_fu_413_p1 = ctx[3:0];

assign trunc_ln50_fu_458_p1 = lshr_ln47_fu_428_p2[31:0];

assign trunc_ln56_fu_513_p1 = select_ln50_fu_472_p3[58:0];

assign trunc_ln57_fu_553_p1 = select_ln56_fu_527_p3[59:0];

assign trunc_ln58_fu_593_p1 = select_ln57_fu_567_p3[60:0];

assign trunc_ln59_fu_633_p1 = select_ln58_fu_607_p3[61:0];

assign trunc_ln60_fu_673_p1 = select_ln59_fu_647_p3[62:0];

assign trunc_ln61_fu_711_p1 = select_ln60_fu_687_p3[63:0];

assign trunc_ln62_fu_775_p1 = select_ln61_reg_1913[64:0];

assign trunc_ln70_fu_1833_p1 = empty_reg_245[31:0];

assign trunc_ln92_fu_1741_p1 = empty_reg_245[41:0];

assign trunc_ln97_fu_1795_p1 = empty_reg_245[31:0];

assign trunc_ln9_fu_793_p4 = {{ap_phi_mux_empty_phi_fu_248_p6[39:32]}};

assign zext_ln182_fu_1105_p1 = or_ln26_fu_1091_p6;

assign zext_ln47_1_fu_424_p1 = shl_ln_fu_417_p3;

assign zext_ln47_fu_408_p1 = lshr_ln47_1_fu_398_p4;

assign zext_ln6_fu_468_p1 = layer_idx;

assign zext_ln87_fu_1847_p1 = or_ln12_fu_1837_p4;

always @ (posedge ap_clk) begin
    zext_ln47_1_reg_1877[2:0] <= 3'b000;
    zext_ln47_1_reg_1877[65:7] <= 59'b00000000000000000000000000000000000000000000000000000000000;
    select_ln61_reg_1913[50:42] <= 9'b000000000;
    empty_reg_245[50:42] <= 9'b000000000;
end

endmodule //drive_group_head_phase_run_single_head
