-- ==============================================================
-- Generated by Vitis HLS v2025.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity drive_group_head_phase_run_single_head is
port (
    ap_ready : OUT STD_LOGIC;
    p_read : IN STD_LOGIC_VECTOR (65 downto 0);
    layer_idx : IN STD_LOGIC_VECTOR (31 downto 0);
    start_r : IN STD_LOGIC_VECTOR (0 downto 0);
    ap_return_0 : OUT STD_LOGIC_VECTOR (0 downto 0);
    ap_return_1 : OUT STD_LOGIC_VECTOR (65 downto 0);
    ap_rst : IN STD_LOGIC );
end;


architecture behav of drive_group_head_phase_run_single_head is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv8_0 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    constant ap_const_lv8_1 : STD_LOGIC_VECTOR (7 downto 0) := "00000001";
    constant ap_const_lv8_2 : STD_LOGIC_VECTOR (7 downto 0) := "00000010";
    constant ap_const_lv8_3 : STD_LOGIC_VECTOR (7 downto 0) := "00000011";
    constant ap_const_lv8_4 : STD_LOGIC_VECTOR (7 downto 0) := "00000100";
    constant ap_const_lv8_5 : STD_LOGIC_VECTOR (7 downto 0) := "00000101";
    constant ap_const_lv8_6 : STD_LOGIC_VECTOR (7 downto 0) := "00000110";
    constant ap_const_lv8_7 : STD_LOGIC_VECTOR (7 downto 0) := "00000111";
    constant ap_const_lv8_8 : STD_LOGIC_VECTOR (7 downto 0) := "00001000";
    constant ap_const_lv8_9 : STD_LOGIC_VECTOR (7 downto 0) := "00001001";
    constant ap_const_lv8_A : STD_LOGIC_VECTOR (7 downto 0) := "00001010";
    constant ap_const_lv8_B : STD_LOGIC_VECTOR (7 downto 0) := "00001011";
    constant ap_const_lv8_C : STD_LOGIC_VECTOR (7 downto 0) := "00001100";
    constant ap_const_lv8_D : STD_LOGIC_VECTOR (7 downto 0) := "00001101";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv8_E : STD_LOGIC_VECTOR (7 downto 0) := "00001110";
    constant ap_const_lv32_28 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000101000";
    constant ap_const_lv32_41 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001000001";
    constant ap_const_lv32_3B : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000111011";
    constant ap_const_lv32_3A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000111010";
    constant ap_const_lv32_39 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000111001";
    constant ap_const_lv32_38 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000111000";
    constant ap_const_lv32_37 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000110111";
    constant ap_const_lv32_36 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000110110";
    constant ap_const_lv32_35 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000110101";
    constant ap_const_lv32_33 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000110011";
    constant ap_const_lv9_0 : STD_LOGIC_VECTOR (8 downto 0) := "000000000";
    constant ap_const_lv32_29 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000101001";
    constant ap_const_lv32_34 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000110100";
    constant ap_const_lv32_3C : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000111100";
    constant ap_const_lv32_3D : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000111101";
    constant ap_const_lv32_3E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000111110";
    constant ap_const_lv32_3F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000111111";
    constant ap_const_lv32_40 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001000000";
    constant ap_const_lv32_20 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000100000";
    constant ap_const_lv32_27 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000100111";
    constant ap_const_lv9_F : STD_LOGIC_VECTOR (8 downto 0) := "000001111";
    constant ap_const_lv9_D : STD_LOGIC_VECTOR (8 downto 0) := "000001101";
    constant ap_const_lv9_B : STD_LOGIC_VECTOR (8 downto 0) := "000001011";
    constant ap_const_lv9_9 : STD_LOGIC_VECTOR (8 downto 0) := "000001001";
    constant ap_const_lv9_7 : STD_LOGIC_VECTOR (8 downto 0) := "000000111";
    constant ap_const_lv9_5 : STD_LOGIC_VECTOR (8 downto 0) := "000000101";
    constant ap_const_lv9_3 : STD_LOGIC_VECTOR (8 downto 0) := "000000011";
    constant ap_const_lv32_2B : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000101011";
    constant ap_const_lv11_1 : STD_LOGIC_VECTOR (10 downto 0) := "00000000001";
    constant ap_const_logic_0 : STD_LOGIC := '0';

attribute shreg_extract : string;
    signal head_ctx_ref_0_1_fu_865_p9 : STD_LOGIC_VECTOR (65 downto 0);
    signal ap_phi_mux_head_ctx_ref_0_2_phi_fu_225_p74 : STD_LOGIC_VECTOR (65 downto 0);
    signal trunc_ln9_fu_930_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal or_ln11_fu_979_p4 : STD_LOGIC_VECTOR (65 downto 0);
    signal or_ln19_fu_1012_p6 : STD_LOGIC_VECTOR (65 downto 0);
    signal grp_fu_425_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_62_fu_990_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln18_fu_1094_p6 : STD_LOGIC_VECTOR (65 downto 0);
    signal tmp_56_fu_1072_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln17_fu_1176_p6 : STD_LOGIC_VECTOR (65 downto 0);
    signal tmp_50_fu_1154_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln16_fu_1258_p6 : STD_LOGIC_VECTOR (65 downto 0);
    signal tmp_44_fu_1236_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln10_fu_1322_p4 : STD_LOGIC_VECTOR (65 downto 0);
    signal or_ln9_fu_1337_p4 : STD_LOGIC_VECTOR (65 downto 0);
    signal or_ln8_fu_1352_p4 : STD_LOGIC_VECTOR (65 downto 0);
    signal or_ln15_fu_1385_p6 : STD_LOGIC_VECTOR (65 downto 0);
    signal tmp_38_fu_1363_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln7_fu_1449_p4 : STD_LOGIC_VECTOR (65 downto 0);
    signal or_ln6_fu_1464_p4 : STD_LOGIC_VECTOR (65 downto 0);
    signal or_ln14_fu_1497_p6 : STD_LOGIC_VECTOR (65 downto 0);
    signal tmp_32_fu_1475_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln13_fu_1577_p6 : STD_LOGIC_VECTOR (65 downto 0);
    signal tmp_29_fu_1557_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal zext_ln88_fu_1661_p1 : STD_LOGIC_VECTOR (65 downto 0);
    signal start_read_read_fu_204_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln26_fu_1057_p6 : STD_LOGIC_VECTOR (65 downto 0);
    signal tmp_65_fu_1027_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_77_fu_1035_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln25_fu_1139_p6 : STD_LOGIC_VECTOR (65 downto 0);
    signal tmp_59_fu_1109_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_76_fu_1117_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln24_fu_1221_p6 : STD_LOGIC_VECTOR (65 downto 0);
    signal tmp_53_fu_1191_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_75_fu_1199_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln23_fu_1303_p6 : STD_LOGIC_VECTOR (65 downto 0);
    signal tmp_47_fu_1273_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_74_fu_1281_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln22_fu_1430_p6 : STD_LOGIC_VECTOR (65 downto 0);
    signal tmp_41_fu_1400_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_73_fu_1408_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln21_fu_1542_p6 : STD_LOGIC_VECTOR (65 downto 0);
    signal tmp_35_fu_1512_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_72_fu_1520_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln20_fu_1622_p6 : STD_LOGIC_VECTOR (65 downto 0);
    signal tmp_31_fu_1592_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_71_fu_1600_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_phi_mux_empty_phi_fu_304_p74 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_fu_901_p9 : STD_LOGIC_VECTOR (65 downto 0);
    signal tmp_1_fu_495_p4 : STD_LOGIC_VECTOR (14 downto 0);
    signal trunc_ln47_fu_505_p1 : STD_LOGIC_VECTOR (41 downto 0);
    signal trunc_ln50_fu_519_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal icmp_ln50_fu_523_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal zext_ln6_fu_529_p1 : STD_LOGIC_VECTOR (65 downto 0);
    signal and_ln_fu_509_p4 : STD_LOGIC_VECTOR (65 downto 0);
    signal select_ln50_fu_533_p3 : STD_LOGIC_VECTOR (65 downto 0);
    signal tmp_3_fu_557_p4 : STD_LOGIC_VECTOR (5 downto 0);
    signal trunc_ln56_fu_567_p1 : STD_LOGIC_VECTOR (58 downto 0);
    signal tmp_4_fu_549_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln_fu_571_p4 : STD_LOGIC_VECTOR (65 downto 0);
    signal select_ln56_fu_581_p3 : STD_LOGIC_VECTOR (65 downto 0);
    signal tmp_5_fu_597_p4 : STD_LOGIC_VECTOR (4 downto 0);
    signal trunc_ln57_fu_607_p1 : STD_LOGIC_VECTOR (59 downto 0);
    signal tmp_6_fu_589_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln1_fu_611_p4 : STD_LOGIC_VECTOR (65 downto 0);
    signal select_ln57_fu_621_p3 : STD_LOGIC_VECTOR (65 downto 0);
    signal tmp_7_fu_637_p4 : STD_LOGIC_VECTOR (3 downto 0);
    signal trunc_ln58_fu_647_p1 : STD_LOGIC_VECTOR (60 downto 0);
    signal tmp_8_fu_629_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln2_fu_651_p4 : STD_LOGIC_VECTOR (65 downto 0);
    signal select_ln58_fu_661_p3 : STD_LOGIC_VECTOR (65 downto 0);
    signal tmp_9_fu_677_p4 : STD_LOGIC_VECTOR (2 downto 0);
    signal trunc_ln59_fu_687_p1 : STD_LOGIC_VECTOR (61 downto 0);
    signal tmp_10_fu_669_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln3_fu_691_p4 : STD_LOGIC_VECTOR (65 downto 0);
    signal select_ln59_fu_701_p3 : STD_LOGIC_VECTOR (65 downto 0);
    signal tmp_s_fu_717_p4 : STD_LOGIC_VECTOR (1 downto 0);
    signal trunc_ln60_fu_727_p1 : STD_LOGIC_VECTOR (62 downto 0);
    signal tmp_12_fu_709_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln4_fu_731_p4 : STD_LOGIC_VECTOR (65 downto 0);
    signal select_ln60_fu_741_p3 : STD_LOGIC_VECTOR (65 downto 0);
    signal tmp_14_fu_757_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln61_fu_765_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal tmp_13_fu_749_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln5_fu_769_p4 : STD_LOGIC_VECTOR (65 downto 0);
    signal or_ln62_fu_787_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln62_2_fu_799_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln62_3_fu_805_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln62_1_fu_793_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln62_5_fu_811_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln61_fu_779_p3 : STD_LOGIC_VECTOR (65 downto 0);
    signal trunc_ln62_fu_833_p1 : STD_LOGIC_VECTOR (64 downto 0);
    signal tmp_2_fu_541_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_15_fu_825_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln62_fu_845_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln55_fu_851_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln62_4_fu_837_p3 : STD_LOGIC_VECTOR (65 downto 0);
    signal head_ctx_ref_0_1_fu_865_p6 : STD_LOGIC_VECTOR (65 downto 0);
    signal head_ctx_ref_0_1_fu_865_p7 : STD_LOGIC_VECTOR (65 downto 0);
    signal sel_tmp2_fu_857_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_fu_901_p7 : STD_LOGIC_VECTOR (65 downto 0);
    signal grp_fu_416_p4 : STD_LOGIC_VECTOR (25 downto 0);
    signal trunc_ln178_fu_975_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_432_p4 : STD_LOGIC_VECTOR (6 downto 0);
    signal tmp_49_fu_998_p4 : STD_LOGIC_VECTOR (6 downto 0);
    signal trunc_ln169_fu_1008_p1 : STD_LOGIC_VECTOR (41 downto 0);
    signal tmp_70_fu_1043_p4 : STD_LOGIC_VECTOR (17 downto 0);
    signal trunc_ln173_fu_1053_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_441_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_46_fu_1080_p4 : STD_LOGIC_VECTOR (5 downto 0);
    signal trunc_ln159_fu_1090_p1 : STD_LOGIC_VECTOR (41 downto 0);
    signal tmp_67_fu_1125_p4 : STD_LOGIC_VECTOR (16 downto 0);
    signal trunc_ln163_fu_1135_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_450_p4 : STD_LOGIC_VECTOR (8 downto 0);
    signal tmp_43_fu_1162_p4 : STD_LOGIC_VECTOR (4 downto 0);
    signal trunc_ln149_fu_1172_p1 : STD_LOGIC_VECTOR (41 downto 0);
    signal tmp_64_fu_1207_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln153_fu_1217_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_459_p4 : STD_LOGIC_VECTOR (9 downto 0);
    signal tmp_40_fu_1244_p4 : STD_LOGIC_VECTOR (3 downto 0);
    signal trunc_ln139_fu_1254_p1 : STD_LOGIC_VECTOR (41 downto 0);
    signal tmp_61_fu_1289_p4 : STD_LOGIC_VECTOR (14 downto 0);
    signal trunc_ln143_fu_1299_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal trunc_ln135_fu_1318_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal trunc_ln132_fu_1333_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal trunc_ln129_fu_1348_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_468_p4 : STD_LOGIC_VECTOR (10 downto 0);
    signal tmp_37_fu_1371_p4 : STD_LOGIC_VECTOR (2 downto 0);
    signal trunc_ln119_fu_1381_p1 : STD_LOGIC_VECTOR (41 downto 0);
    signal tmp_58_fu_1416_p4 : STD_LOGIC_VECTOR (13 downto 0);
    signal trunc_ln124_fu_1426_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal trunc_ln115_fu_1445_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal trunc_ln112_fu_1460_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_477_p4 : STD_LOGIC_VECTOR (11 downto 0);
    signal tmp_34_fu_1483_p4 : STD_LOGIC_VECTOR (1 downto 0);
    signal trunc_ln103_fu_1493_p1 : STD_LOGIC_VECTOR (41 downto 0);
    signal tmp_55_fu_1528_p4 : STD_LOGIC_VECTOR (12 downto 0);
    signal trunc_ln108_fu_1538_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_486_p4 : STD_LOGIC_VECTOR (12 downto 0);
    signal tmp_68_fu_1565_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln92_fu_1573_p1 : STD_LOGIC_VECTOR (41 downto 0);
    signal tmp_52_fu_1608_p4 : STD_LOGIC_VECTOR (11 downto 0);
    signal trunc_ln97_fu_1618_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_28_fu_1637_p4 : STD_LOGIC_VECTOR (8 downto 0);
    signal trunc_ln70_fu_1647_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal or_ln12_fu_1651_p4 : STD_LOGIC_VECTOR (51 downto 0);
    signal icmp_ln186_fu_1666_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal head_ctx_ref_0_1_fu_865_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal head_ctx_ref_0_1_fu_865_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal head_ctx_ref_0_1_fu_865_p5 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_fu_901_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_fu_901_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_fu_901_p5 : STD_LOGIC_VECTOR (1 downto 0);
    signal ap_ce_reg : STD_LOGIC;

    component drive_group_head_phase_sparsemux_7_2_66_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        CASE0 : STD_LOGIC_VECTOR (1 downto 0);
        din0_WIDTH : INTEGER;
        CASE1 : STD_LOGIC_VECTOR (1 downto 0);
        din1_WIDTH : INTEGER;
        CASE2 : STD_LOGIC_VECTOR (1 downto 0);
        din2_WIDTH : INTEGER;
        def_WIDTH : INTEGER;
        sel_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (65 downto 0);
        din1 : IN STD_LOGIC_VECTOR (65 downto 0);
        din2 : IN STD_LOGIC_VECTOR (65 downto 0);
        def : IN STD_LOGIC_VECTOR (65 downto 0);
        sel : IN STD_LOGIC_VECTOR (1 downto 0);
        dout : OUT STD_LOGIC_VECTOR (65 downto 0) );
    end component;



begin
    sparsemux_7_2_66_1_1_U1 : component drive_group_head_phase_sparsemux_7_2_66_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        CASE0 => "10",
        din0_WIDTH => 66,
        CASE1 => "01",
        din1_WIDTH => 66,
        CASE2 => "00",
        din2_WIDTH => 66,
        def_WIDTH => 66,
        sel_WIDTH => 2,
        dout_WIDTH => 66)
    port map (
        din0 => or_ln62_4_fu_837_p3,
        din1 => select_ln50_fu_533_p3,
        din2 => head_ctx_ref_0_1_fu_865_p6,
        def => head_ctx_ref_0_1_fu_865_p7,
        sel => sel_tmp2_fu_857_p3,
        dout => head_ctx_ref_0_1_fu_865_p9);

    sparsemux_7_2_66_1_1_U2 : component drive_group_head_phase_sparsemux_7_2_66_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        CASE0 => "10",
        din0_WIDTH => 66,
        CASE1 => "01",
        din1_WIDTH => 66,
        CASE2 => "00",
        din2_WIDTH => 66,
        def_WIDTH => 66,
        sel_WIDTH => 2,
        dout_WIDTH => 66)
    port map (
        din0 => or_ln62_4_fu_837_p3,
        din1 => select_ln50_fu_533_p3,
        din2 => select_ln61_fu_779_p3,
        def => tmp_fu_901_p7,
        sel => sel_tmp2_fu_857_p3,
        dout => tmp_fu_901_p9);




    and_ln62_fu_845_p2 <= (tmp_2_fu_541_p3 and tmp_15_fu_825_p3);
    and_ln_fu_509_p4 <= ((tmp_1_fu_495_p4 & ap_const_lv9_0) & trunc_ln47_fu_505_p1);

    ap_phi_mux_empty_phi_fu_304_p74_assign_proc : process(trunc_ln9_fu_930_p4, grp_fu_425_p3, tmp_62_fu_990_p3, tmp_56_fu_1072_p3, tmp_50_fu_1154_p3, tmp_44_fu_1236_p3, tmp_38_fu_1363_p3, tmp_32_fu_1475_p3, tmp_29_fu_1557_p3, start_read_read_fu_204_p2, tmp_65_fu_1027_p3, tmp_77_fu_1035_p3, tmp_59_fu_1109_p3, tmp_76_fu_1117_p3, tmp_53_fu_1191_p3, tmp_75_fu_1199_p3, tmp_47_fu_1273_p3, tmp_74_fu_1281_p3, tmp_41_fu_1400_p3, tmp_73_fu_1408_p3, tmp_35_fu_1512_p3, tmp_72_fu_1520_p3, tmp_31_fu_1592_p3, tmp_71_fu_1600_p3, tmp_fu_901_p9)
    begin
        if ((((tmp_72_fu_1520_p3 = ap_const_lv1_1) and (tmp_35_fu_1512_p3 = ap_const_lv1_1) and (trunc_ln9_fu_930_p4 = ap_const_lv8_2) and (tmp_32_fu_1475_p3 = ap_const_lv1_1)) or ((grp_fu_425_p3 = ap_const_lv1_0) and (tmp_72_fu_1520_p3 = ap_const_lv1_1) and (tmp_35_fu_1512_p3 = ap_const_lv1_1) and (trunc_ln9_fu_930_p4 = ap_const_lv8_2)))) then 
            ap_phi_mux_empty_phi_fu_304_p74 <= ap_const_lv8_3;
        elsif ((((tmp_73_fu_1408_p3 = ap_const_lv1_1) and (tmp_41_fu_1400_p3 = ap_const_lv1_1) and (trunc_ln9_fu_930_p4 = ap_const_lv8_5) and (tmp_38_fu_1363_p3 = ap_const_lv1_1)) or ((grp_fu_425_p3 = ap_const_lv1_0) and (tmp_73_fu_1408_p3 = ap_const_lv1_1) and (tmp_41_fu_1400_p3 = ap_const_lv1_1) and (trunc_ln9_fu_930_p4 = ap_const_lv8_5)))) then 
            ap_phi_mux_empty_phi_fu_304_p74 <= ap_const_lv8_6;
        elsif ((((grp_fu_425_p3 = ap_const_lv1_0) and (trunc_ln9_fu_930_p4 = ap_const_lv8_C) and (tmp_77_fu_1035_p3 = ap_const_lv1_1) and (tmp_65_fu_1027_p3 = ap_const_lv1_1)) or ((tmp_62_fu_990_p3 = ap_const_lv1_1) and (trunc_ln9_fu_930_p4 = ap_const_lv8_C) and (tmp_77_fu_1035_p3 = ap_const_lv1_1) and (tmp_65_fu_1027_p3 = ap_const_lv1_1)))) then 
            ap_phi_mux_empty_phi_fu_304_p74 <= ap_const_lv8_D;
        elsif (((trunc_ln9_fu_930_p4 = ap_const_lv8_0) and (start_read_read_fu_204_p2 = ap_const_lv1_0))) then 
            ap_phi_mux_empty_phi_fu_304_p74 <= ap_const_lv8_0;
        elsif ((((grp_fu_425_p3 = ap_const_lv1_1) and (trunc_ln9_fu_930_p4 = ap_const_lv8_1) and (tmp_29_fu_1557_p3 = ap_const_lv1_0)) or ((tmp_31_fu_1592_p3 = ap_const_lv1_0) and (trunc_ln9_fu_930_p4 = ap_const_lv8_1) and (tmp_29_fu_1557_p3 = ap_const_lv1_1)) or ((tmp_71_fu_1600_p3 = ap_const_lv1_0) and (tmp_31_fu_1592_p3 = ap_const_lv1_1) and (trunc_ln9_fu_930_p4 = ap_const_lv8_1) and (tmp_29_fu_1557_p3 = ap_const_lv1_1)) or ((trunc_ln9_fu_930_p4 = ap_const_lv8_0) and (start_read_read_fu_204_p2 = ap_const_lv1_1)) or ((grp_fu_425_p3 = ap_const_lv1_0) and (tmp_31_fu_1592_p3 = ap_const_lv1_0) and (trunc_ln9_fu_930_p4 = ap_const_lv8_1)) or ((grp_fu_425_p3 = ap_const_lv1_0) and (tmp_71_fu_1600_p3 = ap_const_lv1_0) and (tmp_31_fu_1592_p3 = ap_const_lv1_1) and (trunc_ln9_fu_930_p4 = ap_const_lv8_1)))) then 
            ap_phi_mux_empty_phi_fu_304_p74 <= ap_const_lv8_1;
        elsif ((((grp_fu_425_p3 = ap_const_lv1_1) and (trunc_ln9_fu_930_p4 = ap_const_lv8_2) and (tmp_32_fu_1475_p3 = ap_const_lv1_0)) or ((tmp_71_fu_1600_p3 = ap_const_lv1_1) and (tmp_31_fu_1592_p3 = ap_const_lv1_1) and (trunc_ln9_fu_930_p4 = ap_const_lv8_1) and (tmp_29_fu_1557_p3 = ap_const_lv1_1)) or ((tmp_35_fu_1512_p3 = ap_const_lv1_0) and (trunc_ln9_fu_930_p4 = ap_const_lv8_2) and (tmp_32_fu_1475_p3 = ap_const_lv1_1)) or ((tmp_72_fu_1520_p3 = ap_const_lv1_0) and (tmp_35_fu_1512_p3 = ap_const_lv1_1) and (trunc_ln9_fu_930_p4 = ap_const_lv8_2) and (tmp_32_fu_1475_p3 = ap_const_lv1_1)) or ((grp_fu_425_p3 = ap_const_lv1_0) and (tmp_71_fu_1600_p3 = ap_const_lv1_1) and (tmp_31_fu_1592_p3 = ap_const_lv1_1) and (trunc_ln9_fu_930_p4 = ap_const_lv8_1)) or ((grp_fu_425_p3 = ap_const_lv1_0) and (tmp_35_fu_1512_p3 = ap_const_lv1_0) and (trunc_ln9_fu_930_p4 = ap_const_lv8_2)) or ((grp_fu_425_p3 = ap_const_lv1_0) and (tmp_72_fu_1520_p3 = ap_const_lv1_0) and (tmp_35_fu_1512_p3 = ap_const_lv1_1) and (trunc_ln9_fu_930_p4 = ap_const_lv8_2)))) then 
            ap_phi_mux_empty_phi_fu_304_p74 <= ap_const_lv8_2;
        elsif ((trunc_ln9_fu_930_p4 = ap_const_lv8_3)) then 
            ap_phi_mux_empty_phi_fu_304_p74 <= ap_const_lv8_4;
        elsif (((trunc_ln9_fu_930_p4 = ap_const_lv8_4) or ((grp_fu_425_p3 = ap_const_lv1_1) and (trunc_ln9_fu_930_p4 = ap_const_lv8_5) and (tmp_38_fu_1363_p3 = ap_const_lv1_0)) or ((tmp_41_fu_1400_p3 = ap_const_lv1_0) and (trunc_ln9_fu_930_p4 = ap_const_lv8_5) and (tmp_38_fu_1363_p3 = ap_const_lv1_1)) or ((tmp_73_fu_1408_p3 = ap_const_lv1_0) and (tmp_41_fu_1400_p3 = ap_const_lv1_1) and (trunc_ln9_fu_930_p4 = ap_const_lv8_5) and (tmp_38_fu_1363_p3 = ap_const_lv1_1)) or ((grp_fu_425_p3 = ap_const_lv1_0) and (tmp_41_fu_1400_p3 = ap_const_lv1_0) and (trunc_ln9_fu_930_p4 = ap_const_lv8_5)) or ((grp_fu_425_p3 = ap_const_lv1_0) and (tmp_73_fu_1408_p3 = ap_const_lv1_0) and (tmp_41_fu_1400_p3 = ap_const_lv1_1) and (trunc_ln9_fu_930_p4 = ap_const_lv8_5)))) then 
            ap_phi_mux_empty_phi_fu_304_p74 <= ap_const_lv8_5;
        elsif ((trunc_ln9_fu_930_p4 = ap_const_lv8_6)) then 
            ap_phi_mux_empty_phi_fu_304_p74 <= ap_const_lv8_7;
        elsif ((trunc_ln9_fu_930_p4 = ap_const_lv8_7)) then 
            ap_phi_mux_empty_phi_fu_304_p74 <= ap_const_lv8_8;
        elsif (((trunc_ln9_fu_930_p4 = ap_const_lv8_8) or ((tmp_44_fu_1236_p3 = ap_const_lv1_0) and (grp_fu_425_p3 = ap_const_lv1_1) and (trunc_ln9_fu_930_p4 = ap_const_lv8_9)) or ((tmp_44_fu_1236_p3 = ap_const_lv1_1) and (tmp_47_fu_1273_p3 = ap_const_lv1_0) and (trunc_ln9_fu_930_p4 = ap_const_lv8_9)) or ((tmp_44_fu_1236_p3 = ap_const_lv1_1) and (tmp_74_fu_1281_p3 = ap_const_lv1_0) and (tmp_47_fu_1273_p3 = ap_const_lv1_1) and (trunc_ln9_fu_930_p4 = ap_const_lv8_9)) or ((grp_fu_425_p3 = ap_const_lv1_0) and (tmp_47_fu_1273_p3 = ap_const_lv1_0) and (trunc_ln9_fu_930_p4 = ap_const_lv8_9)) or ((grp_fu_425_p3 = ap_const_lv1_0) and (tmp_74_fu_1281_p3 = ap_const_lv1_0) and (tmp_47_fu_1273_p3 = ap_const_lv1_1) and (trunc_ln9_fu_930_p4 = ap_const_lv8_9)))) then 
            ap_phi_mux_empty_phi_fu_304_p74 <= ap_const_lv8_9;
        elsif ((((tmp_50_fu_1154_p3 = ap_const_lv1_0) and (grp_fu_425_p3 = ap_const_lv1_1) and (trunc_ln9_fu_930_p4 = ap_const_lv8_A)) or ((tmp_44_fu_1236_p3 = ap_const_lv1_1) and (tmp_74_fu_1281_p3 = ap_const_lv1_1) and (tmp_47_fu_1273_p3 = ap_const_lv1_1) and (trunc_ln9_fu_930_p4 = ap_const_lv8_9)) or ((tmp_50_fu_1154_p3 = ap_const_lv1_1) and (tmp_53_fu_1191_p3 = ap_const_lv1_0) and (trunc_ln9_fu_930_p4 = ap_const_lv8_A)) or ((tmp_50_fu_1154_p3 = ap_const_lv1_1) and (tmp_75_fu_1199_p3 = ap_const_lv1_0) and (tmp_53_fu_1191_p3 = ap_const_lv1_1) and (trunc_ln9_fu_930_p4 = ap_const_lv8_A)) or ((grp_fu_425_p3 = ap_const_lv1_0) and (tmp_74_fu_1281_p3 = ap_const_lv1_1) and (tmp_47_fu_1273_p3 = ap_const_lv1_1) and (trunc_ln9_fu_930_p4 = ap_const_lv8_9)) or ((grp_fu_425_p3 = ap_const_lv1_0) and (tmp_53_fu_1191_p3 = ap_const_lv1_0) and (trunc_ln9_fu_930_p4 = ap_const_lv8_A)) or ((grp_fu_425_p3 = ap_const_lv1_0) and (tmp_75_fu_1199_p3 = ap_const_lv1_0) and (tmp_53_fu_1191_p3 = ap_const_lv1_1) and (trunc_ln9_fu_930_p4 = ap_const_lv8_A)))) then 
            ap_phi_mux_empty_phi_fu_304_p74 <= ap_const_lv8_A;
        elsif ((((tmp_56_fu_1072_p3 = ap_const_lv1_0) and (grp_fu_425_p3 = ap_const_lv1_1) and (trunc_ln9_fu_930_p4 = ap_const_lv8_B)) or ((tmp_50_fu_1154_p3 = ap_const_lv1_1) and (tmp_75_fu_1199_p3 = ap_const_lv1_1) and (tmp_53_fu_1191_p3 = ap_const_lv1_1) and (trunc_ln9_fu_930_p4 = ap_const_lv8_A)) or ((tmp_56_fu_1072_p3 = ap_const_lv1_1) and (trunc_ln9_fu_930_p4 = ap_const_lv8_B) and (tmp_59_fu_1109_p3 = ap_const_lv1_0)) or ((tmp_56_fu_1072_p3 = ap_const_lv1_1) and (tmp_76_fu_1117_p3 = ap_const_lv1_0) and (trunc_ln9_fu_930_p4 = ap_const_lv8_B) and (tmp_59_fu_1109_p3 = ap_const_lv1_1)) or ((grp_fu_425_p3 = ap_const_lv1_0) and (trunc_ln9_fu_930_p4 = ap_const_lv8_B) and (tmp_59_fu_1109_p3 = ap_const_lv1_0)) or ((grp_fu_425_p3 = ap_const_lv1_0) and (tmp_75_fu_1199_p3 = ap_const_lv1_1) and (tmp_53_fu_1191_p3 = ap_const_lv1_1) and (trunc_ln9_fu_930_p4 = ap_const_lv8_A)) or ((grp_fu_425_p3 = ap_const_lv1_0) and (tmp_76_fu_1117_p3 = ap_const_lv1_0) and (trunc_ln9_fu_930_p4 = ap_const_lv8_B) and (tmp_59_fu_1109_p3 = ap_const_lv1_1)))) then 
            ap_phi_mux_empty_phi_fu_304_p74 <= ap_const_lv8_B;
        elsif ((((tmp_62_fu_990_p3 = ap_const_lv1_0) and (grp_fu_425_p3 = ap_const_lv1_1) and (trunc_ln9_fu_930_p4 = ap_const_lv8_C)) or ((tmp_56_fu_1072_p3 = ap_const_lv1_1) and (tmp_76_fu_1117_p3 = ap_const_lv1_1) and (trunc_ln9_fu_930_p4 = ap_const_lv8_B) and (tmp_59_fu_1109_p3 = ap_const_lv1_1)) or ((grp_fu_425_p3 = ap_const_lv1_0) and (trunc_ln9_fu_930_p4 = ap_const_lv8_C) and (tmp_65_fu_1027_p3 = ap_const_lv1_0)) or ((grp_fu_425_p3 = ap_const_lv1_0) and (trunc_ln9_fu_930_p4 = ap_const_lv8_C) and (tmp_77_fu_1035_p3 = ap_const_lv1_0) and (tmp_65_fu_1027_p3 = ap_const_lv1_1)) or ((grp_fu_425_p3 = ap_const_lv1_0) and (tmp_76_fu_1117_p3 = ap_const_lv1_1) and (trunc_ln9_fu_930_p4 = ap_const_lv8_B) and (tmp_59_fu_1109_p3 = ap_const_lv1_1)) or ((tmp_62_fu_990_p3 = ap_const_lv1_1) and (trunc_ln9_fu_930_p4 = ap_const_lv8_C) and (tmp_65_fu_1027_p3 = ap_const_lv1_0)) or ((tmp_62_fu_990_p3 = ap_const_lv1_1) and (trunc_ln9_fu_930_p4 = ap_const_lv8_C) and (tmp_77_fu_1035_p3 = ap_const_lv1_0) and (tmp_65_fu_1027_p3 = ap_const_lv1_1)))) then 
            ap_phi_mux_empty_phi_fu_304_p74 <= ap_const_lv8_C;
        elsif ((trunc_ln9_fu_930_p4 = ap_const_lv8_D)) then 
            ap_phi_mux_empty_phi_fu_304_p74 <= ap_const_lv8_E;
        elsif ((not((trunc_ln9_fu_930_p4 = ap_const_lv8_D)) and not((trunc_ln9_fu_930_p4 = ap_const_lv8_C)) and not((trunc_ln9_fu_930_p4 = ap_const_lv8_B)) and not((trunc_ln9_fu_930_p4 = ap_const_lv8_A)) and not((trunc_ln9_fu_930_p4 = ap_const_lv8_9)) and not((trunc_ln9_fu_930_p4 = ap_const_lv8_8)) and not((trunc_ln9_fu_930_p4 = ap_const_lv8_7)) and not((trunc_ln9_fu_930_p4 = ap_const_lv8_6)) and not((trunc_ln9_fu_930_p4 = ap_const_lv8_5)) and not((trunc_ln9_fu_930_p4 = ap_const_lv8_4)) and not((trunc_ln9_fu_930_p4 = ap_const_lv8_3)) and not((trunc_ln9_fu_930_p4 = ap_const_lv8_2)) and not((trunc_ln9_fu_930_p4 = ap_const_lv8_1)) and not((trunc_ln9_fu_930_p4 = ap_const_lv8_0)))) then 
            ap_phi_mux_empty_phi_fu_304_p74 <= tmp_fu_901_p9(39 downto 32);
        else 
            ap_phi_mux_empty_phi_fu_304_p74 <= "XXXXXXXX";
        end if; 
    end process;


    ap_phi_mux_head_ctx_ref_0_2_phi_fu_225_p74_assign_proc : process(head_ctx_ref_0_1_fu_865_p9, trunc_ln9_fu_930_p4, or_ln11_fu_979_p4, or_ln19_fu_1012_p6, grp_fu_425_p3, tmp_62_fu_990_p3, or_ln18_fu_1094_p6, tmp_56_fu_1072_p3, or_ln17_fu_1176_p6, tmp_50_fu_1154_p3, or_ln16_fu_1258_p6, tmp_44_fu_1236_p3, or_ln10_fu_1322_p4, or_ln9_fu_1337_p4, or_ln8_fu_1352_p4, or_ln15_fu_1385_p6, tmp_38_fu_1363_p3, or_ln7_fu_1449_p4, or_ln6_fu_1464_p4, or_ln14_fu_1497_p6, tmp_32_fu_1475_p3, or_ln13_fu_1577_p6, tmp_29_fu_1557_p3, zext_ln88_fu_1661_p1, start_read_read_fu_204_p2, or_ln26_fu_1057_p6, tmp_65_fu_1027_p3, tmp_77_fu_1035_p3, or_ln25_fu_1139_p6, tmp_59_fu_1109_p3, tmp_76_fu_1117_p3, or_ln24_fu_1221_p6, tmp_53_fu_1191_p3, tmp_75_fu_1199_p3, or_ln23_fu_1303_p6, tmp_47_fu_1273_p3, tmp_74_fu_1281_p3, or_ln22_fu_1430_p6, tmp_41_fu_1400_p3, tmp_73_fu_1408_p3, or_ln21_fu_1542_p6, tmp_35_fu_1512_p3, tmp_72_fu_1520_p3, or_ln20_fu_1622_p6, tmp_31_fu_1592_p3, tmp_71_fu_1600_p3)
    begin
        if ((((tmp_71_fu_1600_p3 = ap_const_lv1_1) and (tmp_31_fu_1592_p3 = ap_const_lv1_1) and (trunc_ln9_fu_930_p4 = ap_const_lv8_1) and (tmp_29_fu_1557_p3 = ap_const_lv1_1)) or ((grp_fu_425_p3 = ap_const_lv1_0) and (tmp_71_fu_1600_p3 = ap_const_lv1_1) and (tmp_31_fu_1592_p3 = ap_const_lv1_1) and (trunc_ln9_fu_930_p4 = ap_const_lv8_1)))) then 
            ap_phi_mux_head_ctx_ref_0_2_phi_fu_225_p74 <= or_ln20_fu_1622_p6;
        elsif ((((tmp_72_fu_1520_p3 = ap_const_lv1_1) and (tmp_35_fu_1512_p3 = ap_const_lv1_1) and (trunc_ln9_fu_930_p4 = ap_const_lv8_2) and (tmp_32_fu_1475_p3 = ap_const_lv1_1)) or ((grp_fu_425_p3 = ap_const_lv1_0) and (tmp_72_fu_1520_p3 = ap_const_lv1_1) and (tmp_35_fu_1512_p3 = ap_const_lv1_1) and (trunc_ln9_fu_930_p4 = ap_const_lv8_2)))) then 
            ap_phi_mux_head_ctx_ref_0_2_phi_fu_225_p74 <= or_ln21_fu_1542_p6;
        elsif ((((tmp_73_fu_1408_p3 = ap_const_lv1_1) and (tmp_41_fu_1400_p3 = ap_const_lv1_1) and (trunc_ln9_fu_930_p4 = ap_const_lv8_5) and (tmp_38_fu_1363_p3 = ap_const_lv1_1)) or ((grp_fu_425_p3 = ap_const_lv1_0) and (tmp_73_fu_1408_p3 = ap_const_lv1_1) and (tmp_41_fu_1400_p3 = ap_const_lv1_1) and (trunc_ln9_fu_930_p4 = ap_const_lv8_5)))) then 
            ap_phi_mux_head_ctx_ref_0_2_phi_fu_225_p74 <= or_ln22_fu_1430_p6;
        elsif ((((tmp_44_fu_1236_p3 = ap_const_lv1_1) and (tmp_74_fu_1281_p3 = ap_const_lv1_1) and (tmp_47_fu_1273_p3 = ap_const_lv1_1) and (trunc_ln9_fu_930_p4 = ap_const_lv8_9)) or ((grp_fu_425_p3 = ap_const_lv1_0) and (tmp_74_fu_1281_p3 = ap_const_lv1_1) and (tmp_47_fu_1273_p3 = ap_const_lv1_1) and (trunc_ln9_fu_930_p4 = ap_const_lv8_9)))) then 
            ap_phi_mux_head_ctx_ref_0_2_phi_fu_225_p74 <= or_ln23_fu_1303_p6;
        elsif ((((tmp_50_fu_1154_p3 = ap_const_lv1_1) and (tmp_75_fu_1199_p3 = ap_const_lv1_1) and (tmp_53_fu_1191_p3 = ap_const_lv1_1) and (trunc_ln9_fu_930_p4 = ap_const_lv8_A)) or ((grp_fu_425_p3 = ap_const_lv1_0) and (tmp_75_fu_1199_p3 = ap_const_lv1_1) and (tmp_53_fu_1191_p3 = ap_const_lv1_1) and (trunc_ln9_fu_930_p4 = ap_const_lv8_A)))) then 
            ap_phi_mux_head_ctx_ref_0_2_phi_fu_225_p74 <= or_ln24_fu_1221_p6;
        elsif ((((tmp_56_fu_1072_p3 = ap_const_lv1_1) and (tmp_76_fu_1117_p3 = ap_const_lv1_1) and (trunc_ln9_fu_930_p4 = ap_const_lv8_B) and (tmp_59_fu_1109_p3 = ap_const_lv1_1)) or ((grp_fu_425_p3 = ap_const_lv1_0) and (tmp_76_fu_1117_p3 = ap_const_lv1_1) and (trunc_ln9_fu_930_p4 = ap_const_lv8_B) and (tmp_59_fu_1109_p3 = ap_const_lv1_1)))) then 
            ap_phi_mux_head_ctx_ref_0_2_phi_fu_225_p74 <= or_ln25_fu_1139_p6;
        elsif ((((grp_fu_425_p3 = ap_const_lv1_0) and (trunc_ln9_fu_930_p4 = ap_const_lv8_C) and (tmp_77_fu_1035_p3 = ap_const_lv1_1) and (tmp_65_fu_1027_p3 = ap_const_lv1_1)) or ((tmp_62_fu_990_p3 = ap_const_lv1_1) and (trunc_ln9_fu_930_p4 = ap_const_lv8_C) and (tmp_77_fu_1035_p3 = ap_const_lv1_1) and (tmp_65_fu_1027_p3 = ap_const_lv1_1)))) then 
            ap_phi_mux_head_ctx_ref_0_2_phi_fu_225_p74 <= or_ln26_fu_1057_p6;
        elsif (((trunc_ln9_fu_930_p4 = ap_const_lv8_0) and (start_read_read_fu_204_p2 = ap_const_lv1_1))) then 
            ap_phi_mux_head_ctx_ref_0_2_phi_fu_225_p74 <= zext_ln88_fu_1661_p1;
        elsif (((grp_fu_425_p3 = ap_const_lv1_1) and (trunc_ln9_fu_930_p4 = ap_const_lv8_1) and (tmp_29_fu_1557_p3 = ap_const_lv1_0))) then 
            ap_phi_mux_head_ctx_ref_0_2_phi_fu_225_p74 <= or_ln13_fu_1577_p6;
        elsif (((grp_fu_425_p3 = ap_const_lv1_1) and (trunc_ln9_fu_930_p4 = ap_const_lv8_2) and (tmp_32_fu_1475_p3 = ap_const_lv1_0))) then 
            ap_phi_mux_head_ctx_ref_0_2_phi_fu_225_p74 <= or_ln14_fu_1497_p6;
        elsif ((trunc_ln9_fu_930_p4 = ap_const_lv8_3)) then 
            ap_phi_mux_head_ctx_ref_0_2_phi_fu_225_p74 <= or_ln6_fu_1464_p4;
        elsif ((trunc_ln9_fu_930_p4 = ap_const_lv8_4)) then 
            ap_phi_mux_head_ctx_ref_0_2_phi_fu_225_p74 <= or_ln7_fu_1449_p4;
        elsif (((grp_fu_425_p3 = ap_const_lv1_1) and (trunc_ln9_fu_930_p4 = ap_const_lv8_5) and (tmp_38_fu_1363_p3 = ap_const_lv1_0))) then 
            ap_phi_mux_head_ctx_ref_0_2_phi_fu_225_p74 <= or_ln15_fu_1385_p6;
        elsif ((trunc_ln9_fu_930_p4 = ap_const_lv8_6)) then 
            ap_phi_mux_head_ctx_ref_0_2_phi_fu_225_p74 <= or_ln8_fu_1352_p4;
        elsif ((trunc_ln9_fu_930_p4 = ap_const_lv8_7)) then 
            ap_phi_mux_head_ctx_ref_0_2_phi_fu_225_p74 <= or_ln9_fu_1337_p4;
        elsif ((trunc_ln9_fu_930_p4 = ap_const_lv8_8)) then 
            ap_phi_mux_head_ctx_ref_0_2_phi_fu_225_p74 <= or_ln10_fu_1322_p4;
        elsif (((tmp_44_fu_1236_p3 = ap_const_lv1_0) and (grp_fu_425_p3 = ap_const_lv1_1) and (trunc_ln9_fu_930_p4 = ap_const_lv8_9))) then 
            ap_phi_mux_head_ctx_ref_0_2_phi_fu_225_p74 <= or_ln16_fu_1258_p6;
        elsif (((tmp_50_fu_1154_p3 = ap_const_lv1_0) and (grp_fu_425_p3 = ap_const_lv1_1) and (trunc_ln9_fu_930_p4 = ap_const_lv8_A))) then 
            ap_phi_mux_head_ctx_ref_0_2_phi_fu_225_p74 <= or_ln17_fu_1176_p6;
        elsif (((tmp_56_fu_1072_p3 = ap_const_lv1_0) and (grp_fu_425_p3 = ap_const_lv1_1) and (trunc_ln9_fu_930_p4 = ap_const_lv8_B))) then 
            ap_phi_mux_head_ctx_ref_0_2_phi_fu_225_p74 <= or_ln18_fu_1094_p6;
        elsif (((tmp_62_fu_990_p3 = ap_const_lv1_0) and (grp_fu_425_p3 = ap_const_lv1_1) and (trunc_ln9_fu_930_p4 = ap_const_lv8_C))) then 
            ap_phi_mux_head_ctx_ref_0_2_phi_fu_225_p74 <= or_ln19_fu_1012_p6;
        elsif ((trunc_ln9_fu_930_p4 = ap_const_lv8_D)) then 
            ap_phi_mux_head_ctx_ref_0_2_phi_fu_225_p74 <= or_ln11_fu_979_p4;
        elsif (((not((trunc_ln9_fu_930_p4 = ap_const_lv8_D)) and not((trunc_ln9_fu_930_p4 = ap_const_lv8_C)) and not((trunc_ln9_fu_930_p4 = ap_const_lv8_B)) and not((trunc_ln9_fu_930_p4 = ap_const_lv8_A)) and not((trunc_ln9_fu_930_p4 = ap_const_lv8_9)) and not((trunc_ln9_fu_930_p4 = ap_const_lv8_8)) and not((trunc_ln9_fu_930_p4 = ap_const_lv8_7)) and not((trunc_ln9_fu_930_p4 = ap_const_lv8_6)) and not((trunc_ln9_fu_930_p4 = ap_const_lv8_5)) and not((trunc_ln9_fu_930_p4 = ap_const_lv8_4)) and not((trunc_ln9_fu_930_p4 = ap_const_lv8_3)) and not((trunc_ln9_fu_930_p4 = ap_const_lv8_2)) and not((trunc_ln9_fu_930_p4 = ap_const_lv8_1)) and not((trunc_ln9_fu_930_p4 = ap_const_lv8_0))) or ((tmp_31_fu_1592_p3 = ap_const_lv1_0) and (trunc_ln9_fu_930_p4 = ap_const_lv8_1) and (tmp_29_fu_1557_p3 = ap_const_lv1_1)) or ((tmp_71_fu_1600_p3 = ap_const_lv1_0) and (tmp_31_fu_1592_p3 = ap_const_lv1_1) and (trunc_ln9_fu_930_p4 = ap_const_lv8_1) and (tmp_29_fu_1557_p3 = ap_const_lv1_1)) or ((tmp_35_fu_1512_p3 = ap_const_lv1_0) and (trunc_ln9_fu_930_p4 
    = ap_const_lv8_2) and (tmp_32_fu_1475_p3 = ap_const_lv1_1)) or ((tmp_72_fu_1520_p3 = ap_const_lv1_0) and (tmp_35_fu_1512_p3 = ap_const_lv1_1) and (trunc_ln9_fu_930_p4 = ap_const_lv8_2) and (tmp_32_fu_1475_p3 = ap_const_lv1_1)) or ((tmp_41_fu_1400_p3 = ap_const_lv1_0) and (trunc_ln9_fu_930_p4 = ap_const_lv8_5) and (tmp_38_fu_1363_p3 = ap_const_lv1_1)) or ((tmp_73_fu_1408_p3 = ap_const_lv1_0) and (tmp_41_fu_1400_p3 = ap_const_lv1_1) and (trunc_ln9_fu_930_p4 = ap_const_lv8_5) and (tmp_38_fu_1363_p3 = ap_const_lv1_1)) or ((tmp_44_fu_1236_p3 = ap_const_lv1_1) and (tmp_47_fu_1273_p3 = ap_const_lv1_0) and (trunc_ln9_fu_930_p4 = ap_const_lv8_9)) or ((tmp_44_fu_1236_p3 = ap_const_lv1_1) and (tmp_74_fu_1281_p3 = ap_const_lv1_0) and (tmp_47_fu_1273_p3 = ap_const_lv1_1) and (trunc_ln9_fu_930_p4 = ap_const_lv8_9)) or ((tmp_50_fu_1154_p3 = ap_const_lv1_1) and (tmp_53_fu_1191_p3 = ap_const_lv1_0) and (trunc_ln9_fu_930_p4 = ap_const_lv8_A)) or ((tmp_50_fu_1154_p3 = ap_const_lv1_1) and (tmp_75_fu_1199_p3 = ap_const_lv1_0) and 
    (tmp_53_fu_1191_p3 = ap_const_lv1_1) and (trunc_ln9_fu_930_p4 = ap_const_lv8_A)) or ((trunc_ln9_fu_930_p4 = ap_const_lv8_0) and (start_read_read_fu_204_p2 = ap_const_lv1_0)) or ((tmp_56_fu_1072_p3 = ap_const_lv1_1) and (trunc_ln9_fu_930_p4 = ap_const_lv8_B) and (tmp_59_fu_1109_p3 = ap_const_lv1_0)) or ((tmp_56_fu_1072_p3 = ap_const_lv1_1) and (tmp_76_fu_1117_p3 = ap_const_lv1_0) and (trunc_ln9_fu_930_p4 = ap_const_lv8_B) and (tmp_59_fu_1109_p3 = ap_const_lv1_1)) or ((grp_fu_425_p3 = ap_const_lv1_0) and (trunc_ln9_fu_930_p4 = ap_const_lv8_C) and (tmp_65_fu_1027_p3 = ap_const_lv1_0)) or ((grp_fu_425_p3 = ap_const_lv1_0) and (trunc_ln9_fu_930_p4 = ap_const_lv8_C) and (tmp_77_fu_1035_p3 = ap_const_lv1_0) and (tmp_65_fu_1027_p3 = ap_const_lv1_1)) or ((grp_fu_425_p3 = ap_const_lv1_0) and (trunc_ln9_fu_930_p4 = ap_const_lv8_B) and (tmp_59_fu_1109_p3 = ap_const_lv1_0)) or ((grp_fu_425_p3 = ap_const_lv1_0) and (tmp_31_fu_1592_p3 = ap_const_lv1_0) and (trunc_ln9_fu_930_p4 = ap_const_lv8_1)) or ((grp_fu_425_p3 = ap_const_lv1_0) 
    and (tmp_71_fu_1600_p3 = ap_const_lv1_0) and (tmp_31_fu_1592_p3 = ap_const_lv1_1) and (trunc_ln9_fu_930_p4 = ap_const_lv8_1)) or ((grp_fu_425_p3 = ap_const_lv1_0) and (tmp_35_fu_1512_p3 = ap_const_lv1_0) and (trunc_ln9_fu_930_p4 = ap_const_lv8_2)) or ((grp_fu_425_p3 = ap_const_lv1_0) and (tmp_72_fu_1520_p3 = ap_const_lv1_0) and (tmp_35_fu_1512_p3 = ap_const_lv1_1) and (trunc_ln9_fu_930_p4 = ap_const_lv8_2)) or ((grp_fu_425_p3 = ap_const_lv1_0) and (tmp_41_fu_1400_p3 = ap_const_lv1_0) and (trunc_ln9_fu_930_p4 = ap_const_lv8_5)) or ((grp_fu_425_p3 = ap_const_lv1_0) and (tmp_73_fu_1408_p3 = ap_const_lv1_0) and (tmp_41_fu_1400_p3 = ap_const_lv1_1) and (trunc_ln9_fu_930_p4 = ap_const_lv8_5)) or ((grp_fu_425_p3 = ap_const_lv1_0) and (tmp_47_fu_1273_p3 = ap_const_lv1_0) and (trunc_ln9_fu_930_p4 = ap_const_lv8_9)) or ((grp_fu_425_p3 = ap_const_lv1_0) and (tmp_74_fu_1281_p3 = ap_const_lv1_0) and (tmp_47_fu_1273_p3 = ap_const_lv1_1) and (trunc_ln9_fu_930_p4 = ap_const_lv8_9)) or ((grp_fu_425_p3 = ap_const_lv1_0) and (tmp_53_fu_1191_p3 
    = ap_const_lv1_0) and (trunc_ln9_fu_930_p4 = ap_const_lv8_A)) or ((grp_fu_425_p3 = ap_const_lv1_0) and (tmp_75_fu_1199_p3 = ap_const_lv1_0) and (tmp_53_fu_1191_p3 = ap_const_lv1_1) and (trunc_ln9_fu_930_p4 = ap_const_lv8_A)) or ((grp_fu_425_p3 = ap_const_lv1_0) and (tmp_76_fu_1117_p3 = ap_const_lv1_0) and (trunc_ln9_fu_930_p4 = ap_const_lv8_B) and (tmp_59_fu_1109_p3 = ap_const_lv1_1)) or ((tmp_62_fu_990_p3 = ap_const_lv1_1) and (trunc_ln9_fu_930_p4 = ap_const_lv8_C) and (tmp_65_fu_1027_p3 = ap_const_lv1_0)) or ((tmp_62_fu_990_p3 = ap_const_lv1_1) and (trunc_ln9_fu_930_p4 = ap_const_lv8_C) and (tmp_77_fu_1035_p3 = ap_const_lv1_0) and (tmp_65_fu_1027_p3 = ap_const_lv1_1)))) then 
            ap_phi_mux_head_ctx_ref_0_2_phi_fu_225_p74 <= head_ctx_ref_0_1_fu_865_p9;
        else 
            ap_phi_mux_head_ctx_ref_0_2_phi_fu_225_p74 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;

    ap_ready <= ap_const_logic_1;
    ap_return_0 <= icmp_ln186_fu_1666_p2;
    ap_return_1 <= ap_phi_mux_head_ctx_ref_0_2_phi_fu_225_p74;
    grp_fu_416_p4 <= tmp_fu_901_p9(65 downto 40);
    grp_fu_425_p3 <= tmp_fu_901_p9(40 downto 40);
    grp_fu_432_p4 <= tmp_fu_901_p9(65 downto 59);
    grp_fu_441_p4 <= tmp_fu_901_p9(65 downto 58);
    grp_fu_450_p4 <= tmp_fu_901_p9(65 downto 57);
    grp_fu_459_p4 <= tmp_fu_901_p9(65 downto 56);
    grp_fu_468_p4 <= tmp_fu_901_p9(65 downto 55);
    grp_fu_477_p4 <= tmp_fu_901_p9(65 downto 54);
    grp_fu_486_p4 <= tmp_fu_901_p9(65 downto 53);
    head_ctx_ref_0_1_fu_865_p6 <= 
        select_ln61_fu_779_p3 when (or_ln62_5_fu_811_p2(0) = '1') else 
        select_ln50_fu_533_p3;
    head_ctx_ref_0_1_fu_865_p7 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
    icmp_ln186_fu_1666_p2 <= "1" when (ap_phi_mux_empty_phi_fu_304_p74 = ap_const_lv8_E) else "0";
    icmp_ln50_fu_523_p2 <= "0" when (trunc_ln50_fu_519_p1 = layer_idx) else "1";
    or_ln10_fu_1322_p4 <= ((grp_fu_416_p4 & ap_const_lv8_9) & trunc_ln135_fu_1318_p1);
    or_ln11_fu_979_p4 <= ((grp_fu_416_p4 & ap_const_lv8_E) & trunc_ln178_fu_975_p1);
    or_ln12_fu_1651_p4 <= ((tmp_28_fu_1637_p4 & ap_const_lv11_1) & trunc_ln70_fu_1647_p1);
    or_ln13_fu_1577_p6 <= ((((grp_fu_486_p4 & ap_const_lv1_1) & tmp_68_fu_1565_p3) & ap_const_lv9_3) & trunc_ln92_fu_1573_p1);
    or_ln14_fu_1497_p6 <= ((((grp_fu_477_p4 & ap_const_lv1_1) & tmp_34_fu_1483_p4) & ap_const_lv9_5) & trunc_ln103_fu_1493_p1);
    or_ln15_fu_1385_p6 <= ((((grp_fu_468_p4 & ap_const_lv1_1) & tmp_37_fu_1371_p4) & ap_const_lv9_7) & trunc_ln119_fu_1381_p1);
    or_ln16_fu_1258_p6 <= ((((grp_fu_459_p4 & ap_const_lv1_1) & tmp_40_fu_1244_p4) & ap_const_lv9_9) & trunc_ln139_fu_1254_p1);
    or_ln17_fu_1176_p6 <= ((((grp_fu_450_p4 & ap_const_lv1_1) & tmp_43_fu_1162_p4) & ap_const_lv9_B) & trunc_ln149_fu_1172_p1);
    or_ln18_fu_1094_p6 <= ((((grp_fu_441_p4 & ap_const_lv1_1) & tmp_46_fu_1080_p4) & ap_const_lv9_D) & trunc_ln159_fu_1090_p1);
    or_ln19_fu_1012_p6 <= ((((grp_fu_432_p4 & ap_const_lv1_1) & tmp_49_fu_998_p4) & ap_const_lv9_F) & trunc_ln169_fu_1008_p1);
    or_ln1_fu_611_p4 <= ((tmp_5_fu_597_p4 & ap_const_lv1_1) & trunc_ln57_fu_607_p1);
    or_ln20_fu_1622_p6 <= ((((grp_fu_486_p4 & ap_const_lv1_0) & tmp_52_fu_1608_p4) & ap_const_lv8_2) & trunc_ln97_fu_1618_p1);
    or_ln21_fu_1542_p6 <= ((((grp_fu_477_p4 & ap_const_lv1_0) & tmp_55_fu_1528_p4) & ap_const_lv8_3) & trunc_ln108_fu_1538_p1);
    or_ln22_fu_1430_p6 <= ((((grp_fu_468_p4 & ap_const_lv1_0) & tmp_58_fu_1416_p4) & ap_const_lv8_6) & trunc_ln124_fu_1426_p1);
    or_ln23_fu_1303_p6 <= ((((grp_fu_459_p4 & ap_const_lv1_0) & tmp_61_fu_1289_p4) & ap_const_lv8_A) & trunc_ln143_fu_1299_p1);
    or_ln24_fu_1221_p6 <= ((((grp_fu_450_p4 & ap_const_lv1_0) & tmp_64_fu_1207_p4) & ap_const_lv8_B) & trunc_ln153_fu_1217_p1);
    or_ln25_fu_1139_p6 <= ((((grp_fu_441_p4 & ap_const_lv1_0) & tmp_67_fu_1125_p4) & ap_const_lv8_C) & trunc_ln163_fu_1135_p1);
    or_ln26_fu_1057_p6 <= ((((grp_fu_432_p4 & ap_const_lv1_0) & tmp_70_fu_1043_p4) & ap_const_lv8_D) & trunc_ln173_fu_1053_p1);
    or_ln2_fu_651_p4 <= ((tmp_7_fu_637_p4 & ap_const_lv1_1) & trunc_ln58_fu_647_p1);
    or_ln3_fu_691_p4 <= ((tmp_9_fu_677_p4 & ap_const_lv1_1) & trunc_ln59_fu_687_p1);
    or_ln4_fu_731_p4 <= ((tmp_s_fu_717_p4 & ap_const_lv1_1) & trunc_ln60_fu_727_p1);
    or_ln5_fu_769_p4 <= ((tmp_14_fu_757_p3 & ap_const_lv1_1) & trunc_ln61_fu_765_p1);
    or_ln62_1_fu_793_p2 <= (tmp_6_fu_589_p3 or or_ln62_fu_787_p2);
    or_ln62_2_fu_799_p2 <= (tmp_13_fu_749_p3 or tmp_12_fu_709_p3);
    or_ln62_3_fu_805_p2 <= (tmp_10_fu_669_p3 or or_ln62_2_fu_799_p2);
    or_ln62_4_fu_837_p3 <= (ap_const_lv1_1 & trunc_ln62_fu_833_p1);
    or_ln62_5_fu_811_p2 <= (or_ln62_3_fu_805_p2 or or_ln62_1_fu_793_p2);
    or_ln62_fu_787_p2 <= (tmp_8_fu_629_p3 or tmp_4_fu_549_p3);
    or_ln6_fu_1464_p4 <= ((grp_fu_416_p4 & ap_const_lv8_4) & trunc_ln112_fu_1460_p1);
    or_ln7_fu_1449_p4 <= ((grp_fu_416_p4 & ap_const_lv8_5) & trunc_ln115_fu_1445_p1);
    or_ln8_fu_1352_p4 <= ((grp_fu_416_p4 & ap_const_lv8_7) & trunc_ln129_fu_1348_p1);
    or_ln9_fu_1337_p4 <= ((grp_fu_416_p4 & ap_const_lv8_8) & trunc_ln132_fu_1333_p1);
    or_ln_fu_571_p4 <= ((tmp_3_fu_557_p4 & ap_const_lv1_1) & trunc_ln56_fu_567_p1);
    sel_tmp2_fu_857_p3 <= (and_ln62_fu_845_p2 & xor_ln55_fu_851_p2);
    select_ln50_fu_533_p3 <= 
        zext_ln6_fu_529_p1 when (icmp_ln50_fu_523_p2(0) = '1') else 
        and_ln_fu_509_p4;
    select_ln56_fu_581_p3 <= 
        or_ln_fu_571_p4 when (tmp_4_fu_549_p3(0) = '1') else 
        select_ln50_fu_533_p3;
    select_ln57_fu_621_p3 <= 
        or_ln1_fu_611_p4 when (tmp_6_fu_589_p3(0) = '1') else 
        select_ln56_fu_581_p3;
    select_ln58_fu_661_p3 <= 
        or_ln2_fu_651_p4 when (tmp_8_fu_629_p3(0) = '1') else 
        select_ln57_fu_621_p3;
    select_ln59_fu_701_p3 <= 
        or_ln3_fu_691_p4 when (tmp_10_fu_669_p3(0) = '1') else 
        select_ln58_fu_661_p3;
    select_ln60_fu_741_p3 <= 
        or_ln4_fu_731_p4 when (tmp_12_fu_709_p3(0) = '1') else 
        select_ln59_fu_701_p3;
    select_ln61_fu_779_p3 <= 
        or_ln5_fu_769_p4 when (tmp_13_fu_749_p3(0) = '1') else 
        select_ln60_fu_741_p3;
    start_read_read_fu_204_p2 <= start_r;
    tmp_10_fu_669_p3 <= select_ln58_fu_661_p3(55 downto 55);
    tmp_12_fu_709_p3 <= select_ln59_fu_701_p3(56 downto 56);
    tmp_13_fu_749_p3 <= select_ln60_fu_741_p3(57 downto 57);
    tmp_14_fu_757_p3 <= select_ln60_fu_741_p3(65 downto 65);
    tmp_15_fu_825_p3 <= select_ln61_fu_779_p3(58 downto 58);
    tmp_1_fu_495_p4 <= p_read(65 downto 51);
    tmp_28_fu_1637_p4 <= tmp_fu_901_p9(51 downto 43);
    tmp_29_fu_1557_p3 <= tmp_fu_901_p9(52 downto 52);
    tmp_2_fu_541_p3 <= select_ln50_fu_533_p3(41 downto 41);
    tmp_31_fu_1592_p3 <= tmp_fu_901_p9(59 downto 59);
    tmp_32_fu_1475_p3 <= tmp_fu_901_p9(53 downto 53);
    tmp_34_fu_1483_p4 <= tmp_fu_901_p9(52 downto 51);
    tmp_35_fu_1512_p3 <= tmp_fu_901_p9(60 downto 60);
    tmp_37_fu_1371_p4 <= tmp_fu_901_p9(53 downto 51);
    tmp_38_fu_1363_p3 <= tmp_fu_901_p9(54 downto 54);
    tmp_3_fu_557_p4 <= select_ln50_fu_533_p3(65 downto 60);
    tmp_40_fu_1244_p4 <= tmp_fu_901_p9(54 downto 51);
    tmp_41_fu_1400_p3 <= tmp_fu_901_p9(61 downto 61);
    tmp_43_fu_1162_p4 <= tmp_fu_901_p9(55 downto 51);
    tmp_44_fu_1236_p3 <= tmp_fu_901_p9(55 downto 55);
    tmp_46_fu_1080_p4 <= tmp_fu_901_p9(56 downto 51);
    tmp_47_fu_1273_p3 <= tmp_fu_901_p9(62 downto 62);
    tmp_49_fu_998_p4 <= tmp_fu_901_p9(57 downto 51);
    tmp_4_fu_549_p3 <= select_ln50_fu_533_p3(52 downto 52);
    tmp_50_fu_1154_p3 <= tmp_fu_901_p9(56 downto 56);
    tmp_52_fu_1608_p4 <= tmp_fu_901_p9(51 downto 40);
    tmp_53_fu_1191_p3 <= tmp_fu_901_p9(63 downto 63);
    tmp_55_fu_1528_p4 <= tmp_fu_901_p9(52 downto 40);
    tmp_56_fu_1072_p3 <= tmp_fu_901_p9(57 downto 57);
    tmp_58_fu_1416_p4 <= tmp_fu_901_p9(53 downto 40);
    tmp_59_fu_1109_p3 <= tmp_fu_901_p9(64 downto 64);
    tmp_5_fu_597_p4 <= select_ln56_fu_581_p3(65 downto 61);
    tmp_61_fu_1289_p4 <= tmp_fu_901_p9(54 downto 40);
    tmp_62_fu_990_p3 <= tmp_fu_901_p9(58 downto 58);
    tmp_64_fu_1207_p4 <= tmp_fu_901_p9(55 downto 40);
    tmp_65_fu_1027_p3 <= tmp_fu_901_p9(65 downto 65);
    tmp_67_fu_1125_p4 <= tmp_fu_901_p9(56 downto 40);
    tmp_68_fu_1565_p3 <= tmp_fu_901_p9(51 downto 51);
    tmp_6_fu_589_p3 <= select_ln56_fu_581_p3(53 downto 53);
    tmp_70_fu_1043_p4 <= tmp_fu_901_p9(57 downto 40);
    tmp_71_fu_1600_p3 <= tmp_fu_901_p9(52 downto 52);
    tmp_72_fu_1520_p3 <= tmp_fu_901_p9(53 downto 53);
    tmp_73_fu_1408_p3 <= tmp_fu_901_p9(54 downto 54);
    tmp_74_fu_1281_p3 <= tmp_fu_901_p9(55 downto 55);
    tmp_75_fu_1199_p3 <= tmp_fu_901_p9(56 downto 56);
    tmp_76_fu_1117_p3 <= tmp_fu_901_p9(57 downto 57);
    tmp_77_fu_1035_p3 <= tmp_fu_901_p9(58 downto 58);
    tmp_7_fu_637_p4 <= select_ln57_fu_621_p3(65 downto 62);
    tmp_8_fu_629_p3 <= select_ln57_fu_621_p3(54 downto 54);
    tmp_9_fu_677_p4 <= select_ln58_fu_661_p3(65 downto 63);
    tmp_fu_901_p7 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
    tmp_s_fu_717_p4 <= select_ln59_fu_701_p3(65 downto 64);
    trunc_ln103_fu_1493_p1 <= tmp_fu_901_p9(42 - 1 downto 0);
    trunc_ln108_fu_1538_p1 <= tmp_fu_901_p9(32 - 1 downto 0);
    trunc_ln112_fu_1460_p1 <= tmp_fu_901_p9(32 - 1 downto 0);
    trunc_ln115_fu_1445_p1 <= tmp_fu_901_p9(32 - 1 downto 0);
    trunc_ln119_fu_1381_p1 <= tmp_fu_901_p9(42 - 1 downto 0);
    trunc_ln124_fu_1426_p1 <= tmp_fu_901_p9(32 - 1 downto 0);
    trunc_ln129_fu_1348_p1 <= tmp_fu_901_p9(32 - 1 downto 0);
    trunc_ln132_fu_1333_p1 <= tmp_fu_901_p9(32 - 1 downto 0);
    trunc_ln135_fu_1318_p1 <= tmp_fu_901_p9(32 - 1 downto 0);
    trunc_ln139_fu_1254_p1 <= tmp_fu_901_p9(42 - 1 downto 0);
    trunc_ln143_fu_1299_p1 <= tmp_fu_901_p9(32 - 1 downto 0);
    trunc_ln149_fu_1172_p1 <= tmp_fu_901_p9(42 - 1 downto 0);
    trunc_ln153_fu_1217_p1 <= tmp_fu_901_p9(32 - 1 downto 0);
    trunc_ln159_fu_1090_p1 <= tmp_fu_901_p9(42 - 1 downto 0);
    trunc_ln163_fu_1135_p1 <= tmp_fu_901_p9(32 - 1 downto 0);
    trunc_ln169_fu_1008_p1 <= tmp_fu_901_p9(42 - 1 downto 0);
    trunc_ln173_fu_1053_p1 <= tmp_fu_901_p9(32 - 1 downto 0);
    trunc_ln178_fu_975_p1 <= tmp_fu_901_p9(32 - 1 downto 0);
    trunc_ln47_fu_505_p1 <= p_read(42 - 1 downto 0);
    trunc_ln50_fu_519_p1 <= p_read(32 - 1 downto 0);
    trunc_ln56_fu_567_p1 <= select_ln50_fu_533_p3(59 - 1 downto 0);
    trunc_ln57_fu_607_p1 <= select_ln56_fu_581_p3(60 - 1 downto 0);
    trunc_ln58_fu_647_p1 <= select_ln57_fu_621_p3(61 - 1 downto 0);
    trunc_ln59_fu_687_p1 <= select_ln58_fu_661_p3(62 - 1 downto 0);
    trunc_ln60_fu_727_p1 <= select_ln59_fu_701_p3(63 - 1 downto 0);
    trunc_ln61_fu_765_p1 <= select_ln60_fu_741_p3(64 - 1 downto 0);
    trunc_ln62_fu_833_p1 <= select_ln61_fu_779_p3(65 - 1 downto 0);
    trunc_ln70_fu_1647_p1 <= tmp_fu_901_p9(32 - 1 downto 0);
    trunc_ln92_fu_1573_p1 <= tmp_fu_901_p9(42 - 1 downto 0);
    trunc_ln97_fu_1618_p1 <= tmp_fu_901_p9(32 - 1 downto 0);
    trunc_ln9_fu_930_p4 <= tmp_fu_901_p9(39 downto 32);
    xor_ln55_fu_851_p2 <= (tmp_2_fu_541_p3 xor ap_const_lv1_1);
    zext_ln6_fu_529_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(layer_idx),66));
    zext_ln88_fu_1661_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(or_ln12_fu_1651_p4),66));
end behav;
